//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/agent_logging_config_bean.go:14

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	logging "github.com/spice-framework/spice-agent/logging"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructAgentLoggingConfig_b3cd42db performs the direct construction selected for bean "agentLoggingConfig".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewAgentLoggingConfig.
func ConstructAgentLoggingConfig_b3cd42db(dependency0 daemon.Properties) (logging.Config, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewAgentLoggingConfig(dependency0)
	if err != nil {
		var zero logging.Config
		return zero, nil, fmt.Errorf("construct bean agentLoggingConfig (github.com/spice-framework/spice-agent/logging.Config, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewAgentLoggingConfig): %w", err)
	}
	return value, nil, nil
}
