//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/agent_logging_health_source_bean.go:13

package spicegen

import (
	daemon2 "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemon "github.com/spice-framework/spice-agent/daemon"
	logging "github.com/spice-framework/spice-agent/logging"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructAgentLoggingHealth_1ccf2800 performs the direct construction selected for bean "agentLoggingHealth".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|27:NewAgentLoggingHealthSource.
func ConstructAgentLoggingHealth_1ccf2800(dependency0 logging.Config, dependency1 *logging.Processor) (daemon.HealthSource, spicelifecycle.Cleanup, error) {
	value := daemon2.NewAgentLoggingHealthSource(dependency0, dependency1)
	return value, nil, nil
}
