//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/coding_config_bean.go:17

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructCodingConfig_4bbfc767 performs the direct construction selected for bean "codingConfig".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewCodingConfig.
func ConstructCodingConfig_4bbfc767(dependency0 daemon.Properties, dependency1 daemonprocess.RootRegistry) (coding.Config, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewCodingConfig(dependency0, dependency1)
	if err != nil {
		var zero coding.Config
		return zero, nil, fmt.Errorf("construct bean codingConfig (github.com/spice-framework/spice-agent-tools-coding.Config, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewCodingConfig): %w", err)
	}
	return value, nil, nil
}
