//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/daemon_root_registry_bean.go:18

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructDaemonRootRegistry_5e3757f8 performs the direct construction selected for bean "daemonRootRegistry".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRootRegistry.
func ConstructDaemonRootRegistry_5e3757f8() (daemonprocess.RootRegistry, spicelifecycle.Cleanup, error) {
	value, cleanup, err := daemon.NewRootRegistry()
	if err != nil {
		var zero daemonprocess.RootRegistry
		return zero, nil, fmt.Errorf("construct bean daemonRootRegistry (github.com/spice-framework/spice-agent-coding/internal/daemonprocess.RootRegistry, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRootRegistry): %w", err)
	}
	return value, cleanup, nil
}
