//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/daemon_interaction_broker_bean.go:13

package spicegen

import (
	daemon2 "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemon "github.com/spice-framework/spice-agent/daemon"
	interaction "github.com/spice-framework/spice-agent/interaction"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructDaemonInteractionBroker_bf812f17 performs the direct construction selected for bean "daemonInteractionBroker".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewInteractionBroker.
func ConstructDaemonInteractionBroker_bf812f17(dependency0 *daemon.PendingHub) (interaction.Broker, spicelifecycle.Cleanup, error) {
	value := daemon2.NewInteractionBroker(dependency0)
	return value, nil, nil
}
