//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/daemon_listener_factory_bean.go:8

package spicegen

import (
	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructDaemonListenerFactory_66b0ce4f performs the direct construction selected for bean "daemonListenerFactory".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewListenerFactory.
func ConstructDaemonListenerFactory_66b0ce4f() (daemon.ListenerFactory, spicelifecycle.Cleanup, error) {
	value := daemon.NewListenerFactory()
	return value, nil, nil
}
