//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/daemon_root_bean.go:16

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructDaemonRoot_3c8cd2a3 performs the direct construction selected for bean "daemonRoot".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|7:NewRoot.
func ConstructDaemonRoot_3c8cd2a3(dependency0 daemonprocess.RootRegistry) (*daemon.Root, spicelifecycle.Cleanup, error) {
	value, cleanup, err := daemon.NewRoot(dependency0)
	if err != nil {
		var zero *daemon.Root
		return zero, nil, fmt.Errorf("construct bean daemonRoot (*github.com/spice-framework/spice-agent-coding/internal/daemon.Root, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|7:NewRoot): %w", err)
	}
	return value, cleanup, nil
}
