//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/daemon_engine_bean.go:25

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	agent "github.com/spice-framework/spice-agent/agent"
	client "github.com/spice-framework/spice-agent/client"
	event "github.com/spice-framework/spice-agent/event"
	interaction "github.com/spice-framework/spice-agent/interaction"
	logging "github.com/spice-framework/spice-agent/logging"
	model "github.com/spice-framework/spice-agent/model"
	stage "github.com/spice-framework/spice-agent/stage"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructDaemonEngine_10b0c974 performs the direct construction selected for bean "daemonEngine".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine.
func ConstructDaemonEngine_10b0c974(dependency0 model.Provider, dependency1 stage.ToolPlanSource, dependency2 interaction.Broker, dependency3 agent.IDSource, dependency4 client.Limits, dependency5 coding.Config, dependency6 *logging.Processor, dependency7 []*event.BestEffortObserver) (*agent.Engine, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewEngine(dependency0, dependency1, dependency2, dependency3, dependency4, dependency5, dependency6, dependency7)
	if err != nil {
		var zero *agent.Engine
		return zero, nil, fmt.Errorf("construct bean daemonEngine (*github.com/spice-framework/spice-agent/agent.Engine, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine): %w", err)
	}
	return value, nil, nil
}
