//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/daemon_id_source_bean.go:15

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	agent "github.com/spice-framework/spice-agent/agent"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructDaemonIDSource_f337ceca performs the direct construction selected for bean "daemonIDSource".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|11:NewIDSource.
func ConstructDaemonIDSource_f337ceca() (agent.IDSource, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewIDSource()
	if err != nil {
		var zero agent.IDSource
		return zero, nil, fmt.Errorf("construct bean daemonIDSource (github.com/spice-framework/spice-agent/agent.IDSource, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|11:NewIDSource): %w", err)
	}
	return value, nil, nil
}
