//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/definition_set_bean.go:14

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemon2 "github.com/spice-framework/spice-agent/daemon"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructDefinitionSet_a8acae3e performs the direct construction selected for bean "definitionSet".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewDefinitionSet.
func ConstructDefinitionSet_a8acae3e(dependency0 daemon.Properties) (daemon2.DefinitionSet, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewDefinitionSet(dependency0)
	if err != nil {
		var zero daemon2.DefinitionSet
		return zero, nil, fmt.Errorf("construct bean definitionSet (github.com/spice-framework/spice-agent/daemon.DefinitionSet, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewDefinitionSet): %w", err)
	}
	return value, nil, nil
}
