//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/endpoint_scope_bean.go:12

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructEndpointScope_4a25ec50 performs the direct construction selected for bean "endpointScope".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointScope.
func ConstructEndpointScope_4a25ec50() (endpoint.UserScope, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewEndpointScope()
	if err != nil {
		var zero endpoint.UserScope
		return zero, nil, fmt.Errorf("construct bean endpointScope (github.com/spice-framework/spice-agent/daemon/endpoint.UserScope, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointScope): %w", err)
	}
	return value, nil, nil
}
