//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/endpoint_store_bean.go:17

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructEndpointStore_c41f25a3 performs the direct construction selected for bean "endpointStore".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointStore.
func ConstructEndpointStore_c41f25a3(dependency0 endpoint.UserScope) (*endpoint.Store, spicelifecycle.Cleanup, error) {
	value, cleanup, err := daemon.NewEndpointStore(dependency0)
	if err != nil {
		var zero *endpoint.Store
		return zero, nil, fmt.Errorf("construct bean endpointStore (*github.com/spice-framework/spice-agent/daemon/endpoint.Store, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointStore): %w", err)
	}
	return value, cleanup, nil
}
