//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/endpoint_token_bean.go:11

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructEndpointToken_94cf31d6 performs the direct construction selected for bean "endpointToken".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointToken.
func ConstructEndpointToken_94cf31d6() (endpoint.Token, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewEndpointToken()
	if err != nil {
		var zero endpoint.Token
		return zero, nil, fmt.Errorf("construct bean endpointToken (github.com/spice-framework/spice-agent/daemon/endpoint.Token, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointToken): %w", err)
	}
	return value, nil, nil
}
