//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/grpc_server_bean.go:15

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	client "github.com/spice-framework/spice-agent/client"
	daemon2 "github.com/spice-framework/spice-agent/daemon"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	grpcserver "github.com/spice-framework/spice-agent/daemon/grpcserver"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructGrpcServer_97f7cc1f performs the direct construction selected for bean "grpcServer".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewGRPCServer.
func ConstructGrpcServer_97f7cc1f(dependency0 *daemon.Root, dependency1 endpoint.Token, dependency2 *daemon2.RunHost, dependency3 *daemon2.SessionStore, dependency4 client.Build) (*grpcserver.Server, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewGRPCServer(dependency0, dependency1, dependency2, dependency3, dependency4)
	if err != nil {
		var zero *grpcserver.Server
		return zero, nil, fmt.Errorf("construct bean grpcServer (*github.com/spice-framework/spice-agent/daemon/grpcserver.Server, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewGRPCServer): %w", err)
	}
	return value, nil, nil
}
