//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/host.go:24
// Source: internal/daemon/host.go:32
// Source: internal/daemon/host.go:43
// Source: internal/daemon/host.go:50
// Source: internal/daemon/host.go:64
// Source: internal/daemon/host.go:84
// Source: internal/daemon/host.go:91
// Source: internal/daemon/host.go:99
// Source: internal/daemon/host.go:110
// Source: internal/daemon/host.go:118
// Source: internal/daemon/host.go:134
// Source: internal/daemon/host.go:150
// Source: internal/daemon/host.go:181

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	agent "github.com/spice-framework/spice-agent/agent"
	client "github.com/spice-framework/spice-agent/client"
	daemon2 "github.com/spice-framework/spice-agent/daemon"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	grpcserver "github.com/spice-framework/spice-agent/daemon/grpcserver"
	pluginv1 "github.com/spice-framework/spice-agent/plugin/v1"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructRunHost_4a91e2b0 performs the direct construction selected for bean "runHost".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRunHost.
func ConstructRunHost_4a91e2b0(dependency0 *daemon.Root, dependency1 *agent.Engine, dependency2 *daemon2.RunAuthority, dependency3 *daemon2.SessionStore, dependency4 *daemon2.Ledger, dependency5 *daemon2.PendingHub, dependency6 daemon2.DefinitionSet, dependency7 []daemon2.HealthSource, dependency8 client.Limits) (*daemon2.RunHost, spicelifecycle.Cleanup, error) {
	value, cleanup, err := daemon.NewRunHost(dependency0, dependency1, dependency2, dependency3, dependency4, dependency5, dependency6, dependency7, dependency8)
	if err != nil {
		var zero *daemon2.RunHost
		return zero, nil, fmt.Errorf("construct bean runHost (*github.com/spice-framework/spice-agent/daemon.RunHost, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRunHost): %w", err)
	}
	return value, cleanup, nil
}

// ConstructGrpcServer_97f7cc1f performs the direct construction selected for bean "grpcServer".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewGRPCServer.
func ConstructGrpcServer_97f7cc1f(dependency0 *daemon.Root, dependency1 endpoint.Token, dependency2 *daemon2.RunHost, dependency3 *daemon2.SessionStore, dependency4 client.Build) (*grpcserver.Server, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewGRPCServer(dependency0, dependency1, dependency2, dependency3, dependency4)
	if err != nil {
		var zero *grpcserver.Server
		return zero, nil, fmt.Errorf("construct bean grpcServer (*github.com/spice-framework/spice-agent/daemon/grpcserver.Server, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewGRPCServer): %w", err)
	}
	return value, nil, nil
}

// ConstructServerBuild_a30ee9e7 performs the direct construction selected for bean "serverBuild".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|14:NewServerBuild.
func ConstructServerBuild_a30ee9e7() (client.Build, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewServerBuild()
	if err != nil {
		var zero client.Build
		return zero, nil, fmt.Errorf("construct bean serverBuild (github.com/spice-framework/spice-agent/client.Build, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|14:NewServerBuild): %w", err)
	}
	return value, nil, nil
}

// ConstructRunAuthority_af30e6a5 performs the direct construction selected for bean "runAuthority".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRunAuthority.
func ConstructRunAuthority_af30e6a5(dependency0 daemon.Properties) (*daemon2.RunAuthority, spicelifecycle.Cleanup, error) {
	value, cleanup, err := daemon.NewRunAuthority(dependency0)
	if err != nil {
		var zero *daemon2.RunAuthority
		return zero, nil, fmt.Errorf("construct bean runAuthority (*github.com/spice-framework/spice-agent/daemon.RunAuthority, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRunAuthority): %w", err)
	}
	return value, cleanup, nil
}

// ConstructSessionStore_5ce90ba9 performs the direct construction selected for bean "sessionStore".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewSessionStore.
func ConstructSessionStore_5ce90ba9(dependency0 *daemon.Root) (*daemon2.SessionStore, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewSessionStore(dependency0)
	if err != nil {
		var zero *daemon2.SessionStore
		return zero, nil, fmt.Errorf("construct bean sessionStore (*github.com/spice-framework/spice-agent/daemon.SessionStore, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewSessionStore): %w", err)
	}
	return value, nil, nil
}

// ConstructDefinitionSet_a8acae3e performs the direct construction selected for bean "definitionSet".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewDefinitionSet.
func ConstructDefinitionSet_a8acae3e(dependency0 daemon.Properties) (daemon2.DefinitionSet, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewDefinitionSet(dependency0)
	if err != nil {
		var zero daemon2.DefinitionSet
		return zero, nil, fmt.Errorf("construct bean definitionSet (github.com/spice-framework/spice-agent/daemon.DefinitionSet, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewDefinitionSet): %w", err)
	}
	return value, nil, nil
}

// ConstructEndpointScope_4a25ec50 performs the direct construction selected for bean "endpointScope".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointScope.
func ConstructEndpointScope_4a25ec50() (endpoint.UserScope, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewEndpointScope()
	if err != nil {
		var zero endpoint.UserScope
		return zero, nil, fmt.Errorf("construct bean endpointScope (github.com/spice-framework/spice-agent/daemon/endpoint.UserScope, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointScope): %w", err)
	}
	return value, nil, nil
}

// ConstructEndpointStore_c41f25a3 performs the direct construction selected for bean "endpointStore".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointStore.
func ConstructEndpointStore_c41f25a3(dependency0 endpoint.UserScope) (*endpoint.Store, spicelifecycle.Cleanup, error) {
	value, cleanup, err := daemon.NewEndpointStore(dependency0)
	if err != nil {
		var zero *endpoint.Store
		return zero, nil, fmt.Errorf("construct bean endpointStore (*github.com/spice-framework/spice-agent/daemon/endpoint.Store, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointStore): %w", err)
	}
	return value, cleanup, nil
}

// ConstructEndpointToken_94cf31d6 performs the direct construction selected for bean "endpointToken".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointToken.
func ConstructEndpointToken_94cf31d6() (endpoint.Token, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewEndpointToken()
	if err != nil {
		var zero endpoint.Token
		return zero, nil, fmt.Errorf("construct bean endpointToken (github.com/spice-framework/spice-agent/daemon/endpoint.Token, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointToken): %w", err)
	}
	return value, nil, nil
}

// ConstructServerProtocol_5afceae2 performs the direct construction selected for bean "serverProtocol".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProtocolVersion.
func ConstructServerProtocol_5afceae2() (client.ProtocolVersion, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewProtocolVersion()
	if err != nil {
		var zero client.ProtocolVersion
		return zero, nil, fmt.Errorf("construct bean serverProtocol (github.com/spice-framework/spice-agent/client.ProtocolVersion, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProtocolVersion): %w", err)
	}
	return value, nil, nil
}

// ConstructRuntimePluginHostIdentity_5b56db5e performs the direct construction selected for bean "runtimePluginHostIdentity".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHostIdentity.
func ConstructRuntimePluginHostIdentity_5b56db5e(dependency0 client.Build) (*pluginv1.BuildIdentity, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewRuntimePluginHostIdentity(dependency0)
	if err != nil {
		var zero *pluginv1.BuildIdentity
		return zero, nil, fmt.Errorf("construct bean runtimePluginHostIdentity (*github.com/spice-framework/spice-agent/plugin/v1.BuildIdentity, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHostIdentity): %w", err)
	}
	return value, nil, nil
}

// ConstructOperationLedger_4e34d52a performs the direct construction selected for bean "operationLedger".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLedger.
func ConstructOperationLedger_4e34d52a() (*daemon2.Ledger, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewLedger()
	if err != nil {
		var zero *daemon2.Ledger
		return zero, nil, fmt.Errorf("construct bean operationLedger (*github.com/spice-framework/spice-agent/daemon.Ledger, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLedger): %w", err)
	}
	return value, nil, nil
}

// ConstructServerLimits_3afc4093 performs the direct construction selected for bean "serverLimits".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLimits.
func ConstructServerLimits_3afc4093() (client.Limits, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewLimits()
	if err != nil {
		var zero client.Limits
		return zero, nil, fmt.Errorf("construct bean serverLimits (github.com/spice-framework/spice-agent/client.Limits, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLimits): %w", err)
	}
	return value, nil, nil
}
