//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/open_ai_config_bean.go:12

package spicegen

import (
	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	openaiprovider "github.com/spice-framework/spice-agent-provider-openai"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructOpenAIConfig_f13e2cf9 performs the direct construction selected for bean "openAIConfig".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewOpenAIConfig.
func ConstructOpenAIConfig_f13e2cf9(dependency0 daemon.Properties) (openaiprovider.Config, spicelifecycle.Cleanup, error) {
	value := daemon.NewOpenAIConfig(dependency0)
	return value, nil, nil
}
