//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/pending_hub_bean.go:11

package spicegen

import (
	fmt "fmt"

	daemon2 "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemon "github.com/spice-framework/spice-agent/daemon"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructPendingHub_4cbcfd89 performs the direct construction selected for bean "pendingHub".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub.
func ConstructPendingHub_4cbcfd89() (*daemon.PendingHub, spicelifecycle.Cleanup, error) {
	value, err := daemon2.NewPendingHub()
	if err != nil {
		var zero *daemon.PendingHub
		return zero, nil, fmt.Errorf("construct bean pendingHub (*github.com/spice-framework/spice-agent/daemon.PendingHub, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub): %w", err)
	}
	return value, nil, nil
}
