//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/plan.go:19
// Source: internal/daemon/plan.go:27
// Source: internal/daemon/plan.go:35

package spicegen

import (
	fmt "fmt"

	daemon2 "github.com/spice-framework/spice-agent-coding/internal/daemon"
	agent "github.com/spice-framework/spice-agent/agent"
	daemon "github.com/spice-framework/spice-agent/daemon"
	interaction "github.com/spice-framework/spice-agent/interaction"
	model "github.com/spice-framework/spice-agent/model"
	stage "github.com/spice-framework/spice-agent/stage"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructPendingHub_4cbcfd89 performs the direct construction selected for bean "pendingHub".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub.
func ConstructPendingHub_4cbcfd89() (*daemon.PendingHub, spicelifecycle.Cleanup, error) {
	value, err := daemon2.NewPendingHub()
	if err != nil {
		var zero *daemon.PendingHub
		return zero, nil, fmt.Errorf("construct bean pendingHub (*github.com/spice-framework/spice-agent/daemon.PendingHub, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub): %w", err)
	}
	return value, nil, nil
}

// ConstructDaemonInteractionBroker_bf812f17 performs the direct construction selected for bean "daemonInteractionBroker".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewInteractionBroker.
func ConstructDaemonInteractionBroker_bf812f17(dependency0 *daemon.PendingHub) (interaction.Broker, spicelifecycle.Cleanup, error) {
	value := daemon2.NewInteractionBroker(dependency0)
	return value, nil, nil
}

// ConstructDaemonEngine_10b0c974 performs the direct construction selected for bean "daemonEngine".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine.
func ConstructDaemonEngine_10b0c974(dependency0 model.Provider, dependency1 stage.ToolPlanSource, dependency2 interaction.Broker, dependency3 agent.IDSource) (*agent.Engine, spicelifecycle.Cleanup, error) {
	value, err := daemon2.NewEngine(dependency0, dependency1, dependency2, dependency3)
	if err != nil {
		var zero *agent.Engine
		return zero, nil, fmt.Errorf("construct bean daemonEngine (*github.com/spice-framework/spice-agent/agent.Engine, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine): %w", err)
	}
	return value, nil, nil
}
