//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/process.go:14
// Source: internal/daemon/process.go:22

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	process "github.com/spice-framework/spice-agent/process"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructProcessLauncher_6dd45eb0 performs the direct construction selected for bean "processLauncher".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProcessLauncher.
func ConstructProcessLauncher_6dd45eb0(dependency0 daemonprocess.RootRegistry) (process.Launcher, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewProcessLauncher(dependency0)
	if err != nil {
		var zero process.Launcher
		return zero, nil, fmt.Errorf("construct bean processLauncher (github.com/spice-framework/spice-agent/process.Launcher, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProcessLauncher): %w", err)
	}
	return value, nil, nil
}

// ConstructProcessResolver_4d5da368 performs the direct construction selected for bean "processResolver".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewExecutableResolver.
func ConstructProcessResolver_4d5da368() (process.ExecutableResolver, spicelifecycle.Cleanup, error) {
	value := daemon.NewExecutableResolver()
	return value, nil, nil
}
