//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/process_resolver_bean.go:13

package spicegen

import (
	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	process "github.com/spice-framework/spice-agent/process"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructProcessResolver_4d5da368 performs the direct construction selected for bean "processResolver".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewExecutableResolver.
func ConstructProcessResolver_4d5da368() (process.ExecutableResolver, spicelifecycle.Cleanup, error) {
	value := daemon.NewExecutableResolver()
	return value, nil, nil
}
