//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/properties.go:17

package spicegen

import (
	fmt "fmt"
	time "time"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	spiceconfig "github.com/spice-framework/spice/config"
)

// BindProperties_641bb6f4 binds the validated configuration declared by spice:symbol:v1|type|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:Properties.
func BindProperties_641bb6f4(configurationSnapshot spiceconfig.Snapshot) (daemon.Properties, error) {
	value := daemon.Properties{}
	if _, configured := configurationSnapshot.Lookup("agent.openai.api-key"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.openai.api-key")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.openai.api-key for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.APIKey: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.APIKey = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.openai.base-url"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.openai.base-url")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.openai.base-url for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.BaseURL: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.BaseURL = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.openai.organization"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.openai.organization")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.openai.organization for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.Organization: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.Organization = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.openai.project"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.openai.project")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.openai.project for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.Project: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.Project = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.openai.timeout"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("agent.openai.timeout")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.openai.timeout for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.ProviderTimeout: %w", valueErr)
		}
		convertedValue := time.Duration(rawValue)
		value.ProviderTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.openai.max-retries"); configured {
		rawValue, valueErr := configurationSnapshot.Integer("agent.openai.max-retries")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.openai.max-retries for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.ProviderRetries: %w", valueErr)
		}
		convertedValue := int(rawValue)
		if int64(convertedValue) != rawValue {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.openai.max-retries for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.ProviderRetries: value is outside int")
		}
		value.ProviderRetries = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.model"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.model")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.model for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.Model: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.Model = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.workspace"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.workspace")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.workspace for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.Workspace: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.Workspace = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.run-authority-directory"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.run-authority-directory")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.run-authority-directory for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.RunAuthorityDirectory: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.RunAuthorityDirectory = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.logging.mailbox-capacity"); configured {
		rawValue, valueErr := configurationSnapshot.Integer("agent.logging.mailbox-capacity")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.logging.mailbox-capacity for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.LoggingMailboxCapacity: %w", valueErr)
		}
		convertedValue := int(rawValue)
		if int64(convertedValue) != rawValue {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.logging.mailbox-capacity for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.LoggingMailboxCapacity: value is outside int")
		}
		value.LoggingMailboxCapacity = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.logging.include-progress"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("agent.logging.include-progress")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.logging.include-progress for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.LoggingIncludeProgress: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.LoggingIncludeProgress = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.logging.readiness-impact"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("agent.logging.readiness-impact")
		if valueErr != nil {
			return daemon.Properties{}, fmt.Errorf("decode configuration property agent.logging.readiness-impact for github.com/spice-framework/spice-agent-coding/internal/daemon.Properties.LoggingReadinessImpact: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.LoggingReadinessImpact = convertedValue
	}
	return value, nil
}
