//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/run_authority_bean.go:15

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemon2 "github.com/spice-framework/spice-agent/daemon"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructRunAuthority_af30e6a5 performs the direct construction selected for bean "runAuthority".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRunAuthority.
func ConstructRunAuthority_af30e6a5(dependency0 daemon.Properties) (*daemon2.RunAuthority, spicelifecycle.Cleanup, error) {
	value, cleanup, err := daemon.NewRunAuthority(dependency0)
	if err != nil {
		var zero *daemon2.RunAuthority
		return zero, nil, fmt.Errorf("construct bean runAuthority (*github.com/spice-framework/spice-agent/daemon.RunAuthority, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRunAuthority): %w", err)
	}
	return value, cleanup, nil
}
