//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/runtime.go:71

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	client "github.com/spice-framework/spice-agent/client"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	grpcserver "github.com/spice-framework/spice-agent/daemon/grpcserver"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructDaemonRuntime_b0e1ae70 performs the direct construction selected for bean "daemonRuntime".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRuntime.
func ConstructDaemonRuntime_b0e1ae70(dependency0 endpoint.UserScope, dependency1 *endpoint.Store, dependency2 endpoint.Token, dependency3 client.Build, dependency4 client.ProtocolVersion, dependency5 *grpcserver.Server, dependency6 *daemon.RuntimePluginActivation) (*daemon.Runtime, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewRuntime(dependency0, dependency1, dependency2, dependency3, dependency4, dependency5, dependency6)
	if err != nil {
		var zero *daemon.Runtime
		return zero, nil, fmt.Errorf("construct bean daemonRuntime (*github.com/spice-framework/spice-agent-coding/internal/daemon.Runtime, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRuntime): %w", err)
	}
	return value, nil, nil
}
