//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/runtime_plugin_properties.go:12

package spicegen

import (
	fmt "fmt"
	time "time"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	spiceconfig "github.com/spice-framework/spice/config"
)

// BindRuntimePluginProperties_9c54299d binds the validated configuration declared by spice:symbol:v1|type|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|23:RuntimePluginProperties.
func BindRuntimePluginProperties_9c54299d(configurationSnapshot spiceconfig.Snapshot) (daemon.RuntimePluginProperties, error) {
	value := daemon.RuntimePluginProperties{}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.required"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("agent.runtime-plugin.required")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.required for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.Required: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.Required = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.id"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.runtime-plugin.id")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.id for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.ID: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.ID = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.path"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.runtime-plugin.path")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.path for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.Path: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.Path = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.sha256"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.runtime-plugin.sha256")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.sha256 for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.SHA256: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.SHA256 = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.manifest-name"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.runtime-plugin.manifest-name")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.manifest-name for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.ManifestName: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.ManifestName = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.manifest-version"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.runtime-plugin.manifest-version")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.manifest-version for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.ManifestVersion: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.ManifestVersion = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.working-directory"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.runtime-plugin.working-directory")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.working-directory for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.WorkingDirectory: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.WorkingDirectory = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.capabilities.filesystem-read"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("agent.runtime-plugin.capabilities.filesystem-read")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.capabilities.filesystem-read for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.FilesystemRead: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.FilesystemRead = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.capabilities.filesystem-write"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("agent.runtime-plugin.capabilities.filesystem-write")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.capabilities.filesystem-write for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.FilesystemWrite: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.FilesystemWrite = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.capabilities.process-execute"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("agent.runtime-plugin.capabilities.process-execute")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.capabilities.process-execute for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.ProcessExecute: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.ProcessExecute = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.capabilities.network-access"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("agent.runtime-plugin.capabilities.network-access")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.capabilities.network-access for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.NetworkAccess: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.NetworkAccess = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.capabilities.secrets-read"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("agent.runtime-plugin.capabilities.secrets-read")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.capabilities.secrets-read for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.SecretsRead: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.SecretsRead = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.capabilities.environment-read"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("agent.runtime-plugin.capabilities.environment-read")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.capabilities.environment-read for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.EnvironmentRead: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.EnvironmentRead = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.capabilities.environment-write"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("agent.runtime-plugin.capabilities.environment-write")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.capabilities.environment-write for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.EnvironmentWrite: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.EnvironmentWrite = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.timeouts.startup"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("agent.runtime-plugin.timeouts.startup")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.timeouts.startup for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.StartupTimeout: %w", valueErr)
		}
		convertedValue := time.Duration(rawValue)
		value.StartupTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.timeouts.call"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("agent.runtime-plugin.timeouts.call")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.timeouts.call for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.CallTimeout: %w", valueErr)
		}
		convertedValue := time.Duration(rawValue)
		value.CallTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.timeouts.drain"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("agent.runtime-plugin.timeouts.drain")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.timeouts.drain for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.DrainTimeout: %w", valueErr)
		}
		convertedValue := time.Duration(rawValue)
		value.DrainTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.timeouts.shutdown"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("agent.runtime-plugin.timeouts.shutdown")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.timeouts.shutdown for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.ShutdownTimeout: %w", valueErr)
		}
		convertedValue := time.Duration(rawValue)
		value.ShutdownTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.runtime-plugin.timeouts.containment"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("agent.runtime-plugin.timeouts.containment")
		if valueErr != nil {
			return daemon.RuntimePluginProperties{}, fmt.Errorf("decode configuration property agent.runtime-plugin.timeouts.containment for github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties.ContainmentTimeout: %w", valueErr)
		}
		convertedValue := time.Duration(rawValue)
		value.ContainmentTimeout = convertedValue
	}
	return value, nil
}
