//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/runtime_plugin_host_bean.go:21

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	pluginhost "github.com/spice-framework/spice-agent/plugin/host"
	pluginv1 "github.com/spice-framework/spice-agent/plugin/v1"
	process "github.com/spice-framework/spice-agent/process"
	stage "github.com/spice-framework/spice-agent/stage"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructRuntimePluginHost_5f5e1f27 performs the direct construction selected for bean "runtimePluginHost".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewRuntimePluginHost.
func ConstructRuntimePluginHost_5f5e1f27(dependency0 *pluginv1.BuildIdentity, dependency1 stage.ToolDispatcher, dependency2 []stage.ToolDispatchDecorator, dependency3 pluginhost.RestartPolicy, dependency4 process.Launcher, dependency5 pluginhost.LocalEndpointFactory, dependency6 daemon.RuntimePluginPlan) (*pluginhost.Host, spicelifecycle.Cleanup, error) {
	value, cleanup, err := daemon.NewRuntimePluginHost(dependency0, dependency1, dependency2, dependency3, dependency4, dependency5, dependency6)
	if err != nil {
		var zero *pluginhost.Host
		return zero, nil, fmt.Errorf("construct bean runtimePluginHost (*github.com/spice-framework/spice-agent/plugin/host.Host, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewRuntimePluginHost): %w", err)
	}
	return value, cleanup, nil
}
