//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/runtime_plugin_restart_policy_bean.go:15

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	pluginhost "github.com/spice-framework/spice-agent/plugin/host"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructRuntimePluginRestartPolicy_e8e4c4c9 performs the direct construction selected for bean "runtimePluginRestartPolicy".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|29:NewRuntimePluginRestartPolicy.
func ConstructRuntimePluginRestartPolicy_e8e4c4c9(dependency0 daemon.RuntimePluginPlan) (pluginhost.RestartPolicy, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewRuntimePluginRestartPolicy(dependency0)
	if err != nil {
		var zero pluginhost.RestartPolicy
		return zero, nil, fmt.Errorf("construct bean runtimePluginRestartPolicy (github.com/spice-framework/spice-agent/plugin/host.RestartPolicy, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|29:NewRuntimePluginRestartPolicy): %w", err)
	}
	return value, nil, nil
}
