//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/runtime_plugin_activation.go:47
// Source: internal/daemon/runtime_plugin_activation.go:148

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemon2 "github.com/spice-framework/spice-agent/daemon"
	pluginhost "github.com/spice-framework/spice-agent/plugin/host"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructRuntimePluginActivation_74e21535 performs the direct construction selected for bean "runtimePluginActivation".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewRuntimePluginActivation.
func ConstructRuntimePluginActivation_74e21535(dependency0 daemon.RuntimePluginPlan, dependency1 *pluginhost.Host) (*daemon.RuntimePluginActivation, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewRuntimePluginActivation(dependency0, dependency1)
	if err != nil {
		var zero *daemon.RuntimePluginActivation
		return zero, nil, fmt.Errorf("construct bean runtimePluginActivation (*github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginActivation, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewRuntimePluginActivation): %w", err)
	}
	return value, nil, nil
}

// ConstructRuntimePluginHealthSource_b1db0a10 performs the direct construction selected for bean "runtimePluginHealthSource".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHealthSource.
func ConstructRuntimePluginHealthSource_b1db0a10(dependency0 *daemon.RuntimePluginActivation, dependency1 *pluginhost.Host) (daemon2.HealthSource, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewRuntimePluginHealthSource(dependency0, dependency1)
	if err != nil {
		var zero daemon2.HealthSource
		return zero, nil, fmt.Errorf("construct bean runtimePluginHealthSource (github.com/spice-framework/spice-agent/daemon.HealthSource, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHealthSource): %w", err)
	}
	return value, nil, nil
}
