//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/runtime_plugin_activation_bean.go:13

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	pluginhost "github.com/spice-framework/spice-agent/plugin/host"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructRuntimePluginActivation_74e21535 performs the direct construction selected for bean "runtimePluginActivation".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewRuntimePluginActivation.
func ConstructRuntimePluginActivation_74e21535(dependency0 daemon.RuntimePluginPlan, dependency1 *pluginhost.Host) (*daemon.RuntimePluginActivation, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewRuntimePluginActivation(dependency0, dependency1)
	if err != nil {
		var zero *daemon.RuntimePluginActivation
		return zero, nil, fmt.Errorf("construct bean runtimePluginActivation (*github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginActivation, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewRuntimePluginActivation): %w", err)
	}
	return value, nil, nil
}
