//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/runtime_plugin_host_identity_bean.go:16

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	client "github.com/spice-framework/spice-agent/client"
	pluginv1 "github.com/spice-framework/spice-agent/plugin/v1"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructRuntimePluginHostIdentity_5b56db5e performs the direct construction selected for bean "runtimePluginHostIdentity".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHostIdentity.
func ConstructRuntimePluginHostIdentity_5b56db5e(dependency0 client.Build) (*pluginv1.BuildIdentity, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewRuntimePluginHostIdentity(dependency0)
	if err != nil {
		var zero *pluginv1.BuildIdentity
		return zero, nil, fmt.Errorf("construct bean runtimePluginHostIdentity (*github.com/spice-framework/spice-agent/plugin/v1.BuildIdentity, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHostIdentity): %w", err)
	}
	return value, nil, nil
}
