//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/server_limits_bean.go:11

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	client "github.com/spice-framework/spice-agent/client"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructServerLimits_3afc4093 performs the direct construction selected for bean "serverLimits".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLimits.
func ConstructServerLimits_3afc4093() (client.Limits, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewLimits()
	if err != nil {
		var zero client.Limits
		return zero, nil, fmt.Errorf("construct bean serverLimits (github.com/spice-framework/spice-agent/client.Limits, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLimits): %w", err)
	}
	return value, nil, nil
}
