//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/server_build_bean.go:14

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	client "github.com/spice-framework/spice-agent/client"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructServerBuild_a30ee9e7 performs the direct construction selected for bean "serverBuild".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|14:NewServerBuild.
func ConstructServerBuild_a30ee9e7() (client.Build, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewServerBuild()
	if err != nil {
		var zero client.Build
		return zero, nil, fmt.Errorf("construct bean serverBuild (github.com/spice-framework/spice-agent/client.Build, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|14:NewServerBuild): %w", err)
	}
	return value, nil, nil
}
