//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/session_store_bean.go:12

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemon2 "github.com/spice-framework/spice-agent/daemon"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructSessionStore_5ce90ba9 performs the direct construction selected for bean "sessionStore".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewSessionStore.
func ConstructSessionStore_5ce90ba9(dependency0 *daemon.Root) (*daemon2.SessionStore, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewSessionStore(dependency0)
	if err != nil {
		var zero *daemon2.SessionStore
		return zero, nil, fmt.Errorf("construct bean sessionStore (*github.com/spice-framework/spice-agent/daemon.SessionStore, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewSessionStore): %w", err)
	}
	return value, nil, nil
}
