//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/verified_process_launcher_bean.go:14

package spicegen

import (
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	process "github.com/spice-framework/spice-agent/process"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructVerifiedProcessLauncher_0dcbcbce performs the direct construction selected for bean "verifiedProcessLauncher".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewVerifiedProcessLauncher.
func ConstructVerifiedProcessLauncher_0dcbcbce(dependency0 process.Launcher) (process.VerifiedLauncher, spicelifecycle.Cleanup, error) {
	value, err := daemon.NewVerifiedProcessLauncher(dependency0)
	if err != nil {
		var zero process.VerifiedLauncher
		return zero, nil, fmt.Errorf("construct bean verifiedProcessLauncher (github.com/spice-framework/spice-agent/process.VerifiedLauncher, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewVerifiedProcessLauncher): %w", err)
	}
	return value, nil, nil
}
