//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	spiceDaemon "github.com/spice-framework/spice-agent-coding/internal/spicegen/spice_agentd/sources/internal_/daemon"
	spiceWorkspace "github.com/spice-framework/spice-agent-coding/internal/spicegen/spice_agentd/sources/internal_/workspace"
	spiceAutoconfigure "github.com/spice-framework/spice-agent-coding/internal/spicegen/spice_agentd/sources/vendor_/github.com/spice-framework/spice-agent-provider-openai/autoconfigure"
	spiceAutoconfigure2 "github.com/spice-framework/spice-agent-coding/internal/spicegen/spice_agentd/sources/vendor_/github.com/spice-framework/spice-agent-tools-coding/autoconfigure"
	spiceAutoconfigure3 "github.com/spice-framework/spice-agent-coding/internal/spicegen/spice_agentd/sources/vendor_/github.com/spice-framework/spice-agent/logging/autoconfigure"
	spiceAutoconfigure4 "github.com/spice-framework/spice-agent-coding/internal/spicegen/spice_agentd/sources/vendor_/github.com/spice-framework/spice-agent/plugin/host/autoconfigure"
	workspace "github.com/spice-framework/spice-agent-coding/internal/workspace"
	openaiprovider "github.com/spice-framework/spice-agent-provider-openai"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	agent "github.com/spice-framework/spice-agent/agent"
	client "github.com/spice-framework/spice-agent/client"
	daemon2 "github.com/spice-framework/spice-agent/daemon"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	grpcserver "github.com/spice-framework/spice-agent/daemon/grpcserver"
	event "github.com/spice-framework/spice-agent/event"
	interaction "github.com/spice-framework/spice-agent/interaction"
	logging "github.com/spice-framework/spice-agent/logging"
	model "github.com/spice-framework/spice-agent/model"
	pluginhost "github.com/spice-framework/spice-agent/plugin/host"
	pluginv1 "github.com/spice-framework/spice-agent/plugin/v1"
	process "github.com/spice-framework/spice-agent/process"
	stage "github.com/spice-framework/spice-agent/stage"
	tool "github.com/spice-framework/spice-agent/tool"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
	spicelogging "github.com/spice-framework/spice/logging"
)

type applicationDependencies struct {
	spiceLogger                     *spicelogging.Logger
	daemonIDSource                  agent.IDSource
	pendingHub                      *daemon2.PendingHub
	serverBuild                     client.Build
	daemonRootRegistry              daemonprocess.RootRegistry
	endpointScope                   endpoint.UserScope
	endpointStore                   *endpoint.Store
	endpointToken                   endpoint.Token
	daemonListenerFactory           daemon.ListenerFactory
	processLauncher                 process.Launcher
	serverProtocol                  client.ProtocolVersion
	daemonInteractionBroker         interaction.Broker
	processResolver                 process.ExecutableResolver
	verifiedProcessLauncher         process.VerifiedLauncher
	runtimePluginHostIdentity       *pluginv1.BuildIdentity
	daemonRoot                      *daemon.Root
	sessionStore                    *daemon2.SessionStore
	operationLedger                 *daemon2.Ledger
	serverLimits                    client.Limits
	runtimePluginEndpointFactory    pluginhost.LocalEndpointFactory
	daemonProperties                daemon.Properties
	openAIConfig                    openaiprovider.Config
	runAuthority                    *daemon2.RunAuthority
	definitionSet                   daemon2.DefinitionSet
	agentLoggingConfig              logging.Config
	agentLoggingMailbox             *event.BestEffortObserver
	agentLoggingProcessor           *logging.Processor
	agentLoggingHealth              daemon2.HealthSource
	openAIModelProvider             model.Provider
	runtimePluginProperties         daemon.RuntimePluginProperties
	runtimePluginPlan               daemon.RuntimePluginPlan
	runtimePluginRestartPolicy      pluginhost.RestartPolicy
	workspaceProperties             workspace.Properties
	codingConfig                    coding.Config
	read                            tool.Tool
	shell                           tool.Tool
	replace                         tool.Tool
	runtimePluginCompiledDispatcher stage.ToolDispatcher
	runtimePluginHost               *pluginhost.Host
	runtimePluginActivation         *daemon.RuntimePluginActivation
	runtimePluginHealthSource       daemon2.HealthSource
	runtimePluginToolPlanSource     stage.ToolPlanSource
	daemonEngine                    *agent.Engine
	runHost                         *daemon2.RunHost
	grpcServer                      *grpcserver.Server
	daemonRuntime                   *daemon.Runtime
}

func constructApplicationDependencies(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
) (*applicationDependencies, error) {
	_ = ctx
	_ = application
	_ = options
	_ = configurationSnapshot
	spiceLogger := application.logger
	_ = spiceLogger
	daemonIDSource, daemonIDSourceCleanup, err := func() (agent.IDSource, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonIDSource.Enabled() {
			return options.Overrides.DaemonIDSource.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonIDSource_f337ceca()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonIDSource (github.com/spice-framework/spice-agent/agent.IDSource, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|11:NewIDSource): %w", err))
	}
	if daemonIDSourceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|11:NewIDSource", daemonIDSourceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonIDSource (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|11:NewIDSource): %w", err))
		}
	}
	_ = daemonIDSource
	pendingHub, pendingHubCleanup, err := func() (*daemon2.PendingHub, spicelifecycle.Cleanup, error) {
		if options.Overrides.PendingHub.Enabled() {
			return options.Overrides.PendingHub.Acquire(ctx)
		}
		return spiceDaemon.ConstructPendingHub_4cbcfd89()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean pendingHub (*github.com/spice-framework/spice-agent/daemon.PendingHub, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub): %w", err))
	}
	if pendingHubCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub", pendingHubCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean pendingHub (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub): %w", err))
		}
	}
	_ = pendingHub
	serverBuild, serverBuildCleanup, err := func() (client.Build, spicelifecycle.Cleanup, error) {
		if options.Overrides.ServerBuild.Enabled() {
			return options.Overrides.ServerBuild.Acquire(ctx)
		}
		return spiceDaemon.ConstructServerBuild_a30ee9e7()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean serverBuild (github.com/spice-framework/spice-agent/client.Build, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|14:NewServerBuild): %w", err))
	}
	if serverBuildCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|14:NewServerBuild", serverBuildCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean serverBuild (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|14:NewServerBuild): %w", err))
		}
	}
	_ = serverBuild
	daemonRootRegistry, daemonRootRegistryCleanup, err := func() (daemonprocess.RootRegistry, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonRootRegistry.Enabled() {
			return options.Overrides.DaemonRootRegistry.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonRootRegistry_5e3757f8()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonRootRegistry (github.com/spice-framework/spice-agent-coding/internal/daemonprocess.RootRegistry, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRootRegistry): %w", err))
	}
	if daemonRootRegistryCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRootRegistry", daemonRootRegistryCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonRootRegistry (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRootRegistry): %w", err))
		}
	}
	_ = daemonRootRegistry
	endpointScope, endpointScopeCleanup, err := func() (endpoint.UserScope, spicelifecycle.Cleanup, error) {
		if options.Overrides.EndpointScope.Enabled() {
			return options.Overrides.EndpointScope.Acquire(ctx)
		}
		return spiceDaemon.ConstructEndpointScope_4a25ec50()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean endpointScope (github.com/spice-framework/spice-agent/daemon/endpoint.UserScope, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointScope): %w", err))
	}
	if endpointScopeCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointScope", endpointScopeCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean endpointScope (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointScope): %w", err))
		}
	}
	_ = endpointScope
	endpointStore, endpointStoreCleanup, err := func() (*endpoint.Store, spicelifecycle.Cleanup, error) {
		if options.Overrides.EndpointStore.Enabled() {
			return options.Overrides.EndpointStore.Acquire(ctx)
		}
		return spiceDaemon.ConstructEndpointStore_c41f25a3(endpointScope)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean endpointStore (*github.com/spice-framework/spice-agent/daemon/endpoint.Store, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointStore): %w", err))
	}
	if endpointStoreCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointStore", endpointStoreCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean endpointStore (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointStore): %w", err))
		}
	}
	_ = endpointStore
	endpointToken, endpointTokenCleanup, err := func() (endpoint.Token, spicelifecycle.Cleanup, error) {
		if options.Overrides.EndpointToken.Enabled() {
			return options.Overrides.EndpointToken.Acquire(ctx)
		}
		return spiceDaemon.ConstructEndpointToken_94cf31d6()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean endpointToken (github.com/spice-framework/spice-agent/daemon/endpoint.Token, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointToken): %w", err))
	}
	if endpointTokenCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointToken", endpointTokenCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean endpointToken (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointToken): %w", err))
		}
	}
	_ = endpointToken
	daemonListenerFactory, daemonListenerFactoryCleanup, err := func() (daemon.ListenerFactory, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonListenerFactory.Enabled() {
			return options.Overrides.DaemonListenerFactory.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonListenerFactory_66b0ce4f()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonListenerFactory (github.com/spice-framework/spice-agent-coding/internal/daemon.ListenerFactory, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewListenerFactory): %w", err))
	}
	if daemonListenerFactoryCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewListenerFactory", daemonListenerFactoryCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonListenerFactory (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewListenerFactory): %w", err))
		}
	}
	_ = daemonListenerFactory
	processLauncher, processLauncherCleanup, err := func() (process.Launcher, spicelifecycle.Cleanup, error) {
		if options.Overrides.ProcessLauncher.Enabled() {
			return options.Overrides.ProcessLauncher.Acquire(ctx)
		}
		return spiceDaemon.ConstructProcessLauncher_6dd45eb0(daemonRootRegistry)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean processLauncher (github.com/spice-framework/spice-agent/process.Launcher, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProcessLauncher): %w", err))
	}
	if processLauncherCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProcessLauncher", processLauncherCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean processLauncher (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProcessLauncher): %w", err))
		}
	}
	_ = processLauncher
	serverProtocol, serverProtocolCleanup, err := func() (client.ProtocolVersion, spicelifecycle.Cleanup, error) {
		if options.Overrides.ServerProtocol.Enabled() {
			return options.Overrides.ServerProtocol.Acquire(ctx)
		}
		return spiceDaemon.ConstructServerProtocol_5afceae2()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean serverProtocol (github.com/spice-framework/spice-agent/client.ProtocolVersion, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProtocolVersion): %w", err))
	}
	if serverProtocolCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProtocolVersion", serverProtocolCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean serverProtocol (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProtocolVersion): %w", err))
		}
	}
	_ = serverProtocol
	daemonInteractionBroker, daemonInteractionBrokerCleanup, err := func() (interaction.Broker, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonInteractionBroker.Enabled() {
			return options.Overrides.DaemonInteractionBroker.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonInteractionBroker_bf812f17(pendingHub)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonInteractionBroker (github.com/spice-framework/spice-agent/interaction.Broker, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewInteractionBroker): %w", err))
	}
	if daemonInteractionBrokerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewInteractionBroker", daemonInteractionBrokerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonInteractionBroker (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewInteractionBroker): %w", err))
		}
	}
	_ = daemonInteractionBroker
	processResolver, processResolverCleanup, err := func() (process.ExecutableResolver, spicelifecycle.Cleanup, error) {
		if options.Overrides.ProcessResolver.Enabled() {
			return options.Overrides.ProcessResolver.Acquire(ctx)
		}
		return spiceDaemon.ConstructProcessResolver_4d5da368()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean processResolver (github.com/spice-framework/spice-agent/process.ExecutableResolver, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewExecutableResolver): %w", err))
	}
	if processResolverCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewExecutableResolver", processResolverCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean processResolver (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewExecutableResolver): %w", err))
		}
	}
	_ = processResolver
	verifiedProcessLauncher, verifiedProcessLauncherCleanup, err := func() (process.VerifiedLauncher, spicelifecycle.Cleanup, error) {
		if options.Overrides.VerifiedProcessLauncher.Enabled() {
			return options.Overrides.VerifiedProcessLauncher.Acquire(ctx)
		}
		return spiceDaemon.ConstructVerifiedProcessLauncher_0dcbcbce(processLauncher)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean verifiedProcessLauncher (github.com/spice-framework/spice-agent/process.VerifiedLauncher, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewVerifiedProcessLauncher): %w", err))
	}
	if verifiedProcessLauncherCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewVerifiedProcessLauncher", verifiedProcessLauncherCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean verifiedProcessLauncher (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewVerifiedProcessLauncher): %w", err))
		}
	}
	_ = verifiedProcessLauncher
	runtimePluginHostIdentity, runtimePluginHostIdentityCleanup, err := func() (*pluginv1.BuildIdentity, spicelifecycle.Cleanup, error) {
		if options.Overrides.RuntimePluginHostIdentity.Enabled() {
			return options.Overrides.RuntimePluginHostIdentity.Acquire(ctx)
		}
		return spiceDaemon.ConstructRuntimePluginHostIdentity_5b56db5e(serverBuild)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runtimePluginHostIdentity (*github.com/spice-framework/spice-agent/plugin/v1.BuildIdentity, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHostIdentity): %w", err))
	}
	if runtimePluginHostIdentityCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHostIdentity", runtimePluginHostIdentityCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runtimePluginHostIdentity (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHostIdentity): %w", err))
		}
	}
	_ = runtimePluginHostIdentity
	daemonRoot, daemonRootCleanup, err := func() (*daemon.Root, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonRoot.Enabled() {
			return options.Overrides.DaemonRoot.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonRoot_3c8cd2a3(daemonRootRegistry)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonRoot (*github.com/spice-framework/spice-agent-coding/internal/daemon.Root, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|7:NewRoot): %w", err))
	}
	if daemonRootCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|7:NewRoot", daemonRootCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonRoot (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|7:NewRoot): %w", err))
		}
	}
	_ = daemonRoot
	sessionStore, sessionStoreCleanup, err := func() (*daemon2.SessionStore, spicelifecycle.Cleanup, error) {
		if options.Overrides.SessionStore.Enabled() {
			return options.Overrides.SessionStore.Acquire(ctx)
		}
		return spiceDaemon.ConstructSessionStore_5ce90ba9(daemonRoot)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean sessionStore (*github.com/spice-framework/spice-agent/daemon.SessionStore, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewSessionStore): %w", err))
	}
	if sessionStoreCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewSessionStore", sessionStoreCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean sessionStore (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewSessionStore): %w", err))
		}
	}
	_ = sessionStore
	operationLedger, operationLedgerCleanup, err := func() (*daemon2.Ledger, spicelifecycle.Cleanup, error) {
		if options.Overrides.OperationLedger.Enabled() {
			return options.Overrides.OperationLedger.Acquire(ctx)
		}
		return spiceDaemon.ConstructOperationLedger_4e34d52a()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean operationLedger (*github.com/spice-framework/spice-agent/daemon.Ledger, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLedger): %w", err))
	}
	if operationLedgerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLedger", operationLedgerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean operationLedger (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLedger): %w", err))
		}
	}
	_ = operationLedger
	serverLimits, serverLimitsCleanup, err := func() (client.Limits, spicelifecycle.Cleanup, error) {
		if options.Overrides.ServerLimits.Enabled() {
			return options.Overrides.ServerLimits.Acquire(ctx)
		}
		return spiceDaemon.ConstructServerLimits_3afc4093()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean serverLimits (github.com/spice-framework/spice-agent/client.Limits, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLimits): %w", err))
	}
	if serverLimitsCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLimits", serverLimitsCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean serverLimits (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLimits): %w", err))
		}
	}
	_ = serverLimits
	runtimePluginEndpointFactory, runtimePluginEndpointFactoryCleanup, err := func() (pluginhost.LocalEndpointFactory, spicelifecycle.Cleanup, error) {
		if options.Overrides.RuntimePluginEndpointFactory.Enabled() {
			return options.Overrides.RuntimePluginEndpointFactory.Acquire(ctx)
		}
		return spiceAutoconfigure4.ConstructRuntimePluginEndpointFactory_d1bddc00()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runtimePluginEndpointFactory (github.com/spice-framework/spice-agent/plugin/host.LocalEndpointFactory, source spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|33:DefaultCurrentUserEndpointFactory): %w", err))
	}
	if runtimePluginEndpointFactoryCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent/plugin/host/autoconfigure", "spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|33:DefaultCurrentUserEndpointFactory", runtimePluginEndpointFactoryCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runtimePluginEndpointFactory (source spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|33:DefaultCurrentUserEndpointFactory): %w", err))
		}
	}
	_ = runtimePluginEndpointFactory
	daemonProperties, err := spiceDaemon.BindProperties_641bb6f4(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/spice-framework/spice-agent-coding/internal/daemon.Properties for bean Properties (source spice:symbol:v1|type|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:Properties): %w", err))
	}
	_ = daemonProperties
	openAIConfig, openAIConfigCleanup, err := func() (openaiprovider.Config, spicelifecycle.Cleanup, error) {
		if options.Overrides.OpenAIConfig.Enabled() {
			return options.Overrides.OpenAIConfig.Acquire(ctx)
		}
		return spiceDaemon.ConstructOpenAIConfig_f13e2cf9(daemonProperties)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean openAIConfig (github.com/spice-framework/spice-agent-provider-openai.Config, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewOpenAIConfig): %w", err))
	}
	if openAIConfigCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewOpenAIConfig", openAIConfigCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean openAIConfig (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewOpenAIConfig): %w", err))
		}
	}
	_ = openAIConfig
	runAuthority, runAuthorityCleanup, err := func() (*daemon2.RunAuthority, spicelifecycle.Cleanup, error) {
		if options.Overrides.RunAuthority.Enabled() {
			return options.Overrides.RunAuthority.Acquire(ctx)
		}
		return spiceDaemon.ConstructRunAuthority_af30e6a5(daemonProperties)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runAuthority (*github.com/spice-framework/spice-agent/daemon.RunAuthority, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRunAuthority): %w", err))
	}
	if runAuthorityCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRunAuthority", runAuthorityCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runAuthority (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRunAuthority): %w", err))
		}
	}
	_ = runAuthority
	definitionSet, definitionSetCleanup, err := func() (daemon2.DefinitionSet, spicelifecycle.Cleanup, error) {
		if options.Overrides.DefinitionSet.Enabled() {
			return options.Overrides.DefinitionSet.Acquire(ctx)
		}
		return spiceDaemon.ConstructDefinitionSet_a8acae3e(daemonProperties)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean definitionSet (github.com/spice-framework/spice-agent/daemon.DefinitionSet, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewDefinitionSet): %w", err))
	}
	if definitionSetCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewDefinitionSet", definitionSetCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean definitionSet (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewDefinitionSet): %w", err))
		}
	}
	_ = definitionSet
	agentLoggingConfig, agentLoggingConfigCleanup, err := func() (logging.Config, spicelifecycle.Cleanup, error) {
		if options.Overrides.AgentLoggingConfig.Enabled() {
			return options.Overrides.AgentLoggingConfig.Acquire(ctx)
		}
		return spiceDaemon.ConstructAgentLoggingConfig_b3cd42db(daemonProperties)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean agentLoggingConfig (github.com/spice-framework/spice-agent/logging.Config, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewAgentLoggingConfig): %w", err))
	}
	if agentLoggingConfigCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewAgentLoggingConfig", agentLoggingConfigCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean agentLoggingConfig (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewAgentLoggingConfig): %w", err))
		}
	}
	_ = agentLoggingConfig
	agentLoggingMailbox, agentLoggingMailboxCleanup, err := func() (*event.BestEffortObserver, spicelifecycle.Cleanup, error) {
		if options.Overrides.AgentLoggingMailbox.Enabled() {
			return options.Overrides.AgentLoggingMailbox.Acquire(ctx)
		}
		return spiceAutoconfigure3.ConstructAgentLoggingMailbox_42d3a702(agentLoggingConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean agentLoggingMailbox (*github.com/spice-framework/spice-agent/event.BestEffortObserver, source spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|14:DefaultMailbox): %w", err))
	}
	if agentLoggingMailboxCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent/logging/autoconfigure", "spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|14:DefaultMailbox", agentLoggingMailboxCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean agentLoggingMailbox (source spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|14:DefaultMailbox): %w", err))
		}
	}
	_ = agentLoggingMailbox
	agentLoggingProcessor, agentLoggingProcessorCleanup, err := func() (*logging.Processor, spicelifecycle.Cleanup, error) {
		if options.Overrides.AgentLoggingProcessor.Enabled() {
			return options.Overrides.AgentLoggingProcessor.Acquire(ctx)
		}
		return spiceAutoconfigure3.ConstructAgentLoggingProcessor_a4291fa3(agentLoggingConfig, agentLoggingMailbox, spiceLogger)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean agentLoggingProcessor (*github.com/spice-framework/spice-agent/logging.Processor, source spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|16:DefaultProcessor): %w", err))
	}
	if agentLoggingProcessorCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent/logging/autoconfigure", "spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|16:DefaultProcessor", agentLoggingProcessorCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean agentLoggingProcessor (source spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|16:DefaultProcessor): %w", err))
		}
	}
	_ = agentLoggingProcessor
	agentLoggingHealth, agentLoggingHealthCleanup, err := func() (daemon2.HealthSource, spicelifecycle.Cleanup, error) {
		if options.Overrides.AgentLoggingHealth.Enabled() {
			return options.Overrides.AgentLoggingHealth.Acquire(ctx)
		}
		return spiceDaemon.ConstructAgentLoggingHealth_1ccf2800(agentLoggingConfig, agentLoggingProcessor)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean agentLoggingHealth (github.com/spice-framework/spice-agent/daemon.HealthSource, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|27:NewAgentLoggingHealthSource): %w", err))
	}
	if agentLoggingHealthCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|27:NewAgentLoggingHealthSource", agentLoggingHealthCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean agentLoggingHealth (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|27:NewAgentLoggingHealthSource): %w", err))
		}
	}
	_ = agentLoggingHealth
	openAIModelProvider, openAIModelProviderCleanup, err := func() (model.Provider, spicelifecycle.Cleanup, error) {
		if options.Overrides.OpenAIModelProvider.Enabled() {
			return options.Overrides.OpenAIModelProvider.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructOpenAIModelProvider_2228c855(openAIConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean openAIModelProvider (github.com/spice-framework/spice-agent/model.Provider, source spice:symbol:v1|function|68:github.com/spice-framework/spice-agent-provider-openai/autoconfigure|0:|7:Default): %w", err))
	}
	if openAIModelProviderCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-provider-openai/autoconfigure", "spice:symbol:v1|function|68:github.com/spice-framework/spice-agent-provider-openai/autoconfigure|0:|7:Default", openAIModelProviderCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean openAIModelProvider (source spice:symbol:v1|function|68:github.com/spice-framework/spice-agent-provider-openai/autoconfigure|0:|7:Default): %w", err))
		}
	}
	_ = openAIModelProvider
	runtimePluginProperties, err := spiceDaemon.BindRuntimePluginProperties_9c54299d(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginProperties for bean RuntimePluginProperties (source spice:symbol:v1|type|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|23:RuntimePluginProperties): %w", err))
	}
	_ = runtimePluginProperties
	runtimePluginPlan, runtimePluginPlanCleanup, err := func() (daemon.RuntimePluginPlan, spicelifecycle.Cleanup, error) {
		if options.Overrides.RuntimePluginPlan.Enabled() {
			return options.Overrides.RuntimePluginPlan.Acquire(ctx)
		}
		return spiceDaemon.ConstructRuntimePluginPlan_3ea2d428(runtimePluginProperties)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runtimePluginPlan (github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginPlan, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewRuntimePluginPlan): %w", err))
	}
	if runtimePluginPlanCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewRuntimePluginPlan", runtimePluginPlanCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runtimePluginPlan (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewRuntimePluginPlan): %w", err))
		}
	}
	_ = runtimePluginPlan
	runtimePluginRestartPolicy, runtimePluginRestartPolicyCleanup, err := func() (pluginhost.RestartPolicy, spicelifecycle.Cleanup, error) {
		if options.Overrides.RuntimePluginRestartPolicy.Enabled() {
			return options.Overrides.RuntimePluginRestartPolicy.Acquire(ctx)
		}
		return spiceDaemon.ConstructRuntimePluginRestartPolicy_e8e4c4c9(runtimePluginPlan)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runtimePluginRestartPolicy (github.com/spice-framework/spice-agent/plugin/host.RestartPolicy, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|29:NewRuntimePluginRestartPolicy): %w", err))
	}
	if runtimePluginRestartPolicyCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|29:NewRuntimePluginRestartPolicy", runtimePluginRestartPolicyCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runtimePluginRestartPolicy (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|29:NewRuntimePluginRestartPolicy): %w", err))
		}
	}
	_ = runtimePluginRestartPolicy
	workspaceProperties, err := spiceWorkspace.BindProperties_1313dff6(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/spice-framework/spice-agent-coding/internal/workspace.Properties for bean Properties (source spice:symbol:v1|type|64:github.com/spice-framework/spice-agent-coding/internal/workspace|0:|10:Properties): %w", err))
	}
	_ = workspaceProperties
	codingConfig, codingConfigCleanup, err := func() (coding.Config, spicelifecycle.Cleanup, error) {
		if options.Overrides.CodingConfig.Enabled() {
			return options.Overrides.CodingConfig.Acquire(ctx)
		}
		return spiceDaemon.ConstructCodingConfig_4bbfc767(workspaceProperties, daemonRootRegistry)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean codingConfig (github.com/spice-framework/spice-agent-tools-coding.Config, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewCodingConfig): %w", err))
	}
	if codingConfigCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewCodingConfig", codingConfigCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean codingConfig (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewCodingConfig): %w", err))
		}
	}
	_ = codingConfig
	read, readCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Read.Enabled() {
			return options.Overrides.Read.Acquire(ctx)
		}
		return spiceAutoconfigure2.ConstructRead_1b770715(codingConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean read (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead): %w", err))
	}
	if readCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-tools-coding/autoconfigure", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead", readCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean read (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead): %w", err))
		}
	}
	_ = read
	shell, shellCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Shell.Enabled() {
			return options.Overrides.Shell.Acquire(ctx)
		}
		return spiceAutoconfigure2.ConstructShell_a48b269f(codingConfig, processResolver, processLauncher)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean shell (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell): %w", err))
	}
	if shellCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-tools-coding/autoconfigure", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell", shellCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean shell (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell): %w", err))
		}
	}
	_ = shell
	replace, replaceCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Replace.Enabled() {
			return options.Overrides.Replace.Acquire(ctx)
		}
		return spiceAutoconfigure2.ConstructReplace_96382d5b(codingConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean replace (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace): %w", err))
	}
	if replaceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-tools-coding/autoconfigure", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace", replaceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean replace (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace): %w", err))
		}
	}
	_ = replace
	runtimePluginCompiledDispatcher, runtimePluginCompiledDispatcherCleanup, err := func() (stage.ToolDispatcher, spicelifecycle.Cleanup, error) {
		if options.Overrides.RuntimePluginCompiledDispatcher.Enabled() {
			return options.Overrides.RuntimePluginCompiledDispatcher.Acquire(ctx)
		}
		return spiceAutoconfigure4.ConstructRuntimePluginCompiledDispatcher_288d6ba6(map[string]tool.Tool{"read": read, "replace": replace, "shell": shell})
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runtimePluginCompiledDispatcher (github.com/spice-framework/spice-agent/stage.ToolDispatcher, source spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|25:DefaultCompiledDispatcher): %w", err))
	}
	if runtimePluginCompiledDispatcherCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent/plugin/host/autoconfigure", "spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|25:DefaultCompiledDispatcher", runtimePluginCompiledDispatcherCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runtimePluginCompiledDispatcher (source spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|25:DefaultCompiledDispatcher): %w", err))
		}
	}
	_ = runtimePluginCompiledDispatcher
	runtimePluginHost, runtimePluginHostCleanup, err := func() (*pluginhost.Host, spicelifecycle.Cleanup, error) {
		if options.Overrides.RuntimePluginHost.Enabled() {
			return options.Overrides.RuntimePluginHost.Acquire(ctx)
		}
		return spiceDaemon.ConstructRuntimePluginHost_5f5e1f27(runtimePluginHostIdentity, runtimePluginCompiledDispatcher, []stage.ToolDispatchDecorator{}, runtimePluginRestartPolicy, verifiedProcessLauncher, runtimePluginEndpointFactory, runtimePluginPlan)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runtimePluginHost (*github.com/spice-framework/spice-agent/plugin/host.Host, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewRuntimePluginHost): %w", err))
	}
	if runtimePluginHostCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewRuntimePluginHost", runtimePluginHostCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runtimePluginHost (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewRuntimePluginHost): %w", err))
		}
	}
	_ = runtimePluginHost
	runtimePluginActivation, runtimePluginActivationCleanup, err := func() (*daemon.RuntimePluginActivation, spicelifecycle.Cleanup, error) {
		if options.Overrides.RuntimePluginActivation.Enabled() {
			return options.Overrides.RuntimePluginActivation.Acquire(ctx)
		}
		return spiceDaemon.ConstructRuntimePluginActivation_74e21535(runtimePluginPlan, runtimePluginHost)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runtimePluginActivation (*github.com/spice-framework/spice-agent-coding/internal/daemon.RuntimePluginActivation, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewRuntimePluginActivation): %w", err))
	}
	if runtimePluginActivationCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewRuntimePluginActivation", runtimePluginActivationCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runtimePluginActivation (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewRuntimePluginActivation): %w", err))
		}
	}
	_ = runtimePluginActivation
	runtimePluginHealthSource, runtimePluginHealthSourceCleanup, err := func() (daemon2.HealthSource, spicelifecycle.Cleanup, error) {
		if options.Overrides.RuntimePluginHealthSource.Enabled() {
			return options.Overrides.RuntimePluginHealthSource.Acquire(ctx)
		}
		return spiceDaemon.ConstructRuntimePluginHealthSource_b1db0a10(runtimePluginActivation, runtimePluginHost)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runtimePluginHealthSource (github.com/spice-framework/spice-agent/daemon.HealthSource, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHealthSource): %w", err))
	}
	if runtimePluginHealthSourceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHealthSource", runtimePluginHealthSourceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runtimePluginHealthSource (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHealthSource): %w", err))
		}
	}
	_ = runtimePluginHealthSource
	runtimePluginToolPlanSource, runtimePluginToolPlanSourceCleanup, err := func() (stage.ToolPlanSource, spicelifecycle.Cleanup, error) {
		if options.Overrides.RuntimePluginToolPlanSource.Enabled() {
			return options.Overrides.RuntimePluginToolPlanSource.Acquire(ctx)
		}
		return spiceAutoconfigure4.ConstructRuntimePluginToolPlanSource_db29b3aa(runtimePluginHost)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runtimePluginToolPlanSource (github.com/spice-framework/spice-agent/stage.ToolPlanSource, source spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|21:DefaultToolPlanSource): %w", err))
	}
	if runtimePluginToolPlanSourceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent/plugin/host/autoconfigure", "spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|21:DefaultToolPlanSource", runtimePluginToolPlanSourceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runtimePluginToolPlanSource (source spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|21:DefaultToolPlanSource): %w", err))
		}
	}
	_ = runtimePluginToolPlanSource
	daemonEngine, daemonEngineCleanup, err := func() (*agent.Engine, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonEngine.Enabled() {
			return options.Overrides.DaemonEngine.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonEngine_10b0c974(openAIModelProvider, runtimePluginToolPlanSource, daemonInteractionBroker, daemonIDSource, serverLimits, codingConfig, agentLoggingProcessor, []*event.BestEffortObserver{agentLoggingMailbox})
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonEngine (*github.com/spice-framework/spice-agent/agent.Engine, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine): %w", err))
	}
	if daemonEngineCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine", daemonEngineCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonEngine (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine): %w", err))
		}
	}
	_ = daemonEngine
	runHost, runHostCleanup, err := func() (*daemon2.RunHost, spicelifecycle.Cleanup, error) {
		if options.Overrides.RunHost.Enabled() {
			return options.Overrides.RunHost.Acquire(ctx)
		}
		return spiceDaemon.ConstructRunHost_4a91e2b0(daemonRoot, daemonEngine, runAuthority, sessionStore, operationLedger, pendingHub, definitionSet, []daemon2.HealthSource{agentLoggingHealth, runtimePluginHealthSource}, serverLimits)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runHost (*github.com/spice-framework/spice-agent/daemon.RunHost, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRunHost): %w", err))
	}
	if runHostCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRunHost", runHostCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runHost (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRunHost): %w", err))
		}
	}
	_ = runHost
	grpcServer, grpcServerCleanup, err := func() (*grpcserver.Server, spicelifecycle.Cleanup, error) {
		if options.Overrides.GrpcServer.Enabled() {
			return options.Overrides.GrpcServer.Acquire(ctx)
		}
		return spiceDaemon.ConstructGrpcServer_97f7cc1f(daemonRoot, endpointToken, runHost, sessionStore, serverBuild)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean grpcServer (*github.com/spice-framework/spice-agent/daemon/grpcserver.Server, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewGRPCServer): %w", err))
	}
	if grpcServerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewGRPCServer", grpcServerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean grpcServer (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewGRPCServer): %w", err))
		}
	}
	_ = grpcServer
	daemonRuntime, daemonRuntimeCleanup, err := func() (*daemon.Runtime, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonRuntime.Enabled() {
			return options.Overrides.DaemonRuntime.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonRuntime_b0e1ae70(endpointScope, endpointStore, endpointToken, serverBuild, serverProtocol, grpcServer, runtimePluginActivation, daemonListenerFactory)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonRuntime (*github.com/spice-framework/spice-agent-coding/internal/daemon.Runtime, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRuntime): %w", err))
	}
	if daemonRuntimeCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("spice.unassigned:github.com/spice-framework/spice-agent-coding/internal/daemon", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRuntime", daemonRuntimeCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonRuntime (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRuntime): %w", err))
		}
	}
	_ = daemonRuntime
	return &applicationDependencies{
		spiceLogger:                     spiceLogger,
		daemonIDSource:                  daemonIDSource,
		pendingHub:                      pendingHub,
		serverBuild:                     serverBuild,
		daemonRootRegistry:              daemonRootRegistry,
		endpointScope:                   endpointScope,
		endpointStore:                   endpointStore,
		endpointToken:                   endpointToken,
		daemonListenerFactory:           daemonListenerFactory,
		processLauncher:                 processLauncher,
		serverProtocol:                  serverProtocol,
		daemonInteractionBroker:         daemonInteractionBroker,
		processResolver:                 processResolver,
		verifiedProcessLauncher:         verifiedProcessLauncher,
		runtimePluginHostIdentity:       runtimePluginHostIdentity,
		daemonRoot:                      daemonRoot,
		sessionStore:                    sessionStore,
		operationLedger:                 operationLedger,
		serverLimits:                    serverLimits,
		runtimePluginEndpointFactory:    runtimePluginEndpointFactory,
		daemonProperties:                daemonProperties,
		openAIConfig:                    openAIConfig,
		runAuthority:                    runAuthority,
		definitionSet:                   definitionSet,
		agentLoggingConfig:              agentLoggingConfig,
		agentLoggingMailbox:             agentLoggingMailbox,
		agentLoggingProcessor:           agentLoggingProcessor,
		agentLoggingHealth:              agentLoggingHealth,
		openAIModelProvider:             openAIModelProvider,
		runtimePluginProperties:         runtimePluginProperties,
		runtimePluginPlan:               runtimePluginPlan,
		runtimePluginRestartPolicy:      runtimePluginRestartPolicy,
		workspaceProperties:             workspaceProperties,
		codingConfig:                    codingConfig,
		read:                            read,
		shell:                           shell,
		replace:                         replace,
		runtimePluginCompiledDispatcher: runtimePluginCompiledDispatcher,
		runtimePluginHost:               runtimePluginHost,
		runtimePluginActivation:         runtimePluginActivation,
		runtimePluginHealthSource:       runtimePluginHealthSource,
		runtimePluginToolPlanSource:     runtimePluginToolPlanSource,
		daemonEngine:                    daemonEngine,
		runHost:                         runHost,
		grpcServer:                      grpcServer,
		daemonRuntime:                   daemonRuntime,
	}, nil
}
