//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	fmt "fmt"
	io "io"
	slog "log/slog"
	strings "strings"
	time "time"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	spiceentrypoint "github.com/spice-framework/spice-agent-coding/internal/spicegen/spice_agentd/sources/cmd/spice-agentd"
	workspace "github.com/spice-framework/spice-agent-coding/internal/workspace"
	openaiprovider "github.com/spice-framework/spice-agent-provider-openai"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	agent "github.com/spice-framework/spice-agent/agent"
	client "github.com/spice-framework/spice-agent/client"
	daemon2 "github.com/spice-framework/spice-agent/daemon"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	grpcserver "github.com/spice-framework/spice-agent/daemon/grpcserver"
	event "github.com/spice-framework/spice-agent/event"
	interaction "github.com/spice-framework/spice-agent/interaction"
	logging "github.com/spice-framework/spice-agent/logging"
	model "github.com/spice-framework/spice-agent/model"
	pluginhost "github.com/spice-framework/spice-agent/plugin/host"
	pluginv1 "github.com/spice-framework/spice-agent/plugin/v1"
	process "github.com/spice-framework/spice-agent/process"
	stage "github.com/spice-framework/spice-agent/stage"
	tool "github.com/spice-framework/spice-agent/tool"
	spicebean "github.com/spice-framework/spice/bean"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
	spicelogging "github.com/spice-framework/spice/logging"
)

const TargetID = spiceentrypoint.ApplicationTargetSpiceAgentd_d556aede

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// DaemonIDSource is bean "daemonIDSource".
	DaemonIDSource agent.IDSource
	// PendingHub is bean "pendingHub".
	PendingHub *daemon2.PendingHub
	// ServerBuild is bean "serverBuild".
	ServerBuild client.Build
	// DaemonRootRegistry is bean "daemonRootRegistry".
	DaemonRootRegistry daemonprocess.RootRegistry
	// EndpointScope is bean "endpointScope".
	EndpointScope endpoint.UserScope
	// EndpointStore is bean "endpointStore".
	EndpointStore *endpoint.Store
	// EndpointToken is bean "endpointToken".
	EndpointToken endpoint.Token
	// DaemonListenerFactory is bean "daemonListenerFactory".
	DaemonListenerFactory daemon.ListenerFactory
	// ProcessLauncher is bean "processLauncher".
	ProcessLauncher process.Launcher
	// ServerProtocol is bean "serverProtocol".
	ServerProtocol client.ProtocolVersion
	// DaemonInteractionBroker is bean "daemonInteractionBroker".
	DaemonInteractionBroker interaction.Broker
	// ProcessResolver is bean "processResolver".
	ProcessResolver process.ExecutableResolver
	// VerifiedProcessLauncher is bean "verifiedProcessLauncher".
	VerifiedProcessLauncher process.VerifiedLauncher
	// RuntimePluginHostIdentity is bean "runtimePluginHostIdentity".
	RuntimePluginHostIdentity *pluginv1.BuildIdentity
	// DaemonRoot is bean "daemonRoot".
	DaemonRoot *daemon.Root
	// SessionStore is bean "sessionStore".
	SessionStore *daemon2.SessionStore
	// OperationLedger is bean "operationLedger".
	OperationLedger *daemon2.Ledger
	// ServerLimits is bean "serverLimits".
	ServerLimits client.Limits
	// RuntimePluginEndpointFactory is bean "runtimePluginEndpointFactory".
	RuntimePluginEndpointFactory pluginhost.LocalEndpointFactory
	// DaemonProperties is bean "Properties".
	DaemonProperties daemon.Properties
	// OpenAIConfig is bean "openAIConfig".
	OpenAIConfig openaiprovider.Config
	// RunAuthority is bean "runAuthority".
	RunAuthority *daemon2.RunAuthority
	// DefinitionSet is bean "definitionSet".
	DefinitionSet daemon2.DefinitionSet
	// AgentLoggingConfig is bean "agentLoggingConfig".
	AgentLoggingConfig logging.Config
	// AgentLoggingMailbox is bean "agentLoggingMailbox".
	AgentLoggingMailbox *event.BestEffortObserver
	// AgentLoggingProcessor is bean "agentLoggingProcessor".
	AgentLoggingProcessor *logging.Processor
	// AgentLoggingHealth is bean "agentLoggingHealth".
	AgentLoggingHealth daemon2.HealthSource
	// OpenAIModelProvider is bean "openAIModelProvider".
	OpenAIModelProvider model.Provider
	// RuntimePluginProperties is bean "RuntimePluginProperties".
	RuntimePluginProperties daemon.RuntimePluginProperties
	// RuntimePluginPlan is bean "runtimePluginPlan".
	RuntimePluginPlan daemon.RuntimePluginPlan
	// RuntimePluginRestartPolicy is bean "runtimePluginRestartPolicy".
	RuntimePluginRestartPolicy pluginhost.RestartPolicy
	// WorkspaceProperties is bean "Properties".
	WorkspaceProperties workspace.Properties
	// CodingConfig is bean "codingConfig".
	CodingConfig coding.Config
	// Read is bean "read".
	Read tool.Tool
	// Shell is bean "shell".
	Shell tool.Tool
	// Replace is bean "replace".
	Replace tool.Tool
	// RuntimePluginCompiledDispatcher is bean "runtimePluginCompiledDispatcher".
	RuntimePluginCompiledDispatcher stage.ToolDispatcher
	// RuntimePluginHost is bean "runtimePluginHost".
	RuntimePluginHost *pluginhost.Host
	// RuntimePluginActivation is bean "runtimePluginActivation".
	RuntimePluginActivation *daemon.RuntimePluginActivation
	// RuntimePluginHealthSource is bean "runtimePluginHealthSource".
	RuntimePluginHealthSource daemon2.HealthSource
	// RuntimePluginToolPlanSource is bean "runtimePluginToolPlanSource".
	RuntimePluginToolPlanSource stage.ToolPlanSource
	// DaemonEngine is bean "daemonEngine".
	DaemonEngine *agent.Engine
	// RunHost is bean "runHost".
	RunHost *daemon2.RunHost
	// GrpcServer is bean "grpcServer".
	GrpcServer *grpcserver.Server
	// DaemonRuntime is bean "daemonRuntime".
	DaemonRuntime *daemon.Runtime
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// DaemonIDSource replaces bean "daemonIDSource".
	DaemonIDSource spicebean.Override[agent.IDSource]
	// PendingHub replaces bean "pendingHub".
	PendingHub spicebean.Override[*daemon2.PendingHub]
	// ServerBuild replaces bean "serverBuild".
	ServerBuild spicebean.Override[client.Build]
	// DaemonRootRegistry replaces bean "daemonRootRegistry".
	DaemonRootRegistry spicebean.Override[daemonprocess.RootRegistry]
	// EndpointScope replaces bean "endpointScope".
	EndpointScope spicebean.Override[endpoint.UserScope]
	// EndpointStore replaces bean "endpointStore".
	EndpointStore spicebean.Override[*endpoint.Store]
	// EndpointToken replaces bean "endpointToken".
	EndpointToken spicebean.Override[endpoint.Token]
	// DaemonListenerFactory replaces bean "daemonListenerFactory".
	DaemonListenerFactory spicebean.Override[daemon.ListenerFactory]
	// ProcessLauncher replaces bean "processLauncher".
	ProcessLauncher spicebean.Override[process.Launcher]
	// ServerProtocol replaces bean "serverProtocol".
	ServerProtocol spicebean.Override[client.ProtocolVersion]
	// DaemonInteractionBroker replaces bean "daemonInteractionBroker".
	DaemonInteractionBroker spicebean.Override[interaction.Broker]
	// ProcessResolver replaces bean "processResolver".
	ProcessResolver spicebean.Override[process.ExecutableResolver]
	// VerifiedProcessLauncher replaces bean "verifiedProcessLauncher".
	VerifiedProcessLauncher spicebean.Override[process.VerifiedLauncher]
	// RuntimePluginHostIdentity replaces bean "runtimePluginHostIdentity".
	RuntimePluginHostIdentity spicebean.Override[*pluginv1.BuildIdentity]
	// DaemonRoot replaces bean "daemonRoot".
	DaemonRoot spicebean.Override[*daemon.Root]
	// SessionStore replaces bean "sessionStore".
	SessionStore spicebean.Override[*daemon2.SessionStore]
	// OperationLedger replaces bean "operationLedger".
	OperationLedger spicebean.Override[*daemon2.Ledger]
	// ServerLimits replaces bean "serverLimits".
	ServerLimits spicebean.Override[client.Limits]
	// RuntimePluginEndpointFactory replaces bean "runtimePluginEndpointFactory".
	RuntimePluginEndpointFactory spicebean.Override[pluginhost.LocalEndpointFactory]
	// OpenAIConfig replaces bean "openAIConfig".
	OpenAIConfig spicebean.Override[openaiprovider.Config]
	// RunAuthority replaces bean "runAuthority".
	RunAuthority spicebean.Override[*daemon2.RunAuthority]
	// DefinitionSet replaces bean "definitionSet".
	DefinitionSet spicebean.Override[daemon2.DefinitionSet]
	// AgentLoggingConfig replaces bean "agentLoggingConfig".
	AgentLoggingConfig spicebean.Override[logging.Config]
	// AgentLoggingMailbox replaces bean "agentLoggingMailbox".
	AgentLoggingMailbox spicebean.Override[*event.BestEffortObserver]
	// AgentLoggingProcessor replaces bean "agentLoggingProcessor".
	AgentLoggingProcessor spicebean.Override[*logging.Processor]
	// AgentLoggingHealth replaces bean "agentLoggingHealth".
	AgentLoggingHealth spicebean.Override[daemon2.HealthSource]
	// OpenAIModelProvider replaces bean "openAIModelProvider".
	OpenAIModelProvider spicebean.Override[model.Provider]
	// RuntimePluginPlan replaces bean "runtimePluginPlan".
	RuntimePluginPlan spicebean.Override[daemon.RuntimePluginPlan]
	// RuntimePluginRestartPolicy replaces bean "runtimePluginRestartPolicy".
	RuntimePluginRestartPolicy spicebean.Override[pluginhost.RestartPolicy]
	// CodingConfig replaces bean "codingConfig".
	CodingConfig spicebean.Override[coding.Config]
	// Read replaces bean "read".
	Read spicebean.Override[tool.Tool]
	// Shell replaces bean "shell".
	Shell spicebean.Override[tool.Tool]
	// Replace replaces bean "replace".
	Replace spicebean.Override[tool.Tool]
	// RuntimePluginCompiledDispatcher replaces bean "runtimePluginCompiledDispatcher".
	RuntimePluginCompiledDispatcher spicebean.Override[stage.ToolDispatcher]
	// RuntimePluginHost replaces bean "runtimePluginHost".
	RuntimePluginHost spicebean.Override[*pluginhost.Host]
	// RuntimePluginActivation replaces bean "runtimePluginActivation".
	RuntimePluginActivation spicebean.Override[*daemon.RuntimePluginActivation]
	// RuntimePluginHealthSource replaces bean "runtimePluginHealthSource".
	RuntimePluginHealthSource spicebean.Override[daemon2.HealthSource]
	// RuntimePluginToolPlanSource replaces bean "runtimePluginToolPlanSource".
	RuntimePluginToolPlanSource spicebean.Override[stage.ToolPlanSource]
	// DaemonEngine replaces bean "daemonEngine".
	DaemonEngine spicebean.Override[*agent.Engine]
	// RunHost replaces bean "runHost".
	RunHost spicebean.Override[*daemon2.RunHost]
	// GrpcServer replaces bean "grpcServer".
	GrpcServer spicebean.Override[*grpcserver.Server]
	// DaemonRuntime replaces bean "daemonRuntime".
	DaemonRuntime spicebean.Override[*daemon.Runtime]
}

// BeanOverrideLayer is one named immutable override composition layer.
// Layers are applied in order; a later layer deliberately replaces an earlier value.
type BeanOverrideLayer struct {
	Name      string
	Overrides BeanOverrides
}

// ComposeBeanOverrides validates and deterministically composes named layers.
// It never mutates a running application or performs runtime bean lookup.
func ComposeBeanOverrides(layers ...BeanOverrideLayer) (BeanOverrides, error) {
	result := BeanOverrides{}
	seen := make(map[string]int, len(layers))
	for index, layer := range layers {
		if layer.Name == "" || strings.TrimSpace(layer.Name) != layer.Name {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %d requires a non-empty name without surrounding whitespace", index)
		}
		if previous, duplicate := seen[layer.Name]; duplicate {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %q repeats layer %d", layer.Name, previous)
		}
		seen[layer.Name] = index
		if layer.Overrides.DaemonIDSource.Enabled() {
			result.DaemonIDSource = layer.Overrides.DaemonIDSource
		}
		if layer.Overrides.PendingHub.Enabled() {
			result.PendingHub = layer.Overrides.PendingHub
		}
		if layer.Overrides.ServerBuild.Enabled() {
			result.ServerBuild = layer.Overrides.ServerBuild
		}
		if layer.Overrides.DaemonRootRegistry.Enabled() {
			result.DaemonRootRegistry = layer.Overrides.DaemonRootRegistry
		}
		if layer.Overrides.EndpointScope.Enabled() {
			result.EndpointScope = layer.Overrides.EndpointScope
		}
		if layer.Overrides.EndpointStore.Enabled() {
			result.EndpointStore = layer.Overrides.EndpointStore
		}
		if layer.Overrides.EndpointToken.Enabled() {
			result.EndpointToken = layer.Overrides.EndpointToken
		}
		if layer.Overrides.DaemonListenerFactory.Enabled() {
			result.DaemonListenerFactory = layer.Overrides.DaemonListenerFactory
		}
		if layer.Overrides.ProcessLauncher.Enabled() {
			result.ProcessLauncher = layer.Overrides.ProcessLauncher
		}
		if layer.Overrides.ServerProtocol.Enabled() {
			result.ServerProtocol = layer.Overrides.ServerProtocol
		}
		if layer.Overrides.DaemonInteractionBroker.Enabled() {
			result.DaemonInteractionBroker = layer.Overrides.DaemonInteractionBroker
		}
		if layer.Overrides.ProcessResolver.Enabled() {
			result.ProcessResolver = layer.Overrides.ProcessResolver
		}
		if layer.Overrides.VerifiedProcessLauncher.Enabled() {
			result.VerifiedProcessLauncher = layer.Overrides.VerifiedProcessLauncher
		}
		if layer.Overrides.RuntimePluginHostIdentity.Enabled() {
			result.RuntimePluginHostIdentity = layer.Overrides.RuntimePluginHostIdentity
		}
		if layer.Overrides.DaemonRoot.Enabled() {
			result.DaemonRoot = layer.Overrides.DaemonRoot
		}
		if layer.Overrides.SessionStore.Enabled() {
			result.SessionStore = layer.Overrides.SessionStore
		}
		if layer.Overrides.OperationLedger.Enabled() {
			result.OperationLedger = layer.Overrides.OperationLedger
		}
		if layer.Overrides.ServerLimits.Enabled() {
			result.ServerLimits = layer.Overrides.ServerLimits
		}
		if layer.Overrides.RuntimePluginEndpointFactory.Enabled() {
			result.RuntimePluginEndpointFactory = layer.Overrides.RuntimePluginEndpointFactory
		}
		if layer.Overrides.OpenAIConfig.Enabled() {
			result.OpenAIConfig = layer.Overrides.OpenAIConfig
		}
		if layer.Overrides.RunAuthority.Enabled() {
			result.RunAuthority = layer.Overrides.RunAuthority
		}
		if layer.Overrides.DefinitionSet.Enabled() {
			result.DefinitionSet = layer.Overrides.DefinitionSet
		}
		if layer.Overrides.AgentLoggingConfig.Enabled() {
			result.AgentLoggingConfig = layer.Overrides.AgentLoggingConfig
		}
		if layer.Overrides.AgentLoggingMailbox.Enabled() {
			result.AgentLoggingMailbox = layer.Overrides.AgentLoggingMailbox
		}
		if layer.Overrides.AgentLoggingProcessor.Enabled() {
			result.AgentLoggingProcessor = layer.Overrides.AgentLoggingProcessor
		}
		if layer.Overrides.AgentLoggingHealth.Enabled() {
			result.AgentLoggingHealth = layer.Overrides.AgentLoggingHealth
		}
		if layer.Overrides.OpenAIModelProvider.Enabled() {
			result.OpenAIModelProvider = layer.Overrides.OpenAIModelProvider
		}
		if layer.Overrides.RuntimePluginPlan.Enabled() {
			result.RuntimePluginPlan = layer.Overrides.RuntimePluginPlan
		}
		if layer.Overrides.RuntimePluginRestartPolicy.Enabled() {
			result.RuntimePluginRestartPolicy = layer.Overrides.RuntimePluginRestartPolicy
		}
		if layer.Overrides.CodingConfig.Enabled() {
			result.CodingConfig = layer.Overrides.CodingConfig
		}
		if layer.Overrides.Read.Enabled() {
			result.Read = layer.Overrides.Read
		}
		if layer.Overrides.Shell.Enabled() {
			result.Shell = layer.Overrides.Shell
		}
		if layer.Overrides.Replace.Enabled() {
			result.Replace = layer.Overrides.Replace
		}
		if layer.Overrides.RuntimePluginCompiledDispatcher.Enabled() {
			result.RuntimePluginCompiledDispatcher = layer.Overrides.RuntimePluginCompiledDispatcher
		}
		if layer.Overrides.RuntimePluginHost.Enabled() {
			result.RuntimePluginHost = layer.Overrides.RuntimePluginHost
		}
		if layer.Overrides.RuntimePluginActivation.Enabled() {
			result.RuntimePluginActivation = layer.Overrides.RuntimePluginActivation
		}
		if layer.Overrides.RuntimePluginHealthSource.Enabled() {
			result.RuntimePluginHealthSource = layer.Overrides.RuntimePluginHealthSource
		}
		if layer.Overrides.RuntimePluginToolPlanSource.Enabled() {
			result.RuntimePluginToolPlanSource = layer.Overrides.RuntimePluginToolPlanSource
		}
		if layer.Overrides.DaemonEngine.Enabled() {
			result.DaemonEngine = layer.Overrides.DaemonEngine
		}
		if layer.Overrides.RunHost.Enabled() {
			result.RunHost = layer.Overrides.RunHost
		}
		if layer.Overrides.GrpcServer.Enabled() {
			result.GrpcServer = layer.Overrides.GrpcServer
		}
		if layer.Overrides.DaemonRuntime.Enabled() {
			result.DaemonRuntime = layer.Overrides.DaemonRuntime
		}
	}
	return result, nil
}

type LoggingOptions struct {
	Writer        io.Writer
	Handler       slog.Handler
	Configuration *spicelogging.Configuration
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
	logger          *spicelogging.Logger
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	Logging                   *LoggingOptions
	// Logger is deprecated; use Logging.
	Logger    *slog.Logger
	Observers []spicelifecycle.Observer
}
