//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"

	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

func configureGeneratedLifecycle(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	dependencies *applicationDependencies,
) (*Application, error) {
	_ = ctx
	_ = options
	_ = dependencies
	application.hooks = []spicelifecycle.Hook{
		{
			ID:     "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewRuntimePluginActivation",
			Module: "github.com/spice-framework/spice-agent-coding/internal/daemon",
			Start:  dependencies.runtimePluginActivation.Start,
		},
		{
			ID:     "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRuntime",
			Module: "github.com/spice-framework/spice-agent-coding/internal/daemon",
			Start:  dependencies.daemonRuntime.Start,
			Stop:   dependencies.daemonRuntime.Stop,
		},
	}
	return application, nil
}
