//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"
	io "io"
	slog "log/slog"

	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
	spicelogging "github.com/spice-framework/spice/logging"
	spiceobservability "github.com/spice-framework/spice/observability"
)

func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {
	return NewApplicationWithOptions(ctx, ApplicationOptions{Observers: observers})
}

func NewApplicationWithOptions(ctx context.Context, options ApplicationOptions) (*Application, error) {
	if ctx == nil {
		return nil, fmt.Errorf("construct application spice_agentd: context is nil")
	}
	application := &Application{coordinator: spicelifecycle.NewCoordinator()}
	configurationSchema, err := ConfigurationSchema()
	if err != nil {
		return nil, fmt.Errorf("construct configuration schema for application spice_agentd: %w", err)
	}
	configurationSnapshot, err := spiceconfig.Resolve(
		ctx,
		configurationSchema,
		spiceconfig.Options{
			Profiles:     options.Profiles,
			AllowUnknown: options.AllowUnknownConfiguration,
		},
		options.Sources...,
	)
	if err != nil {
		return nil, fmt.Errorf("resolve configuration for application spice_agentd: %w", err)
	}
	application.shutdownTimeout, err = configurationSnapshot.Duration("spice.shutdown-timeout")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application spice_agentd: %w", err))
	}
	if application.shutdownTimeout <= 0 {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application spice_agentd: duration must be positive"))
	}
	loggingFormatValue, err := configurationSnapshot.RequiredString("spice.logging.format")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode Spice logging format: %w", err))
	}
	loggingLevelValue, err := configurationSnapshot.RequiredString("spice.logging.level")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode Spice logging level: %w", err))
	}
	loggingLevel, err := spicelogging.ParseLevel(loggingLevelValue)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode Spice logging level: %w", err))
	}
	loggingAddSource, err := configurationSnapshot.Boolean("spice.logging.add-source")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode Spice logging source policy: %w", err))
	}
	loggingScopes := []spicelogging.Scope{
		{Module: "github.com/spice-framework/spice-agent-coding/cmd/spice-agentd"},
		{Module: "github.com/spice-framework/spice-agent-coding/cmd/spice-agentd", Component: "spice.schedule"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRunHost"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRuntime"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|11:NewIDSource"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewGRPCServer"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|14:NewServerBuild"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewCodingConfig"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewOpenAIConfig"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRootRegistry"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRunAuthority"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewSessionStore"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewDefinitionSet"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointScope"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointStore"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointToken"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewListenerFactory"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProcessLauncher"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProtocolVersion"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewInteractionBroker"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewRuntimePluginHost"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewRuntimePluginPlan"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewAgentLoggingConfig"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewExecutableResolver"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewRuntimePluginActivation"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|26:NewVerifiedProcessLauncher"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|27:NewAgentLoggingHealthSource"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHealthSource"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|28:NewRuntimePluginHostIdentity"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|29:NewRuntimePluginRestartPolicy"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|7:NewRoot"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLedger"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLimits"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|type|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:Properties"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemon", Component: "spice:symbol:v1|type|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|23:RuntimePluginProperties"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/distribution"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/processplatform"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/runidentity"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/workspace"},
		{Module: "github.com/spice-framework/spice-agent-coding/internal/workspace", Component: "spice:symbol:v1|type|64:github.com/spice-framework/spice-agent-coding/internal/workspace|0:|10:Properties"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent-provider-openai/autoconfigure"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent-provider-openai/autoconfigure", Component: "spice:symbol:v1|function|68:github.com/spice-framework/spice-agent-provider-openai/autoconfigure|0:|7:Default"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent-tools-coding/autoconfigure"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent-tools-coding/autoconfigure", Component: "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent-tools-coding/autoconfigure", Component: "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent-tools-coding/autoconfigure", Component: "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent/logging/autoconfigure"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent/logging/autoconfigure", Component: "spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|14:DefaultMailbox"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent/logging/autoconfigure", Component: "spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|16:DefaultProcessor"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent/plugin/host/autoconfigure"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent/plugin/host/autoconfigure", Component: "spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|21:DefaultToolPlanSource"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent/plugin/host/autoconfigure", Component: "spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|25:DefaultCompiledDispatcher"},
		{Module: "spice.unassigned:github.com/spice-framework/spice-agent/plugin/host/autoconfigure", Component: "spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|33:DefaultCurrentUserEndpointFactory"},
	}
	loggingLevelsValue, _ := configurationSnapshot.Lookup("spice.logging.levels")
	loggingLevels, err := spicelogging.ParseLevelRules(loggingLevelsValue, loggingScopes)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode Spice logging scope levels: %w", err))
	}
	loggingConfiguration := spicelogging.Configuration{
		Format: spicelogging.Format(loggingFormatValue), Level: loggingLevel,
		Levels: loggingLevels, AddSource: loggingAddSource,
	}
	var loggingWriter io.Writer
	var loggingHandler slog.Handler
	if options.Logging != nil {
		if (options.Logging.Writer == nil) == (options.Logging.Handler == nil) {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure Spice logging: exactly one writer or handler is required"))
		}
		loggingWriter = options.Logging.Writer
		loggingHandler = options.Logging.Handler
		if options.Logging.Configuration != nil {
			loggingConfiguration = *options.Logging.Configuration
		}
	}
	if options.Logging != nil && options.Logger != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure Spice logging: Logging and deprecated Logger conflict"))
	}
	if options.Logging == nil && options.Logger != nil {
		loggingHandler = options.Logger.Handler()
	}
	application.logger, err = spicelogging.New(spicelogging.Options{
		Application: TargetID, Configuration: loggingConfiguration,
		Writer: loggingWriter, Handler: loggingHandler, Scopes: loggingScopes,
	})
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure Spice logging: %w", err))
	}
	observers := append([]spicelifecycle.Observer(nil), options.Observers...)
	loggingObservers, err := spiceobservability.NewLoggingObservers(application.logger)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure Spice logging observers: %w", err))
	}
	observers = append([]spicelifecycle.Observer{loggingObservers.Lifecycle}, observers...)
	for index, observer := range observers {
		if err := application.coordinator.RegisterObserver(observer); err != nil {
			return nil, fmt.Errorf("register lifecycle observer %d: %w", index, err)
		}
	}
	dependencies, err := constructApplicationDependencies(ctx, application, options, configurationSnapshot)
	if err != nil {
		return nil, err
	}
	_ = dependencies
	application.components = Components{
		DaemonIDSource:                  dependencies.daemonIDSource,
		PendingHub:                      dependencies.pendingHub,
		ServerBuild:                     dependencies.serverBuild,
		DaemonRootRegistry:              dependencies.daemonRootRegistry,
		EndpointScope:                   dependencies.endpointScope,
		EndpointStore:                   dependencies.endpointStore,
		EndpointToken:                   dependencies.endpointToken,
		DaemonListenerFactory:           dependencies.daemonListenerFactory,
		ProcessLauncher:                 dependencies.processLauncher,
		ServerProtocol:                  dependencies.serverProtocol,
		DaemonInteractionBroker:         dependencies.daemonInteractionBroker,
		ProcessResolver:                 dependencies.processResolver,
		VerifiedProcessLauncher:         dependencies.verifiedProcessLauncher,
		RuntimePluginHostIdentity:       dependencies.runtimePluginHostIdentity,
		DaemonRoot:                      dependencies.daemonRoot,
		SessionStore:                    dependencies.sessionStore,
		OperationLedger:                 dependencies.operationLedger,
		ServerLimits:                    dependencies.serverLimits,
		RuntimePluginEndpointFactory:    dependencies.runtimePluginEndpointFactory,
		DaemonProperties:                dependencies.daemonProperties,
		OpenAIConfig:                    dependencies.openAIConfig,
		RunAuthority:                    dependencies.runAuthority,
		DefinitionSet:                   dependencies.definitionSet,
		AgentLoggingConfig:              dependencies.agentLoggingConfig,
		AgentLoggingMailbox:             dependencies.agentLoggingMailbox,
		AgentLoggingProcessor:           dependencies.agentLoggingProcessor,
		AgentLoggingHealth:              dependencies.agentLoggingHealth,
		OpenAIModelProvider:             dependencies.openAIModelProvider,
		RuntimePluginProperties:         dependencies.runtimePluginProperties,
		RuntimePluginPlan:               dependencies.runtimePluginPlan,
		RuntimePluginRestartPolicy:      dependencies.runtimePluginRestartPolicy,
		WorkspaceProperties:             dependencies.workspaceProperties,
		CodingConfig:                    dependencies.codingConfig,
		Read:                            dependencies.read,
		Shell:                           dependencies.shell,
		Replace:                         dependencies.replace,
		RuntimePluginCompiledDispatcher: dependencies.runtimePluginCompiledDispatcher,
		RuntimePluginHost:               dependencies.runtimePluginHost,
		RuntimePluginActivation:         dependencies.runtimePluginActivation,
		RuntimePluginHealthSource:       dependencies.runtimePluginHealthSource,
		RuntimePluginToolPlanSource:     dependencies.runtimePluginToolPlanSource,
		DaemonEngine:                    dependencies.daemonEngine,
		RunHost:                         dependencies.runHost,
		GrpcServer:                      dependencies.grpcServer,
		DaemonRuntime:                   dependencies.daemonRuntime,
	}
	if _, err := configureGeneratedLifecycle(ctx, application, options, dependencies); err != nil {
		return nil, err
	}
	return application, nil
}
