//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	spiceconfig "github.com/spice-framework/spice/config"
)

func ConfigurationSchema() (spiceconfig.Schema, error) {
	return spiceconfig.NewSchema(
		spiceconfig.Property{
			Key:         "agent.openai.api-key",
			Kind:        spiceconfig.KindString,
			Environment: "OPENAI_API_KEY",
			Required:    true,
			Secret:      true,
		},
		spiceconfig.Property{
			Key:         "agent.openai.base-url",
			Kind:        spiceconfig.KindString,
			Environment: "OPENAI_BASE_URL",
			Default:     "https://api.openai.com/v1",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.openai.organization",
			Kind:        spiceconfig.KindString,
			Environment: "OPENAI_ORGANIZATION",
		},
		spiceconfig.Property{
			Key:         "agent.openai.project",
			Kind:        spiceconfig.KindString,
			Environment: "OPENAI_PROJECT",
		},
		spiceconfig.Property{
			Key:         "agent.openai.timeout",
			Kind:        spiceconfig.KindDuration,
			Environment: "OPENAI_TIMEOUT",
			Default:     "2m",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.openai.max-retries",
			Kind:        spiceconfig.KindInteger,
			Environment: "OPENAI_MAX_RETRIES",
			Default:     "0",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.model",
			Kind:        spiceconfig.KindString,
			Environment: "OPENAI_MODEL",
			Required:    true,
		},
		spiceconfig.Property{
			Key:         "agent.run-authority-directory",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_AGENT_RUN_AUTHORITY_DIRECTORY",
		},
		spiceconfig.Property{
			Key:         "agent.logging.mailbox-capacity",
			Kind:        spiceconfig.KindInteger,
			Environment: "SPICE_AGENT_LOGGING_MAILBOX_CAPACITY",
			Default:     "1024",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.logging.include-progress",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_AGENT_LOGGING_INCLUDE_PROGRESS",
			Default:     "false",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.logging.readiness-impact",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_AGENT_LOGGING_READINESS_IMPACT",
			Default:     "false",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.required",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_REQUIRED",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.id",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_ID",
			Default:     "runtime-tool",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.path",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_PATH",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.sha256",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_SHA256",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.manifest-name",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_MANIFEST_NAME",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.manifest-version",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_MANIFEST_VERSION",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.working-directory",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_WORKING_DIRECTORY",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.capabilities.filesystem-read",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_FILESYSTEM_READ",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.capabilities.filesystem-write",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_FILESYSTEM_WRITE",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.capabilities.process-execute",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_PROCESS_EXECUTE",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.capabilities.network-access",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_NETWORK_ACCESS",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.capabilities.secrets-read",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_SECRETS_READ",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.capabilities.environment-read",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_ENVIRONMENT_READ",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.capabilities.environment-write",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_ENVIRONMENT_WRITE",
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.timeouts.startup",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_STARTUP_TIMEOUT",
			Default:     "10s",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.timeouts.call",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_CALL_TIMEOUT",
			Default:     "2m",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.timeouts.drain",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_DRAIN_TIMEOUT",
			Default:     "10s",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.timeouts.shutdown",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_SHUTDOWN_TIMEOUT",
			Default:     "10s",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.runtime-plugin.timeouts.containment",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_AGENT_RUNTIME_PLUGIN_CONTAINMENT_TIMEOUT",
			Default:     "5s",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.workspace",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_AGENT_WORKSPACE",
			Default:     ".",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "spice.logging.format",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_LOGGING_FORMAT",
			Default:     "json",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "spice.logging.level",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_LOGGING_LEVEL",
			Default:     "info",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "spice.logging.levels",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_LOGGING_LEVELS",
			Default:     "",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "spice.logging.add-source",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_LOGGING_ADD_SOURCE",
			Default:     "false",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "spice.shutdown-timeout",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_SHUTDOWN_TIMEOUT",
			Default:     "10s",
			HasDefault:  true,
		},
	)
}
