//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/application.go:13

package spicegen

// ApplicationTargetTerminal_8be179f5 identifies the generated target selected by spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|8:Terminal.
const ApplicationTargetTerminal_8be179f5 = "terminal"
