//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/session.go:17
// Source: internal/terminal/session.go:24
// Source: internal/terminal/session.go:39
// Source: internal/terminal/session.go:51
// Source: internal/terminal/session.go:64
// Source: internal/terminal/session.go:72

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	tuisession "github.com/spice-framework/spice-agent-coding/internal/tuisession"
	agenttui "github.com/spice-framework/spice-agent-tui"
	client "github.com/spice-framework/spice-agent/client"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalSession_bcae29da performs the direct construction selected for bean "terminalSession".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|10:NewSession.
func ConstructTerminalSession_bcae29da(dependency0 tuisession.Config, dependency1 client.Connector, dependency2 tuisession.IdentifierSource) (agenttui.Session, spicelifecycle.Cleanup, error) {
	value, cleanup, err := terminal.NewSession(dependency0, dependency1, dependency2)
	if err != nil {
		var zero agenttui.Session
		return zero, nil, fmt.Errorf("construct bean terminalSession (github.com/spice-framework/spice-agent-tui.Session, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|10:NewSession): %w", err)
	}
	return value, cleanup, nil
}

// ConstructTerminalWorkspace_8ebebbbd performs the direct construction selected for bean "terminalWorkspace".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|12:NewWorkspace.
func ConstructTerminalWorkspace_8ebebbbd(dependency0 terminal.Properties) (agenttui.WorkspaceState, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewWorkspace(dependency0)
	if err != nil {
		var zero agenttui.WorkspaceState
		return zero, nil, fmt.Errorf("construct bean terminalWorkspace (github.com/spice-framework/spice-agent-tui.WorkspaceState, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|12:NewWorkspace): %w", err)
	}
	return value, nil, nil
}

// ConstructTerminalDefinition_7925977f performs the direct construction selected for bean "terminalDefinition".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|13:NewDefinition.
func ConstructTerminalDefinition_7925977f() (client.DefinitionRef, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewDefinition()
	if err != nil {
		var zero client.DefinitionRef
		return zero, nil, fmt.Errorf("construct bean terminalDefinition (github.com/spice-framework/spice-agent/client.DefinitionRef, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|13:NewDefinition): %w", err)
	}
	return value, nil, nil
}

// ConstructTerminalInitialStatus_3572e532 performs the direct construction selected for bean "terminalInitialStatus".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewInitialStatus.
func ConstructTerminalInitialStatus_3572e532() (agenttui.StatusState, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewInitialStatus()
	if err != nil {
		var zero agenttui.StatusState
		return zero, nil, fmt.Errorf("construct bean terminalInitialStatus (github.com/spice-framework/spice-agent-tui.StatusState, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewInitialStatus): %w", err)
	}
	return value, nil, nil
}

// ConstructTerminalSessionConfig_87aa536d performs the direct construction selected for bean "terminalSessionConfig".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewSessionConfig.
func ConstructTerminalSessionConfig_87aa536d(dependency0 client.InitializeRequest, dependency1 client.DefinitionRef, dependency2 agenttui.WorkspaceState, dependency3 agenttui.StatusState) (tuisession.Config, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewSessionConfig(dependency0, dependency1, dependency2, dependency3)
	if err != nil {
		var zero tuisession.Config
		return zero, nil, fmt.Errorf("construct bean terminalSessionConfig (github.com/spice-framework/spice-agent-coding/internal/tuisession.Config, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewSessionConfig): %w", err)
	}
	return value, nil, nil
}

// ConstructTerminalIdentifierSource_3f0df0e0 performs the direct construction selected for bean "terminalIdentifierSource".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|19:NewIdentifierSource.
func ConstructTerminalIdentifierSource_3f0df0e0() (tuisession.IdentifierSource, spicelifecycle.Cleanup, error) {
	value := terminal.NewIdentifierSource()
	return value, nil, nil
}
