//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/workspace/properties.go:8

package spicegen

import (
	fmt "fmt"

	workspace "github.com/spice-framework/spice-agent-coding/internal/workspace"
	spiceconfig "github.com/spice-framework/spice/config"
)

// BindProperties_1313dff6 binds the validated configuration declared by spice:symbol:v1|type|64:github.com/spice-framework/spice-agent-coding/internal/workspace|0:|10:Properties.
func BindProperties_1313dff6(configurationSnapshot spiceconfig.Snapshot) (workspace.Properties, error) {
	value := workspace.Properties{}
	if _, configured := configurationSnapshot.Lookup("agent.workspace"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.workspace")
		if valueErr != nil {
			return workspace.Properties{}, fmt.Errorf("decode configuration property agent.workspace for github.com/spice-framework/spice-agent-coding/internal/workspace.Properties.Workspace: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.Workspace = convertedValue
	}
	return value, nil
}
