//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: vendor/github.com/spice-framework/spice-agent-provider-openai/autoconfigure/autoconfigure.go:13

package spicegen

import (
	fmt "fmt"

	openaiprovider "github.com/spice-framework/spice-agent-provider-openai"
	autoconfigure "github.com/spice-framework/spice-agent-provider-openai/autoconfigure"
	model "github.com/spice-framework/spice-agent/model"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructOpenAIModelProvider_2228c855 performs the direct construction selected for bean "openAIModelProvider".
// Spice source identity: spice:symbol:v1|function|68:github.com/spice-framework/spice-agent-provider-openai/autoconfigure|0:|7:Default.
func ConstructOpenAIModelProvider_2228c855(dependency0 openaiprovider.Config) (model.Provider, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.Default(dependency0)
	if err != nil {
		var zero model.Provider
		return zero, nil, fmt.Errorf("construct bean openAIModelProvider (github.com/spice-framework/spice-agent/model.Provider, source spice:symbol:v1|function|68:github.com/spice-framework/spice-agent-provider-openai/autoconfigure|0:|7:Default): %w", err)
	}
	return value, nil, nil
}
