//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	spiceDaemon "github.com/spice-framework/spice-agent-coding/internal/spicegen/daemon/sources/internal_/daemon"
	spiceAutoconfigure "github.com/spice-framework/spice-agent-coding/internal/spicegen/daemon/sources/vendor_/github.com/spice-framework/spice-agent-provider-openai/autoconfigure"
	spiceAutoconfigure2 "github.com/spice-framework/spice-agent-coding/internal/spicegen/daemon/sources/vendor_/github.com/spice-framework/spice-agent-tools-coding/autoconfigure"
	openaiprovider "github.com/spice-framework/spice-agent-provider-openai"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	agent "github.com/spice-framework/spice-agent/agent"
	client "github.com/spice-framework/spice-agent/client"
	daemon2 "github.com/spice-framework/spice-agent/daemon"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	grpcserver "github.com/spice-framework/spice-agent/daemon/grpcserver"
	interaction "github.com/spice-framework/spice-agent/interaction"
	model "github.com/spice-framework/spice-agent/model"
	process "github.com/spice-framework/spice-agent/process"
	stage "github.com/spice-framework/spice-agent/stage"
	tool "github.com/spice-framework/spice-agent/tool"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

type applicationDependencies struct {
	pendingHub              *daemon2.PendingHub
	serverBuild             client.Build
	daemonRootRegistry      daemonprocess.RootRegistry
	endpointScope           endpoint.UserScope
	endpointStore           *endpoint.Store
	endpointToken           endpoint.Token
	processLauncher         process.Launcher
	serverProtocol          client.ProtocolVersion
	daemonInteractionBroker interaction.Broker
	processResolver         process.ExecutableResolver
	daemonRoot              *daemon.Root
	sessionStore            *daemon2.SessionStore
	operationLedger         *daemon2.Ledger
	serverLimits            client.Limits
	properties              daemon.Properties
	codingConfig            coding.Config
	openAIConfig            openaiprovider.Config
	runAuthority            *daemon2.RunAuthority
	definitionSet           daemon2.DefinitionSet
	read                    tool.Tool
	shell                   tool.Tool
	replace                 tool.Tool
	daemonToolDispatcher    stage.ToolDispatcher
	daemonToolPlanSource    stage.ToolPlanSource
	openAIModelProvider     model.Provider
	daemonEngine            *agent.Engine
	runHost                 *daemon2.RunHost
	grpcServer              *grpcserver.Server
	daemonRuntime           *daemon.Runtime
}

func constructApplicationDependencies(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
) (*applicationDependencies, error) {
	_ = ctx
	_ = application
	_ = options
	_ = configurationSnapshot
	pendingHub, pendingHubCleanup, err := func() (*daemon2.PendingHub, spicelifecycle.Cleanup, error) {
		if options.Overrides.PendingHub.Enabled() {
			return options.Overrides.PendingHub.Acquire(ctx)
		}
		return spiceDaemon.ConstructPendingHub_4cbcfd89()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean pendingHub (*github.com/spice-framework/spice-agent/daemon.PendingHub, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub): %w", err))
	}
	if pendingHubCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub", pendingHubCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean pendingHub (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub): %w", err))
		}
	}
	_ = pendingHub
	serverBuild, serverBuildCleanup, err := func() (client.Build, spicelifecycle.Cleanup, error) {
		if options.Overrides.ServerBuild.Enabled() {
			return options.Overrides.ServerBuild.Acquire(ctx)
		}
		return spiceDaemon.ConstructServerBuild_a30ee9e7()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean serverBuild (github.com/spice-framework/spice-agent/client.Build, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|14:NewServerBuild): %w", err))
	}
	if serverBuildCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|14:NewServerBuild", serverBuildCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean serverBuild (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|14:NewServerBuild): %w", err))
		}
	}
	_ = serverBuild
	daemonRootRegistry, daemonRootRegistryCleanup, err := func() (daemonprocess.RootRegistry, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonRootRegistry.Enabled() {
			return options.Overrides.DaemonRootRegistry.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonRootRegistry_5e3757f8()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonRootRegistry (github.com/spice-framework/spice-agent-coding/internal/daemonprocess.RootRegistry, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRootRegistry): %w", err))
	}
	if daemonRootRegistryCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRootRegistry", daemonRootRegistryCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonRootRegistry (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRootRegistry): %w", err))
		}
	}
	_ = daemonRootRegistry
	endpointScope, endpointScopeCleanup, err := func() (endpoint.UserScope, spicelifecycle.Cleanup, error) {
		if options.Overrides.EndpointScope.Enabled() {
			return options.Overrides.EndpointScope.Acquire(ctx)
		}
		return spiceDaemon.ConstructEndpointScope_4a25ec50()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean endpointScope (github.com/spice-framework/spice-agent/daemon/endpoint.UserScope, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointScope): %w", err))
	}
	if endpointScopeCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointScope", endpointScopeCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean endpointScope (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointScope): %w", err))
		}
	}
	_ = endpointScope
	endpointStore, endpointStoreCleanup, err := func() (*endpoint.Store, spicelifecycle.Cleanup, error) {
		if options.Overrides.EndpointStore.Enabled() {
			return options.Overrides.EndpointStore.Acquire(ctx)
		}
		return spiceDaemon.ConstructEndpointStore_c41f25a3(endpointScope)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean endpointStore (*github.com/spice-framework/spice-agent/daemon/endpoint.Store, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointStore): %w", err))
	}
	if endpointStoreCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointStore", endpointStoreCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean endpointStore (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointStore): %w", err))
		}
	}
	_ = endpointStore
	endpointToken, endpointTokenCleanup, err := func() (endpoint.Token, spicelifecycle.Cleanup, error) {
		if options.Overrides.EndpointToken.Enabled() {
			return options.Overrides.EndpointToken.Acquire(ctx)
		}
		return spiceDaemon.ConstructEndpointToken_94cf31d6()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean endpointToken (github.com/spice-framework/spice-agent/daemon/endpoint.Token, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointToken): %w", err))
	}
	if endpointTokenCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointToken", endpointTokenCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean endpointToken (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewEndpointToken): %w", err))
		}
	}
	_ = endpointToken
	processLauncher, processLauncherCleanup, err := func() (process.Launcher, spicelifecycle.Cleanup, error) {
		if options.Overrides.ProcessLauncher.Enabled() {
			return options.Overrides.ProcessLauncher.Acquire(ctx)
		}
		return spiceDaemon.ConstructProcessLauncher_6dd45eb0(daemonRootRegistry)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean processLauncher (github.com/spice-framework/spice-agent/process.Launcher, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProcessLauncher): %w", err))
	}
	if processLauncherCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProcessLauncher", processLauncherCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean processLauncher (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProcessLauncher): %w", err))
		}
	}
	_ = processLauncher
	serverProtocol, serverProtocolCleanup, err := func() (client.ProtocolVersion, spicelifecycle.Cleanup, error) {
		if options.Overrides.ServerProtocol.Enabled() {
			return options.Overrides.ServerProtocol.Acquire(ctx)
		}
		return spiceDaemon.ConstructServerProtocol_5afceae2()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean serverProtocol (github.com/spice-framework/spice-agent/client.ProtocolVersion, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProtocolVersion): %w", err))
	}
	if serverProtocolCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProtocolVersion", serverProtocolCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean serverProtocol (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|18:NewProtocolVersion): %w", err))
		}
	}
	_ = serverProtocol
	daemonInteractionBroker, daemonInteractionBrokerCleanup, err := func() (interaction.Broker, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonInteractionBroker.Enabled() {
			return options.Overrides.DaemonInteractionBroker.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonInteractionBroker_bf812f17(pendingHub)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonInteractionBroker (github.com/spice-framework/spice-agent/interaction.Broker, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewInteractionBroker): %w", err))
	}
	if daemonInteractionBrokerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewInteractionBroker", daemonInteractionBrokerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonInteractionBroker (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewInteractionBroker): %w", err))
		}
	}
	_ = daemonInteractionBroker
	processResolver, processResolverCleanup, err := func() (process.ExecutableResolver, spicelifecycle.Cleanup, error) {
		if options.Overrides.ProcessResolver.Enabled() {
			return options.Overrides.ProcessResolver.Acquire(ctx)
		}
		return spiceDaemon.ConstructProcessResolver_4d5da368()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean processResolver (github.com/spice-framework/spice-agent/process.ExecutableResolver, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewExecutableResolver): %w", err))
	}
	if processResolverCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewExecutableResolver", processResolverCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean processResolver (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|21:NewExecutableResolver): %w", err))
		}
	}
	_ = processResolver
	daemonRoot, daemonRootCleanup, err := func() (*daemon.Root, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonRoot.Enabled() {
			return options.Overrides.DaemonRoot.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonRoot_3c8cd2a3(daemonRootRegistry)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonRoot (*github.com/spice-framework/spice-agent-coding/internal/daemon.Root, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|7:NewRoot): %w", err))
	}
	if daemonRootCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|7:NewRoot", daemonRootCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonRoot (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|7:NewRoot): %w", err))
		}
	}
	_ = daemonRoot
	sessionStore, sessionStoreCleanup, err := func() (*daemon2.SessionStore, spicelifecycle.Cleanup, error) {
		if options.Overrides.SessionStore.Enabled() {
			return options.Overrides.SessionStore.Acquire(ctx)
		}
		return spiceDaemon.ConstructSessionStore_5ce90ba9(daemonRoot)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean sessionStore (*github.com/spice-framework/spice-agent/daemon.SessionStore, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewSessionStore): %w", err))
	}
	if sessionStoreCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewSessionStore", sessionStoreCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean sessionStore (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewSessionStore): %w", err))
		}
	}
	_ = sessionStore
	operationLedger, operationLedgerCleanup, err := func() (*daemon2.Ledger, spicelifecycle.Cleanup, error) {
		if options.Overrides.OperationLedger.Enabled() {
			return options.Overrides.OperationLedger.Acquire(ctx)
		}
		return spiceDaemon.ConstructOperationLedger_4e34d52a()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean operationLedger (*github.com/spice-framework/spice-agent/daemon.Ledger, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLedger): %w", err))
	}
	if operationLedgerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLedger", operationLedgerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean operationLedger (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLedger): %w", err))
		}
	}
	_ = operationLedger
	serverLimits, serverLimitsCleanup, err := func() (client.Limits, spicelifecycle.Cleanup, error) {
		if options.Overrides.ServerLimits.Enabled() {
			return options.Overrides.ServerLimits.Acquire(ctx)
		}
		return spiceDaemon.ConstructServerLimits_3afc4093()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean serverLimits (github.com/spice-framework/spice-agent/client.Limits, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLimits): %w", err))
	}
	if serverLimitsCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLimits", serverLimitsCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean serverLimits (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewLimits): %w", err))
		}
	}
	_ = serverLimits
	properties, err := spiceDaemon.BindProperties_641bb6f4(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/spice-framework/spice-agent-coding/internal/daemon.Properties for bean Properties (source spice:symbol:v1|type|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:Properties): %w", err))
	}
	_ = properties
	codingConfig, codingConfigCleanup, err := func() (coding.Config, spicelifecycle.Cleanup, error) {
		if options.Overrides.CodingConfig.Enabled() {
			return options.Overrides.CodingConfig.Acquire(ctx)
		}
		return spiceDaemon.ConstructCodingConfig_4bbfc767(properties, daemonRootRegistry)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean codingConfig (github.com/spice-framework/spice-agent-tools-coding.Config, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewCodingConfig): %w", err))
	}
	if codingConfigCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewCodingConfig", codingConfigCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean codingConfig (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewCodingConfig): %w", err))
		}
	}
	_ = codingConfig
	openAIConfig, openAIConfigCleanup, err := func() (openaiprovider.Config, spicelifecycle.Cleanup, error) {
		if options.Overrides.OpenAIConfig.Enabled() {
			return options.Overrides.OpenAIConfig.Acquire(ctx)
		}
		return spiceDaemon.ConstructOpenAIConfig_f13e2cf9(properties)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean openAIConfig (github.com/spice-framework/spice-agent-provider-openai.Config, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewOpenAIConfig): %w", err))
	}
	if openAIConfigCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewOpenAIConfig", openAIConfigCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean openAIConfig (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewOpenAIConfig): %w", err))
		}
	}
	_ = openAIConfig
	runAuthority, runAuthorityCleanup, err := func() (*daemon2.RunAuthority, spicelifecycle.Cleanup, error) {
		if options.Overrides.RunAuthority.Enabled() {
			return options.Overrides.RunAuthority.Acquire(ctx)
		}
		return spiceDaemon.ConstructRunAuthority_af30e6a5(properties)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runAuthority (*github.com/spice-framework/spice-agent/daemon.RunAuthority, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRunAuthority): %w", err))
	}
	if runAuthorityCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRunAuthority", runAuthorityCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runAuthority (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|15:NewRunAuthority): %w", err))
		}
	}
	_ = runAuthority
	definitionSet, definitionSetCleanup, err := func() (daemon2.DefinitionSet, spicelifecycle.Cleanup, error) {
		if options.Overrides.DefinitionSet.Enabled() {
			return options.Overrides.DefinitionSet.Acquire(ctx)
		}
		return spiceDaemon.ConstructDefinitionSet_a8acae3e(properties)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean definitionSet (github.com/spice-framework/spice-agent/daemon.DefinitionSet, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewDefinitionSet): %w", err))
	}
	if definitionSetCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewDefinitionSet", definitionSetCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean definitionSet (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|16:NewDefinitionSet): %w", err))
		}
	}
	_ = definitionSet
	read, readCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Read.Enabled() {
			return options.Overrides.Read.Acquire(ctx)
		}
		return spiceAutoconfigure2.ConstructRead_1b770715(codingConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean read (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead): %w", err))
	}
	if readCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead", readCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean read (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead): %w", err))
		}
	}
	_ = read
	shell, shellCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Shell.Enabled() {
			return options.Overrides.Shell.Acquire(ctx)
		}
		return spiceAutoconfigure2.ConstructShell_a48b269f(codingConfig, processResolver, processLauncher)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean shell (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell): %w", err))
	}
	if shellCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell", shellCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean shell (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell): %w", err))
		}
	}
	_ = shell
	replace, replaceCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Replace.Enabled() {
			return options.Overrides.Replace.Acquire(ctx)
		}
		return spiceAutoconfigure2.ConstructReplace_96382d5b(codingConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean replace (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace): %w", err))
	}
	if replaceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace", replaceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean replace (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace): %w", err))
		}
	}
	_ = replace
	daemonToolDispatcher, daemonToolDispatcherCleanup, err := func() (stage.ToolDispatcher, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonToolDispatcher.Enabled() {
			return options.Overrides.DaemonToolDispatcher.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonToolDispatcher_62bc19b3(map[string]tool.Tool{"read": read, "replace": replace, "shell": shell})
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonToolDispatcher (github.com/spice-framework/spice-agent/stage.ToolDispatcher, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|17:NewToolDispatcher): %w", err))
	}
	if daemonToolDispatcherCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|17:NewToolDispatcher", daemonToolDispatcherCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonToolDispatcher (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|17:NewToolDispatcher): %w", err))
		}
	}
	_ = daemonToolDispatcher
	daemonToolPlanSource, daemonToolPlanSourceCleanup, err := func() (stage.ToolPlanSource, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonToolPlanSource.Enabled() {
			return options.Overrides.DaemonToolPlanSource.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonToolPlanSource_4dd1bcce(daemonToolDispatcher)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonToolPlanSource (github.com/spice-framework/spice-agent/stage.ToolPlanSource, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|17:NewToolPlanSource): %w", err))
	}
	if daemonToolPlanSourceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|17:NewToolPlanSource", daemonToolPlanSourceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonToolPlanSource (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|17:NewToolPlanSource): %w", err))
		}
	}
	_ = daemonToolPlanSource
	openAIModelProvider, openAIModelProviderCleanup, err := func() (model.Provider, spicelifecycle.Cleanup, error) {
		if options.Overrides.OpenAIModelProvider.Enabled() {
			return options.Overrides.OpenAIModelProvider.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructOpenAIModelProvider_2228c855(openAIConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean openAIModelProvider (github.com/spice-framework/spice-agent/model.Provider, source spice:symbol:v1|function|68:github.com/spice-framework/spice-agent-provider-openai/autoconfigure|0:|7:Default): %w", err))
	}
	if openAIModelProviderCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|68:github.com/spice-framework/spice-agent-provider-openai/autoconfigure|0:|7:Default", openAIModelProviderCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean openAIModelProvider (source spice:symbol:v1|function|68:github.com/spice-framework/spice-agent-provider-openai/autoconfigure|0:|7:Default): %w", err))
		}
	}
	_ = openAIModelProvider
	daemonEngine, daemonEngineCleanup, err := func() (*agent.Engine, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonEngine.Enabled() {
			return options.Overrides.DaemonEngine.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonEngine_10b0c974(openAIModelProvider, daemonToolPlanSource, daemonInteractionBroker)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonEngine (*github.com/spice-framework/spice-agent/agent.Engine, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine): %w", err))
	}
	if daemonEngineCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine", daemonEngineCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonEngine (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine): %w", err))
		}
	}
	_ = daemonEngine
	runHost, runHostCleanup, err := func() (*daemon2.RunHost, spicelifecycle.Cleanup, error) {
		if options.Overrides.RunHost.Enabled() {
			return options.Overrides.RunHost.Acquire(ctx)
		}
		return spiceDaemon.ConstructRunHost_4a91e2b0(daemonRoot, daemonEngine, runAuthority, sessionStore, operationLedger, pendingHub, definitionSet, serverLimits)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean runHost (*github.com/spice-framework/spice-agent/daemon.RunHost, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRunHost): %w", err))
	}
	if runHostCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRunHost", runHostCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean runHost (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRunHost): %w", err))
		}
	}
	_ = runHost
	grpcServer, grpcServerCleanup, err := func() (*grpcserver.Server, spicelifecycle.Cleanup, error) {
		if options.Overrides.GrpcServer.Enabled() {
			return options.Overrides.GrpcServer.Acquire(ctx)
		}
		return spiceDaemon.ConstructGrpcServer_97f7cc1f(daemonRoot, endpointToken, runHost, sessionStore, serverBuild)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean grpcServer (*github.com/spice-framework/spice-agent/daemon/grpcserver.Server, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewGRPCServer): %w", err))
	}
	if grpcServerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewGRPCServer", grpcServerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean grpcServer (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewGRPCServer): %w", err))
		}
	}
	_ = grpcServer
	daemonRuntime, daemonRuntimeCleanup, err := func() (*daemon.Runtime, spicelifecycle.Cleanup, error) {
		if options.Overrides.DaemonRuntime.Enabled() {
			return options.Overrides.DaemonRuntime.Acquire(ctx)
		}
		return spiceDaemon.ConstructDaemonRuntime_b0e1ae70(endpointScope, endpointStore, endpointToken, serverBuild, serverProtocol, grpcServer)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean daemonRuntime (*github.com/spice-framework/spice-agent-coding/internal/daemon.Runtime, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRuntime): %w", err))
	}
	if daemonRuntimeCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRuntime", daemonRuntimeCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean daemonRuntime (source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|10:NewRuntime): %w", err))
		}
	}
	_ = daemonRuntime
	return &applicationDependencies{
		pendingHub:              pendingHub,
		serverBuild:             serverBuild,
		daemonRootRegistry:      daemonRootRegistry,
		endpointScope:           endpointScope,
		endpointStore:           endpointStore,
		endpointToken:           endpointToken,
		processLauncher:         processLauncher,
		serverProtocol:          serverProtocol,
		daemonInteractionBroker: daemonInteractionBroker,
		processResolver:         processResolver,
		daemonRoot:              daemonRoot,
		sessionStore:            sessionStore,
		operationLedger:         operationLedger,
		serverLimits:            serverLimits,
		properties:              properties,
		codingConfig:            codingConfig,
		openAIConfig:            openAIConfig,
		runAuthority:            runAuthority,
		definitionSet:           definitionSet,
		read:                    read,
		shell:                   shell,
		replace:                 replace,
		daemonToolDispatcher:    daemonToolDispatcher,
		daemonToolPlanSource:    daemonToolPlanSource,
		openAIModelProvider:     openAIModelProvider,
		daemonEngine:            daemonEngine,
		runHost:                 runHost,
		grpcServer:              grpcServer,
		daemonRuntime:           daemonRuntime,
	}, nil
}
