//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {
	return NewApplicationWithOptions(ctx, ApplicationOptions{Observers: observers})
}

func NewApplicationWithOptions(ctx context.Context, options ApplicationOptions) (*Application, error) {
	if ctx == nil {
		return nil, fmt.Errorf("construct application daemon: context is nil")
	}
	application := &Application{coordinator: spicelifecycle.NewCoordinator()}
	observers := append([]spicelifecycle.Observer(nil), options.Observers...)
	for index, observer := range observers {
		if err := application.coordinator.RegisterObserver(observer); err != nil {
			return nil, fmt.Errorf("register lifecycle observer %d: %w", index, err)
		}
	}
	configurationSchema, err := ConfigurationSchema()
	if err != nil {
		return nil, fmt.Errorf("construct configuration schema for application daemon: %w", err)
	}
	configurationSnapshot, err := spiceconfig.Resolve(
		ctx,
		configurationSchema,
		spiceconfig.Options{
			Profiles:     options.Profiles,
			AllowUnknown: options.AllowUnknownConfiguration,
		},
		options.Sources...,
	)
	if err != nil {
		return nil, fmt.Errorf("resolve configuration for application daemon: %w", err)
	}
	application.shutdownTimeout, err = configurationSnapshot.Duration("spice.shutdown-timeout")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application daemon: %w", err))
	}
	if application.shutdownTimeout <= 0 {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application daemon: duration must be positive"))
	}
	dependencies, err := constructApplicationDependencies(ctx, application, options, configurationSnapshot)
	if err != nil {
		return nil, err
	}
	_ = dependencies
	application.components = Components{
		PendingHub:              dependencies.pendingHub,
		ServerBuild:             dependencies.serverBuild,
		DaemonRootRegistry:      dependencies.daemonRootRegistry,
		EndpointScope:           dependencies.endpointScope,
		EndpointStore:           dependencies.endpointStore,
		EndpointToken:           dependencies.endpointToken,
		ServerProtocol:          dependencies.serverProtocol,
		DaemonInteractionBroker: dependencies.daemonInteractionBroker,
		DaemonRoot:              dependencies.daemonRoot,
		SessionStore:            dependencies.sessionStore,
		OperationLedger:         dependencies.operationLedger,
		ServerLimits:            dependencies.serverLimits,
		Properties:              dependencies.properties,
		CodingConfig:            dependencies.codingConfig,
		OpenAIConfig:            dependencies.openAIConfig,
		RunAuthority:            dependencies.runAuthority,
		DefinitionSet:           dependencies.definitionSet,
		Read:                    dependencies.read,
		Shell:                   dependencies.shell,
		Replace:                 dependencies.replace,
		DaemonToolDispatcher:    dependencies.daemonToolDispatcher,
		DaemonToolPlanSource:    dependencies.daemonToolPlanSource,
		OpenAIModelProvider:     dependencies.openAIModelProvider,
		DaemonEngine:            dependencies.daemonEngine,
		RunHost:                 dependencies.runHost,
		GrpcServer:              dependencies.grpcServer,
		DaemonRuntime:           dependencies.daemonRuntime,
	}
	if _, err := configureGeneratedLifecycle(ctx, application, options, dependencies); err != nil {
		return nil, err
	}
	return application, nil
}
