//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	fmt "fmt"
	strings "strings"
	time "time"

	daemon "github.com/spice-framework/spice-agent-coding/internal/daemon"
	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	spiceDaemon "github.com/spice-framework/spice-agent-coding/internal/spicegen/daemon/sources/internal_/daemon"
	openaiprovider "github.com/spice-framework/spice-agent-provider-openai"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	agent "github.com/spice-framework/spice-agent/agent"
	client "github.com/spice-framework/spice-agent/client"
	daemon2 "github.com/spice-framework/spice-agent/daemon"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	grpcserver "github.com/spice-framework/spice-agent/daemon/grpcserver"
	interaction "github.com/spice-framework/spice-agent/interaction"
	model "github.com/spice-framework/spice-agent/model"
	stage "github.com/spice-framework/spice-agent/stage"
	tool "github.com/spice-framework/spice-agent/tool"
	spicebean "github.com/spice-framework/spice/bean"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

const TargetID = spiceDaemon.ApplicationTargetDaemon_7041e896

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// PendingHub is bean "pendingHub".
	PendingHub *daemon2.PendingHub
	// ServerBuild is bean "serverBuild".
	ServerBuild client.Build
	// DaemonRootRegistry is bean "daemonRootRegistry".
	DaemonRootRegistry daemonprocess.RootRegistry
	// EndpointScope is bean "endpointScope".
	EndpointScope endpoint.UserScope
	// EndpointStore is bean "endpointStore".
	EndpointStore *endpoint.Store
	// EndpointToken is bean "endpointToken".
	EndpointToken endpoint.Token
	// ServerProtocol is bean "serverProtocol".
	ServerProtocol client.ProtocolVersion
	// DaemonInteractionBroker is bean "daemonInteractionBroker".
	DaemonInteractionBroker interaction.Broker
	// DaemonRoot is bean "daemonRoot".
	DaemonRoot *daemon.Root
	// SessionStore is bean "sessionStore".
	SessionStore *daemon2.SessionStore
	// OperationLedger is bean "operationLedger".
	OperationLedger *daemon2.Ledger
	// ServerLimits is bean "serverLimits".
	ServerLimits client.Limits
	// Properties is bean "Properties".
	Properties daemon.Properties
	// CodingConfig is bean "codingConfig".
	CodingConfig coding.Config
	// OpenAIConfig is bean "openAIConfig".
	OpenAIConfig openaiprovider.Config
	// RunAuthority is bean "runAuthority".
	RunAuthority *daemon2.RunAuthority
	// DefinitionSet is bean "definitionSet".
	DefinitionSet daemon2.DefinitionSet
	// Read is bean "read".
	Read tool.Tool
	// Shell is bean "shell".
	Shell tool.Tool
	// Replace is bean "replace".
	Replace tool.Tool
	// DaemonToolDispatcher is bean "daemonToolDispatcher".
	DaemonToolDispatcher stage.ToolDispatcher
	// DaemonToolPlanSource is bean "daemonToolPlanSource".
	DaemonToolPlanSource stage.ToolPlanSource
	// OpenAIModelProvider is bean "openAIModelProvider".
	OpenAIModelProvider model.Provider
	// DaemonEngine is bean "daemonEngine".
	DaemonEngine *agent.Engine
	// RunHost is bean "runHost".
	RunHost *daemon2.RunHost
	// GrpcServer is bean "grpcServer".
	GrpcServer *grpcserver.Server
	// DaemonRuntime is bean "daemonRuntime".
	DaemonRuntime *daemon.Runtime
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// PendingHub replaces bean "pendingHub".
	PendingHub spicebean.Override[*daemon2.PendingHub]
	// ServerBuild replaces bean "serverBuild".
	ServerBuild spicebean.Override[client.Build]
	// DaemonRootRegistry replaces bean "daemonRootRegistry".
	DaemonRootRegistry spicebean.Override[daemonprocess.RootRegistry]
	// EndpointScope replaces bean "endpointScope".
	EndpointScope spicebean.Override[endpoint.UserScope]
	// EndpointStore replaces bean "endpointStore".
	EndpointStore spicebean.Override[*endpoint.Store]
	// EndpointToken replaces bean "endpointToken".
	EndpointToken spicebean.Override[endpoint.Token]
	// ServerProtocol replaces bean "serverProtocol".
	ServerProtocol spicebean.Override[client.ProtocolVersion]
	// DaemonInteractionBroker replaces bean "daemonInteractionBroker".
	DaemonInteractionBroker spicebean.Override[interaction.Broker]
	// DaemonRoot replaces bean "daemonRoot".
	DaemonRoot spicebean.Override[*daemon.Root]
	// SessionStore replaces bean "sessionStore".
	SessionStore spicebean.Override[*daemon2.SessionStore]
	// OperationLedger replaces bean "operationLedger".
	OperationLedger spicebean.Override[*daemon2.Ledger]
	// ServerLimits replaces bean "serverLimits".
	ServerLimits spicebean.Override[client.Limits]
	// CodingConfig replaces bean "codingConfig".
	CodingConfig spicebean.Override[coding.Config]
	// OpenAIConfig replaces bean "openAIConfig".
	OpenAIConfig spicebean.Override[openaiprovider.Config]
	// RunAuthority replaces bean "runAuthority".
	RunAuthority spicebean.Override[*daemon2.RunAuthority]
	// DefinitionSet replaces bean "definitionSet".
	DefinitionSet spicebean.Override[daemon2.DefinitionSet]
	// Read replaces bean "read".
	Read spicebean.Override[tool.Tool]
	// Shell replaces bean "shell".
	Shell spicebean.Override[tool.Tool]
	// Replace replaces bean "replace".
	Replace spicebean.Override[tool.Tool]
	// DaemonToolDispatcher replaces bean "daemonToolDispatcher".
	DaemonToolDispatcher spicebean.Override[stage.ToolDispatcher]
	// DaemonToolPlanSource replaces bean "daemonToolPlanSource".
	DaemonToolPlanSource spicebean.Override[stage.ToolPlanSource]
	// OpenAIModelProvider replaces bean "openAIModelProvider".
	OpenAIModelProvider spicebean.Override[model.Provider]
	// DaemonEngine replaces bean "daemonEngine".
	DaemonEngine spicebean.Override[*agent.Engine]
	// RunHost replaces bean "runHost".
	RunHost spicebean.Override[*daemon2.RunHost]
	// GrpcServer replaces bean "grpcServer".
	GrpcServer spicebean.Override[*grpcserver.Server]
	// DaemonRuntime replaces bean "daemonRuntime".
	DaemonRuntime spicebean.Override[*daemon.Runtime]
}

// BeanOverrideLayer is one named immutable override composition layer.
// Layers are applied in order; a later layer deliberately replaces an earlier value.
type BeanOverrideLayer struct {
	Name      string
	Overrides BeanOverrides
}

// ComposeBeanOverrides validates and deterministically composes named layers.
// It never mutates a running application or performs runtime bean lookup.
func ComposeBeanOverrides(layers ...BeanOverrideLayer) (BeanOverrides, error) {
	result := BeanOverrides{}
	seen := make(map[string]int, len(layers))
	for index, layer := range layers {
		if layer.Name == "" || strings.TrimSpace(layer.Name) != layer.Name {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %d requires a non-empty name without surrounding whitespace", index)
		}
		if previous, duplicate := seen[layer.Name]; duplicate {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %q repeats layer %d", layer.Name, previous)
		}
		seen[layer.Name] = index
		if layer.Overrides.PendingHub.Enabled() {
			result.PendingHub = layer.Overrides.PendingHub
		}
		if layer.Overrides.ServerBuild.Enabled() {
			result.ServerBuild = layer.Overrides.ServerBuild
		}
		if layer.Overrides.DaemonRootRegistry.Enabled() {
			result.DaemonRootRegistry = layer.Overrides.DaemonRootRegistry
		}
		if layer.Overrides.EndpointScope.Enabled() {
			result.EndpointScope = layer.Overrides.EndpointScope
		}
		if layer.Overrides.EndpointStore.Enabled() {
			result.EndpointStore = layer.Overrides.EndpointStore
		}
		if layer.Overrides.EndpointToken.Enabled() {
			result.EndpointToken = layer.Overrides.EndpointToken
		}
		if layer.Overrides.ServerProtocol.Enabled() {
			result.ServerProtocol = layer.Overrides.ServerProtocol
		}
		if layer.Overrides.DaemonInteractionBroker.Enabled() {
			result.DaemonInteractionBroker = layer.Overrides.DaemonInteractionBroker
		}
		if layer.Overrides.DaemonRoot.Enabled() {
			result.DaemonRoot = layer.Overrides.DaemonRoot
		}
		if layer.Overrides.SessionStore.Enabled() {
			result.SessionStore = layer.Overrides.SessionStore
		}
		if layer.Overrides.OperationLedger.Enabled() {
			result.OperationLedger = layer.Overrides.OperationLedger
		}
		if layer.Overrides.ServerLimits.Enabled() {
			result.ServerLimits = layer.Overrides.ServerLimits
		}
		if layer.Overrides.CodingConfig.Enabled() {
			result.CodingConfig = layer.Overrides.CodingConfig
		}
		if layer.Overrides.OpenAIConfig.Enabled() {
			result.OpenAIConfig = layer.Overrides.OpenAIConfig
		}
		if layer.Overrides.RunAuthority.Enabled() {
			result.RunAuthority = layer.Overrides.RunAuthority
		}
		if layer.Overrides.DefinitionSet.Enabled() {
			result.DefinitionSet = layer.Overrides.DefinitionSet
		}
		if layer.Overrides.Read.Enabled() {
			result.Read = layer.Overrides.Read
		}
		if layer.Overrides.Shell.Enabled() {
			result.Shell = layer.Overrides.Shell
		}
		if layer.Overrides.Replace.Enabled() {
			result.Replace = layer.Overrides.Replace
		}
		if layer.Overrides.DaemonToolDispatcher.Enabled() {
			result.DaemonToolDispatcher = layer.Overrides.DaemonToolDispatcher
		}
		if layer.Overrides.DaemonToolPlanSource.Enabled() {
			result.DaemonToolPlanSource = layer.Overrides.DaemonToolPlanSource
		}
		if layer.Overrides.OpenAIModelProvider.Enabled() {
			result.OpenAIModelProvider = layer.Overrides.OpenAIModelProvider
		}
		if layer.Overrides.DaemonEngine.Enabled() {
			result.DaemonEngine = layer.Overrides.DaemonEngine
		}
		if layer.Overrides.RunHost.Enabled() {
			result.RunHost = layer.Overrides.RunHost
		}
		if layer.Overrides.GrpcServer.Enabled() {
			result.GrpcServer = layer.Overrides.GrpcServer
		}
		if layer.Overrides.DaemonRuntime.Enabled() {
			result.DaemonRuntime = layer.Overrides.DaemonRuntime
		}
	}
	return result, nil
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	Observers                 []spicelifecycle.Observer
}
