//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	spiceconfig "github.com/spice-framework/spice/config"
)

func ConfigurationSchema() (spiceconfig.Schema, error) {
	return spiceconfig.NewSchema(
		spiceconfig.Property{
			Key:         "agent.openai.api-key",
			Kind:        spiceconfig.KindString,
			Environment: "OPENAI_API_KEY",
			Required:    true,
			Secret:      true,
		},
		spiceconfig.Property{
			Key:         "agent.openai.base-url",
			Kind:        spiceconfig.KindString,
			Environment: "OPENAI_BASE_URL",
			Default:     "https://api.openai.com/v1",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.openai.organization",
			Kind:        spiceconfig.KindString,
			Environment: "OPENAI_ORGANIZATION",
		},
		spiceconfig.Property{
			Key:         "agent.openai.project",
			Kind:        spiceconfig.KindString,
			Environment: "OPENAI_PROJECT",
		},
		spiceconfig.Property{
			Key:         "agent.openai.timeout",
			Kind:        spiceconfig.KindDuration,
			Environment: "OPENAI_TIMEOUT",
			Default:     "2m",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.openai.max-retries",
			Kind:        spiceconfig.KindInteger,
			Environment: "OPENAI_MAX_RETRIES",
			Default:     "0",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.model",
			Kind:        spiceconfig.KindString,
			Environment: "OPENAI_MODEL",
			Required:    true,
		},
		spiceconfig.Property{
			Key:         "agent.workspace",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_AGENT_WORKSPACE",
			Default:     ".",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "agent.run-authority-directory",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_AGENT_RUN_AUTHORITY_DIRECTORY",
		},
		spiceconfig.Property{
			Key:         "spice.shutdown-timeout",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_SHUTDOWN_TIMEOUT",
			Default:     "10s",
			HasDefault:  true,
		},
	)
}
