//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: cmd/spice-agent/application.go:17

package spicegen

// ApplicationTargetSpiceAgent_89bc7a6d identifies the generated target selected by spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/cmd/spice-agent|0:|4:main.
const ApplicationTargetSpiceAgent_89bc7a6d = "spice_agent"
