//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	spiceconfig "github.com/spice-framework/spice/config"
)

func ConfigurationSchema() (spiceconfig.Schema, error) {
	return spiceconfig.NewSchema(
		spiceconfig.Property{
			Key:         "agent.workspace",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_AGENT_WORKSPACE",
			Default:     ".",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:        "agent.terminal.mode",
			Kind:       spiceconfig.KindString,
			Default:    "managed",
			HasDefault: true,
		},
		spiceconfig.Property{
			Key:  "agent.terminal.endpoint",
			Kind: spiceconfig.KindString,
		},
		spiceconfig.Property{
			Key:         "agent.terminal.accessible",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_AGENT_TERMINAL_ACCESSIBLE",
			Default:     "false",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "spice.logging.format",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_LOGGING_FORMAT",
			Default:     "json",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "spice.logging.level",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_LOGGING_LEVEL",
			Default:     "info",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "spice.logging.levels",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_LOGGING_LEVELS",
			Default:     "",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "spice.logging.add-source",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_LOGGING_ADD_SOURCE",
			Default:     "false",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "spice.shutdown-timeout",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_SHUTDOWN_TIMEOUT",
			Default:     "10s",
			HasDefault:  true,
		},
	)
}
