//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	fmt "fmt"
	strings "strings"
	time "time"

	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	spiceentrypoint "github.com/spice-framework/spice-agent-coding/internal/spicegen/spice_agent/sources/cmd/spice-agent"
	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	tuisession "github.com/spice-framework/spice-agent-coding/internal/tuisession"
	agenttui "github.com/spice-framework/spice-agent-tui"
	client "github.com/spice-framework/spice-agent/client"
	localclient "github.com/spice-framework/spice-agent/client/localclient"
	managed "github.com/spice-framework/spice-agent/client/managed"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	spicebean "github.com/spice-framework/spice/bean"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

const TargetID = spiceentrypoint.ApplicationTargetSpiceAgent_89bc7a6d

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// DarkTheme is bean "darkTheme".
	DarkTheme agenttui.Theme
	// QuitKeyBinding is bean "quitKeyBinding".
	QuitKeyBinding agenttui.KeyBinding
	// OsTerminalIO is bean "osTerminalIO".
	OsTerminalIO agenttui.TerminalIO
	// CancelKeyBinding is bean "cancelKeyBinding".
	CancelKeyBinding agenttui.KeyBinding
	// FixedRenderer is bean "fixedRenderer".
	FixedRenderer agenttui.Renderer
	// SubmitKeyBinding is bean "submitKeyBinding".
	SubmitKeyBinding agenttui.KeyBinding
	// ConnectingView is bean "connectingView".
	ConnectingView agenttui.ViewData
	// RespondKeyBinding is bean "respondKeyBinding".
	RespondKeyBinding agenttui.KeyBinding
	// TerminalConfig is bean "terminalConfig".
	TerminalConfig agenttui.TerminalConfig
	// BackspaceKeyBinding is bean "backspaceKeyBinding".
	BackspaceKeyBinding agenttui.KeyBinding
	// CursorEndKeyBinding is bean "cursorEndKeyBinding".
	CursorEndKeyBinding agenttui.KeyBinding
	// CursorLeftKeyBinding is bean "cursorLeftKeyBinding".
	CursorLeftKeyBinding agenttui.KeyBinding
	// CursorRightKeyBinding is bean "cursorRightKeyBinding".
	CursorRightKeyBinding agenttui.KeyBinding
	// CursorStartKeyBinding is bean "cursorStartKeyBinding".
	CursorStartKeyBinding agenttui.KeyBinding
	// HistoryNextKeyBinding is bean "historyNextKeyBinding".
	HistoryNextKeyBinding agenttui.KeyBinding
	// HistoryPreviousKeyBinding is bean "historyPreviousKeyBinding".
	HistoryPreviousKeyBinding agenttui.KeyBinding
	// TerminalDefinition is bean "terminalDefinition".
	TerminalDefinition client.DefinitionRef
	// TerminalClientBuild is bean "terminalClientBuild".
	TerminalClientBuild client.Build
	// TerminalClientLimits is bean "terminalClientLimits".
	TerminalClientLimits client.Limits
	// TerminalDaemonStarter is bean "terminalDaemonStarter".
	TerminalDaemonStarter *daemonprocess.Starter
	// TerminalEndpointScope is bean "terminalEndpointScope".
	TerminalEndpointScope endpoint.UserScope
	// TerminalEndpointStore is bean "terminalEndpointStore".
	TerminalEndpointStore *endpoint.Store
	// TerminalStartupLock is bean "terminalStartupLock".
	TerminalStartupLock *localclient.StartupLock
	// TerminalInitialStatus is bean "terminalInitialStatus".
	TerminalInitialStatus agenttui.StatusState
	// TerminalClientProtocol is bean "terminalClientProtocol".
	TerminalClientProtocol client.ProtocolRange
	// TerminalIdentifierSource is bean "terminalIdentifierSource".
	TerminalIdentifierSource tuisession.IdentifierSource
	// TerminalManagedDiscovery is bean "terminalManagedDiscovery".
	TerminalManagedDiscovery *localclient.Discovery
	// TerminalManagedConnector is bean "terminalManagedConnector".
	TerminalManagedConnector *managed.Connector
	// TerminalInitializeRequest is bean "terminalInitializeRequest".
	TerminalInitializeRequest client.InitializeRequest
	// Properties is bean "Properties".
	Properties terminal.Properties
	// TerminalWorkspace is bean "terminalWorkspace".
	TerminalWorkspace agenttui.WorkspaceState
	// TerminalSessionConfig is bean "terminalSessionConfig".
	TerminalSessionConfig tuisession.Config
	// TerminalClientConnector is bean "terminalClientConnector".
	TerminalClientConnector client.Connector
	// TerminalSession is bean "terminalSession".
	TerminalSession agenttui.Session
	// TerminalShell is bean "terminalShell".
	TerminalShell agenttui.Shell
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// DarkTheme replaces bean "darkTheme".
	DarkTheme spicebean.Override[agenttui.Theme]
	// QuitKeyBinding replaces bean "quitKeyBinding".
	QuitKeyBinding spicebean.Override[agenttui.KeyBinding]
	// OsTerminalIO replaces bean "osTerminalIO".
	OsTerminalIO spicebean.Override[agenttui.TerminalIO]
	// CancelKeyBinding replaces bean "cancelKeyBinding".
	CancelKeyBinding spicebean.Override[agenttui.KeyBinding]
	// FixedRenderer replaces bean "fixedRenderer".
	FixedRenderer spicebean.Override[agenttui.Renderer]
	// SubmitKeyBinding replaces bean "submitKeyBinding".
	SubmitKeyBinding spicebean.Override[agenttui.KeyBinding]
	// ConnectingView replaces bean "connectingView".
	ConnectingView spicebean.Override[agenttui.ViewData]
	// RespondKeyBinding replaces bean "respondKeyBinding".
	RespondKeyBinding spicebean.Override[agenttui.KeyBinding]
	// TerminalConfig replaces bean "terminalConfig".
	TerminalConfig spicebean.Override[agenttui.TerminalConfig]
	// BackspaceKeyBinding replaces bean "backspaceKeyBinding".
	BackspaceKeyBinding spicebean.Override[agenttui.KeyBinding]
	// CursorEndKeyBinding replaces bean "cursorEndKeyBinding".
	CursorEndKeyBinding spicebean.Override[agenttui.KeyBinding]
	// CursorLeftKeyBinding replaces bean "cursorLeftKeyBinding".
	CursorLeftKeyBinding spicebean.Override[agenttui.KeyBinding]
	// CursorRightKeyBinding replaces bean "cursorRightKeyBinding".
	CursorRightKeyBinding spicebean.Override[agenttui.KeyBinding]
	// CursorStartKeyBinding replaces bean "cursorStartKeyBinding".
	CursorStartKeyBinding spicebean.Override[agenttui.KeyBinding]
	// HistoryNextKeyBinding replaces bean "historyNextKeyBinding".
	HistoryNextKeyBinding spicebean.Override[agenttui.KeyBinding]
	// HistoryPreviousKeyBinding replaces bean "historyPreviousKeyBinding".
	HistoryPreviousKeyBinding spicebean.Override[agenttui.KeyBinding]
	// TerminalDefinition replaces bean "terminalDefinition".
	TerminalDefinition spicebean.Override[client.DefinitionRef]
	// TerminalClientBuild replaces bean "terminalClientBuild".
	TerminalClientBuild spicebean.Override[client.Build]
	// TerminalClientLimits replaces bean "terminalClientLimits".
	TerminalClientLimits spicebean.Override[client.Limits]
	// TerminalDaemonStarter replaces bean "terminalDaemonStarter".
	TerminalDaemonStarter spicebean.Override[*daemonprocess.Starter]
	// TerminalEndpointScope replaces bean "terminalEndpointScope".
	TerminalEndpointScope spicebean.Override[endpoint.UserScope]
	// TerminalEndpointStore replaces bean "terminalEndpointStore".
	TerminalEndpointStore spicebean.Override[*endpoint.Store]
	// TerminalStartupLock replaces bean "terminalStartupLock".
	TerminalStartupLock spicebean.Override[*localclient.StartupLock]
	// TerminalInitialStatus replaces bean "terminalInitialStatus".
	TerminalInitialStatus spicebean.Override[agenttui.StatusState]
	// TerminalClientProtocol replaces bean "terminalClientProtocol".
	TerminalClientProtocol spicebean.Override[client.ProtocolRange]
	// TerminalIdentifierSource replaces bean "terminalIdentifierSource".
	TerminalIdentifierSource spicebean.Override[tuisession.IdentifierSource]
	// TerminalManagedDiscovery replaces bean "terminalManagedDiscovery".
	TerminalManagedDiscovery spicebean.Override[*localclient.Discovery]
	// TerminalManagedConnector replaces bean "terminalManagedConnector".
	TerminalManagedConnector spicebean.Override[*managed.Connector]
	// TerminalInitializeRequest replaces bean "terminalInitializeRequest".
	TerminalInitializeRequest spicebean.Override[client.InitializeRequest]
	// TerminalWorkspace replaces bean "terminalWorkspace".
	TerminalWorkspace spicebean.Override[agenttui.WorkspaceState]
	// TerminalSessionConfig replaces bean "terminalSessionConfig".
	TerminalSessionConfig spicebean.Override[tuisession.Config]
	// TerminalClientConnector replaces bean "terminalClientConnector".
	TerminalClientConnector spicebean.Override[client.Connector]
	// TerminalSession replaces bean "terminalSession".
	TerminalSession spicebean.Override[agenttui.Session]
	// TerminalShell replaces bean "terminalShell".
	TerminalShell spicebean.Override[agenttui.Shell]
}

// BeanOverrideLayer is one named immutable override composition layer.
// Layers are applied in order; a later layer deliberately replaces an earlier value.
type BeanOverrideLayer struct {
	Name      string
	Overrides BeanOverrides
}

// ComposeBeanOverrides validates and deterministically composes named layers.
// It never mutates a running application or performs runtime bean lookup.
func ComposeBeanOverrides(layers ...BeanOverrideLayer) (BeanOverrides, error) {
	result := BeanOverrides{}
	seen := make(map[string]int, len(layers))
	for index, layer := range layers {
		if layer.Name == "" || strings.TrimSpace(layer.Name) != layer.Name {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %d requires a non-empty name without surrounding whitespace", index)
		}
		if previous, duplicate := seen[layer.Name]; duplicate {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %q repeats layer %d", layer.Name, previous)
		}
		seen[layer.Name] = index
		if layer.Overrides.DarkTheme.Enabled() {
			result.DarkTheme = layer.Overrides.DarkTheme
		}
		if layer.Overrides.QuitKeyBinding.Enabled() {
			result.QuitKeyBinding = layer.Overrides.QuitKeyBinding
		}
		if layer.Overrides.OsTerminalIO.Enabled() {
			result.OsTerminalIO = layer.Overrides.OsTerminalIO
		}
		if layer.Overrides.CancelKeyBinding.Enabled() {
			result.CancelKeyBinding = layer.Overrides.CancelKeyBinding
		}
		if layer.Overrides.FixedRenderer.Enabled() {
			result.FixedRenderer = layer.Overrides.FixedRenderer
		}
		if layer.Overrides.SubmitKeyBinding.Enabled() {
			result.SubmitKeyBinding = layer.Overrides.SubmitKeyBinding
		}
		if layer.Overrides.ConnectingView.Enabled() {
			result.ConnectingView = layer.Overrides.ConnectingView
		}
		if layer.Overrides.RespondKeyBinding.Enabled() {
			result.RespondKeyBinding = layer.Overrides.RespondKeyBinding
		}
		if layer.Overrides.TerminalConfig.Enabled() {
			result.TerminalConfig = layer.Overrides.TerminalConfig
		}
		if layer.Overrides.BackspaceKeyBinding.Enabled() {
			result.BackspaceKeyBinding = layer.Overrides.BackspaceKeyBinding
		}
		if layer.Overrides.CursorEndKeyBinding.Enabled() {
			result.CursorEndKeyBinding = layer.Overrides.CursorEndKeyBinding
		}
		if layer.Overrides.CursorLeftKeyBinding.Enabled() {
			result.CursorLeftKeyBinding = layer.Overrides.CursorLeftKeyBinding
		}
		if layer.Overrides.CursorRightKeyBinding.Enabled() {
			result.CursorRightKeyBinding = layer.Overrides.CursorRightKeyBinding
		}
		if layer.Overrides.CursorStartKeyBinding.Enabled() {
			result.CursorStartKeyBinding = layer.Overrides.CursorStartKeyBinding
		}
		if layer.Overrides.HistoryNextKeyBinding.Enabled() {
			result.HistoryNextKeyBinding = layer.Overrides.HistoryNextKeyBinding
		}
		if layer.Overrides.HistoryPreviousKeyBinding.Enabled() {
			result.HistoryPreviousKeyBinding = layer.Overrides.HistoryPreviousKeyBinding
		}
		if layer.Overrides.TerminalDefinition.Enabled() {
			result.TerminalDefinition = layer.Overrides.TerminalDefinition
		}
		if layer.Overrides.TerminalClientBuild.Enabled() {
			result.TerminalClientBuild = layer.Overrides.TerminalClientBuild
		}
		if layer.Overrides.TerminalClientLimits.Enabled() {
			result.TerminalClientLimits = layer.Overrides.TerminalClientLimits
		}
		if layer.Overrides.TerminalDaemonStarter.Enabled() {
			result.TerminalDaemonStarter = layer.Overrides.TerminalDaemonStarter
		}
		if layer.Overrides.TerminalEndpointScope.Enabled() {
			result.TerminalEndpointScope = layer.Overrides.TerminalEndpointScope
		}
		if layer.Overrides.TerminalEndpointStore.Enabled() {
			result.TerminalEndpointStore = layer.Overrides.TerminalEndpointStore
		}
		if layer.Overrides.TerminalStartupLock.Enabled() {
			result.TerminalStartupLock = layer.Overrides.TerminalStartupLock
		}
		if layer.Overrides.TerminalInitialStatus.Enabled() {
			result.TerminalInitialStatus = layer.Overrides.TerminalInitialStatus
		}
		if layer.Overrides.TerminalClientProtocol.Enabled() {
			result.TerminalClientProtocol = layer.Overrides.TerminalClientProtocol
		}
		if layer.Overrides.TerminalIdentifierSource.Enabled() {
			result.TerminalIdentifierSource = layer.Overrides.TerminalIdentifierSource
		}
		if layer.Overrides.TerminalManagedDiscovery.Enabled() {
			result.TerminalManagedDiscovery = layer.Overrides.TerminalManagedDiscovery
		}
		if layer.Overrides.TerminalManagedConnector.Enabled() {
			result.TerminalManagedConnector = layer.Overrides.TerminalManagedConnector
		}
		if layer.Overrides.TerminalInitializeRequest.Enabled() {
			result.TerminalInitializeRequest = layer.Overrides.TerminalInitializeRequest
		}
		if layer.Overrides.TerminalWorkspace.Enabled() {
			result.TerminalWorkspace = layer.Overrides.TerminalWorkspace
		}
		if layer.Overrides.TerminalSessionConfig.Enabled() {
			result.TerminalSessionConfig = layer.Overrides.TerminalSessionConfig
		}
		if layer.Overrides.TerminalClientConnector.Enabled() {
			result.TerminalClientConnector = layer.Overrides.TerminalClientConnector
		}
		if layer.Overrides.TerminalSession.Enabled() {
			result.TerminalSession = layer.Overrides.TerminalSession
		}
		if layer.Overrides.TerminalShell.Enabled() {
			result.TerminalShell = layer.Overrides.TerminalShell
		}
	}
	return result, nil
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	Observers                 []spicelifecycle.Observer
}
