package main

import (
	"bufio"
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"

	commonv1 "github.com/spice-framework/spice-agent/common/v1"
	enginev1 "github.com/spice-framework/spice-agent/engine/v1"
	pluginv1 "github.com/spice-framework/spice-agent/plugin/v1"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	modulePath      = "github.com/spice-framework/spice-agent-coding"
	noticesPath     = "THIRD_PARTY_NOTICES.md"
	descriptorsPath = "protocol-descriptors.pb"
)

// releaseAssetsCommand owns deterministic release-asset rendering.
type releaseAssetsCommand struct{}

func (command releaseAssetsCommand) run(arguments []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet("releaseassets", flag.ContinueOnError)
	flags.SetOutput(stderr)
	check := flags.Bool("check", false, "verify committed release assets without writing")
	if err := flags.Parse(arguments); err != nil || flags.NArg() != 0 {
		return 2
	}
	root, err := command.repositoryRoot()
	if err == nil {
		err = command.apply(root, *check)
	}
	if err != nil {
		if _, writeErr := fmt.Fprintln(stderr, err); writeErr != nil {
			return 1
		}
		return 1
	}
	if *check {
		_, err = fmt.Fprintln(stdout, "release assets are current")
	} else {
		_, err = fmt.Fprintln(stdout, "release assets updated")
	}
	if err != nil {
		return 1
	}
	return 0
}

func (command releaseAssetsCommand) apply(root string, check bool) error {
	notices, err := command.renderNotices(root)
	if err != nil {
		return err
	}
	descriptors, err := command.renderDescriptors()
	if err != nil {
		return err
	}
	assets := []asset{
		{path: noticesPath, content: notices, mode: 0o644},
		{path: descriptorsPath, content: descriptors, mode: 0o644},
	}
	for _, current := range assets {
		path := filepath.Join(root, current.path)
		if check {
			committed, readErr := os.ReadFile(path) // #nosec G304 -- fixed repository-owned path.
			if readErr != nil {
				return fmt.Errorf("read release asset %s: %w", current.path, readErr)
			}
			if !bytes.Equal(committed, current.content) {
				return fmt.Errorf("release asset %s is stale; run go run ./internal/releaseassets", current.path)
			}
			continue
		}
		if err = os.WriteFile(path, current.content, current.mode); err != nil { // #nosec G306 -- public release payload.
			return fmt.Errorf("write release asset %s: %w", current.path, err)
		}
	}
	return nil
}

func (command releaseAssetsCommand) renderNotices(root string) ([]byte, error) {
	modules, err := command.parseVendorModules(filepath.Join(root, "vendor", "modules.txt"))
	if err != nil {
		return nil, err
	}
	var output strings.Builder
	output.WriteString("<!-- Code generated by go run ./internal/releaseassets; DO NOT EDIT. -->\n")
	output.WriteString("# Third-Party Notices\n\n")
	output.WriteString("The Spice Agent distribution includes the following vendored Go modules. ")
	output.WriteString("License and notice text is copied byte-for-byte apart from LF normalization and indentation.\n\n")
	for _, module := range modules {
		files, fileErr := command.moduleLicenseFiles(root, module.path)
		if fileErr != nil {
			return nil, fileErr
		}
		fmt.Fprintf(&output, "## `%s` `%s`\n\n", module.path, module.version)
		fmt.Fprintf(&output, "Source: https://%s\n\n", module.path)
		for _, file := range files {
			relative, relErr := filepath.Rel(root, file)
			if relErr != nil {
				return nil, relErr
			}
			content, readErr := os.ReadFile(file) // #nosec G304 -- confined to validated vendor module root.
			if readErr != nil {
				return nil, fmt.Errorf("read license for %s: %w", module.path, readErr)
			}
			fmt.Fprintf(&output, "### `%s`\n\n", filepath.ToSlash(relative))
			command.writeIndented(&output, command.normalizeText(content))
			output.WriteByte('\n')
		}
	}
	return []byte(strings.TrimRight(output.String(), "\n") + "\n"), nil
}

func (command releaseAssetsCommand) parseVendorModules(path string) ([]moduleSelection, error) {
	content, err := os.ReadFile(path) // #nosec G304 -- fixed vendor/modules.txt path.
	if err != nil {
		return nil, fmt.Errorf("read vendor modules: %w", err)
	}
	seen := make(map[string]struct{})
	var result []moduleSelection
	scanner := bufio.NewScanner(bytes.NewReader(content))
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) < 3 || fields[0] != "#" || !strings.HasPrefix(fields[2], "v") {
			continue
		}
		if err = command.validateModulePath(fields[1]); err != nil {
			return nil, fmt.Errorf("vendor modules: %w", err)
		}
		if _, duplicate := seen[fields[1]]; duplicate {
			return nil, fmt.Errorf("vendor module %s is duplicated", fields[1])
		}
		seen[fields[1]] = struct{}{}
		result = append(result, moduleSelection{path: fields[1], version: fields[2]})
	}
	if err = scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan vendor modules: %w", err)
	}
	if len(result) == 0 {
		return nil, errors.New("vendor modules contains no versioned modules")
	}
	slices.SortFunc(result, func(left, right moduleSelection) int {
		return strings.Compare(left.path, right.path)
	})
	return result, nil
}

func (command releaseAssetsCommand) moduleLicenseFiles(root, module string) ([]string, error) {
	if err := command.validateModulePath(module); err != nil {
		return nil, err
	}
	moduleRoot := filepath.Join(root, "vendor", filepath.FromSlash(module))
	vendorRoot := filepath.Join(root, "vendor")
	relative, err := filepath.Rel(vendorRoot, moduleRoot)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return nil, fmt.Errorf("module %s escapes vendor root", module)
	}
	entries, err := os.ReadDir(moduleRoot) // #nosec G304 -- module root is confined above.
	if err != nil {
		return nil, fmt.Errorf("read vendor module %s: %w", module, err)
	}
	var result []string
	for _, entry := range entries {
		upper := strings.ToUpper(entry.Name())
		if entry.Type().IsRegular() &&
			(strings.HasPrefix(upper, "LICENSE") || strings.HasPrefix(upper, "COPYING") || strings.HasPrefix(upper, "NOTICE")) {
			result = append(result, filepath.Join(moduleRoot, entry.Name()))
		}
	}
	slices.Sort(result)
	if len(result) == 0 {
		return nil, fmt.Errorf("vendor module %s has no root license or notice file", module)
	}
	return result, nil
}

func (releaseAssetsCommand) validateModulePath(module string) error {
	if module == "" || strings.TrimSpace(module) != module || strings.ContainsAny(module, "\\:") ||
		strings.HasPrefix(module, "/") || path.Clean(module) != module {
		return fmt.Errorf("module path %q is invalid", module)
	}
	for component := range strings.SplitSeq(module, "/") {
		if component == "" || component == "." || component == ".." {
			return fmt.Errorf("module path %q is invalid", module)
		}
	}
	return nil
}

func (releaseAssetsCommand) normalizeText(content []byte) string {
	result := strings.ReplaceAll(string(content), "\r\n", "\n")
	result = strings.ReplaceAll(result, "\r", "\n")
	return strings.TrimRight(result, "\n") + "\n"
}

func (releaseAssetsCommand) writeIndented(output *strings.Builder, content string) {
	for line := range strings.SplitSeq(content, "\n") {
		if line == "" {
			output.WriteByte('\n')
			continue
		}
		output.WriteString("    ")
		output.WriteString(line)
		output.WriteByte('\n')
	}
}

func (command releaseAssetsCommand) renderDescriptors() ([]byte, error) {
	seen := make(map[string]protoreflect.FileDescriptor)
	for _, file := range []protoreflect.FileDescriptor{
		commonv1.File_spice_agent_common_v1_common_proto,
		enginev1.File_spice_agent_engine_v1_engine_proto,
		pluginv1.File_spice_agent_plugin_v1_plugin_proto,
	} {
		command.collectDescriptor(file, seen)
	}
	paths := make([]string, 0, len(seen))
	for path := range seen {
		paths = append(paths, path)
	}
	slices.Sort(paths)
	set := &descriptorpb.FileDescriptorSet{File: make([]*descriptorpb.FileDescriptorProto, 0, len(paths))}
	for _, path := range paths {
		set.File = append(set.File, protodesc.ToFileDescriptorProto(seen[path]))
	}
	content, err := proto.MarshalOptions{Deterministic: true}.Marshal(set)
	if err != nil {
		return nil, fmt.Errorf("encode protocol descriptor set: %w", err)
	}
	return content, nil
}

func (command releaseAssetsCommand) collectDescriptor(
	file protoreflect.FileDescriptor,
	seen map[string]protoreflect.FileDescriptor,
) {
	if file == nil {
		return
	}
	path := file.Path()
	if _, found := seen[path]; found {
		return
	}
	seen[path] = file
	imports := file.Imports()
	for index := range imports.Len() {
		command.collectDescriptor(imports.Get(index).FileDescriptor, seen)
	}
}

func (releaseAssetsCommand) repositoryRoot() (string, error) {
	current, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		content, readErr := os.ReadFile(filepath.Join(current, "go.mod")) // #nosec G304 -- bounded ancestor search.
		if readErr == nil && bytes.Contains(content, []byte("module "+modulePath+"\n")) {
			return current, nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			return "", errors.New("find repository root: go.mod not found")
		}
		current = parent
	}
}
