//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/application.go:13

package spicegen

// ApplicationTargetArchitectureProof_a9d0849b identifies the generated target selected by spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:ArchitectureProof.
const ApplicationTargetArchitectureProof_a9d0849b = "architectureproof"
