//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/architecture_proof_interaction_broker_bean.go:12

package spicegen

import (
	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	interaction "github.com/spice-framework/spice-agent/interaction"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructArchitectureProofInteractionBroker_e456026b performs the direct construction selected for bean "architectureProofInteractionBroker".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|20:NewInteractionBroker.
func ConstructArchitectureProofInteractionBroker_e456026b() (interaction.Broker, spicelifecycle.Cleanup, error) {
	value := architectureproof.NewInteractionBroker()
	return value, nil, nil
}
