//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/architecture_proof_tool_dispatcher_bean.go:15

package spicegen

import (
	fmt "fmt"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	stage "github.com/spice-framework/spice-agent/stage"
	tool "github.com/spice-framework/spice-agent/tool"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructArchitectureProofToolDispatcher_d94350c9 performs the direct construction selected for bean "architectureProofToolDispatcher".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolDispatcher.
func ConstructArchitectureProofToolDispatcher_d94350c9(dependency0 map[string]tool.Tool) (stage.ToolDispatcher, spicelifecycle.Cleanup, error) {
	value, err := architectureproof.NewToolDispatcher(dependency0)
	if err != nil {
		var zero stage.ToolDispatcher
		return zero, nil, fmt.Errorf("construct bean architectureProofToolDispatcher (github.com/spice-framework/spice-agent/stage.ToolDispatcher, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolDispatcher): %w", err)
	}
	return value, nil, nil
}
