//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/architecture_proof_engine_bean.go:22

package spicegen

import (
	fmt "fmt"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	agent "github.com/spice-framework/spice-agent/agent"
	interaction "github.com/spice-framework/spice-agent/interaction"
	model "github.com/spice-framework/spice-agent/model"
	stage "github.com/spice-framework/spice-agent/stage"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructArchitectureProofEngine_d50c6257 performs the direct construction selected for bean "architectureProofEngine".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|9:NewEngine.
func ConstructArchitectureProofEngine_d50c6257(dependency0 model.Provider, dependency1 stage.ToolPlanSource, dependency2 interaction.Broker, dependency3 architectureproof.ExecutionPlanMetadata, dependency4 agent.IDSource, dependency5 coding.Config) (*agent.Engine, spicelifecycle.Cleanup, error) {
	value, cleanup, err := architectureproof.NewEngine(dependency0, dependency1, dependency2, dependency3, dependency4, dependency5)
	if err != nil {
		var zero *agent.Engine
		return zero, nil, fmt.Errorf("construct bean architectureProofEngine (*github.com/spice-framework/spice-agent/agent.Engine, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|9:NewEngine): %w", err)
	}
	return value, cleanup, nil
}
