//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/architecture_proof_execution_plan_bean.go:9

package spicegen

import (
	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructArchitectureProofExecutionPlan_98e864a9 performs the direct construction selected for bean "architectureProofExecutionPlan".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|24:NewExecutionPlanMetadata.
func ConstructArchitectureProofExecutionPlan_98e864a9() (architectureproof.ExecutionPlanMetadata, spicelifecycle.Cleanup, error) {
	value := architectureproof.NewExecutionPlanMetadata()
	return value, nil, nil
}
