//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/architecture_proof_tool_plan_source_bean.go:13

package spicegen

import (
	fmt "fmt"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	stage "github.com/spice-framework/spice-agent/stage"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructArchitectureProofToolPlanSource_5bb296a1 performs the direct construction selected for bean "architectureProofToolPlanSource".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolPlanSource.
func ConstructArchitectureProofToolPlanSource_5bb296a1(dependency0 stage.ToolDispatcher) (stage.ToolPlanSource, spicelifecycle.Cleanup, error) {
	value, err := architectureproof.NewToolPlanSource(dependency0)
	if err != nil {
		var zero stage.ToolPlanSource
		return zero, nil, fmt.Errorf("construct bean architectureProofToolPlanSource (github.com/spice-framework/spice-agent/stage.ToolPlanSource, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolPlanSource): %w", err)
	}
	return value, nil, nil
}
