//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/id_source.go:13

package spicegen

import (
	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	agent "github.com/spice-framework/spice-agent/agent"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructArchitectureProofIDSource_a4ffe4a0 performs the direct construction selected for bean "architectureProofIDSource".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|11:NewIDSource.
func ConstructArchitectureProofIDSource_a4ffe4a0() (agent.IDSource, spicelifecycle.Cleanup, error) {
	value := architectureproof.NewIDSource()
	return value, nil, nil
}
