//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/plan.go:40
// Source: internal/architectureproof/plan.go:60
// Source: internal/architectureproof/plan.go:77
// Source: internal/architectureproof/plan.go:89
// Source: internal/architectureproof/plan.go:98

package spicegen

import (
	fmt "fmt"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	agent "github.com/spice-framework/spice-agent/agent"
	interaction "github.com/spice-framework/spice-agent/interaction"
	model "github.com/spice-framework/spice-agent/model"
	stage "github.com/spice-framework/spice-agent/stage"
	tool "github.com/spice-framework/spice-agent/tool"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructArchitectureProofToolDispatcher_d94350c9 performs the direct construction selected for bean "architectureProofToolDispatcher".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolDispatcher.
func ConstructArchitectureProofToolDispatcher_d94350c9(dependency0 map[string]tool.Tool) (stage.ToolDispatcher, spicelifecycle.Cleanup, error) {
	value, err := architectureproof.NewToolDispatcher(dependency0)
	if err != nil {
		var zero stage.ToolDispatcher
		return zero, nil, fmt.Errorf("construct bean architectureProofToolDispatcher (github.com/spice-framework/spice-agent/stage.ToolDispatcher, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolDispatcher): %w", err)
	}
	return value, nil, nil
}

// ConstructArchitectureProofToolPlanSource_5bb296a1 performs the direct construction selected for bean "architectureProofToolPlanSource".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolPlanSource.
func ConstructArchitectureProofToolPlanSource_5bb296a1(dependency0 stage.ToolDispatcher) (stage.ToolPlanSource, spicelifecycle.Cleanup, error) {
	value, err := architectureproof.NewToolPlanSource(dependency0)
	if err != nil {
		var zero stage.ToolPlanSource
		return zero, nil, fmt.Errorf("construct bean architectureProofToolPlanSource (github.com/spice-framework/spice-agent/stage.ToolPlanSource, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolPlanSource): %w", err)
	}
	return value, nil, nil
}

// ConstructArchitectureProofInteractionBroker_e456026b performs the direct construction selected for bean "architectureProofInteractionBroker".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|20:NewInteractionBroker.
func ConstructArchitectureProofInteractionBroker_e456026b() (interaction.Broker, spicelifecycle.Cleanup, error) {
	value := architectureproof.NewInteractionBroker()
	return value, nil, nil
}

// ConstructArchitectureProofExecutionPlan_98e864a9 performs the direct construction selected for bean "architectureProofExecutionPlan".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|24:NewExecutionPlanMetadata.
func ConstructArchitectureProofExecutionPlan_98e864a9() (architectureproof.ExecutionPlanMetadata, spicelifecycle.Cleanup, error) {
	value := architectureproof.NewExecutionPlanMetadata()
	return value, nil, nil
}

// ConstructArchitectureProofEngine_d50c6257 performs the direct construction selected for bean "architectureProofEngine".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|9:NewEngine.
func ConstructArchitectureProofEngine_d50c6257(dependency0 model.Provider, dependency1 stage.ToolPlanSource, dependency2 interaction.Broker, dependency3 architectureproof.ExecutionPlanMetadata, dependency4 agent.IDSource) (*agent.Engine, spicelifecycle.Cleanup, error) {
	value, cleanup, err := architectureproof.NewEngine(dependency0, dependency1, dependency2, dependency3, dependency4)
	if err != nil {
		var zero *agent.Engine
		return zero, nil, fmt.Errorf("construct bean architectureProofEngine (*github.com/spice-framework/spice-agent/agent.Engine, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|9:NewEngine): %w", err)
	}
	return value, cleanup, nil
}
