//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/process_resolver_bean.go:13

package spicegen

import (
	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	process "github.com/spice-framework/spice-agent/process"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructProcessResolver_5cc0b06d performs the direct construction selected for bean "processResolver".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|21:NewExecutableResolver.
func ConstructProcessResolver_5cc0b06d() (process.ExecutableResolver, spicelifecycle.Cleanup, error) {
	value := architectureproof.NewExecutableResolver()
	return value, nil, nil
}
