//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/process.go:28
// Source: internal/architectureproof/process.go:35

package spicegen

import (
	fmt "fmt"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	process "github.com/spice-framework/spice-agent/process"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructProcessLauncher_33098fb2 performs the direct construction selected for bean "processLauncher".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|18:NewProcessLauncher.
func ConstructProcessLauncher_33098fb2() (process.Launcher, spicelifecycle.Cleanup, error) {
	value, err := architectureproof.NewProcessLauncher()
	if err != nil {
		var zero process.Launcher
		return zero, nil, fmt.Errorf("construct bean processLauncher (github.com/spice-framework/spice-agent/process.Launcher, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|18:NewProcessLauncher): %w", err)
	}
	return value, nil, nil
}

// ConstructProcessResolver_5cc0b06d performs the direct construction selected for bean "processResolver".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|21:NewExecutableResolver.
func ConstructProcessResolver_5cc0b06d() (process.ExecutableResolver, spicelifecycle.Cleanup, error) {
	value := architectureproof.NewExecutableResolver()
	return value, nil, nil
}
