//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/proof_bean.go:15

package spicegen

import (
	fmt "fmt"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	agent "github.com/spice-framework/spice-agent/agent"
	stage "github.com/spice-framework/spice-agent/stage"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructProof_579c091e performs the direct construction selected for bean "proof".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|8:NewProof.
func ConstructProof_579c091e(dependency0 *agent.Engine, dependency1 stage.ToolDispatcher, dependency2 *architectureproof.ResponsesFixture) (*architectureproof.Proof, spicelifecycle.Cleanup, error) {
	value, err := architectureproof.NewProof(dependency0, dependency1, dependency2)
	if err != nil {
		var zero *architectureproof.Proof
		return zero, nil, fmt.Errorf("construct bean proof (*github.com/spice-framework/spice-agent-coding/internal/architectureproof.Proof, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|8:NewProof): %w", err)
	}
	return value, nil, nil
}
