//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/responses.go:39

package spicegen

import (
	fmt "fmt"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	model "github.com/spice-framework/spice-agent/model"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructArchitectureProofOpenai_7e4ddfc0 performs the direct construction selected for bean "architecture-proof-openai".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|16:NewModelProvider.
func ConstructArchitectureProofOpenai_7e4ddfc0(dependency0 *architectureproof.ResponsesFixture) (model.Provider, spicelifecycle.Cleanup, error) {
	value, err := architectureproof.NewModelProvider(dependency0)
	if err != nil {
		var zero model.Provider
		return zero, nil, fmt.Errorf("construct bean architecture-proof-openai (github.com/spice-framework/spice-agent/model.Provider, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|16:NewModelProvider): %w", err)
	}
	return value, nil, nil
}
