//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/responses_fixture_bean.go:16

package spicegen

import (
	fmt "fmt"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructResponsesFixture_e85077ec performs the direct construction selected for bean "responsesFixture".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|19:NewResponsesFixture.
func ConstructResponsesFixture_e85077ec() (*architectureproof.ResponsesFixture, spicelifecycle.Cleanup, error) {
	value, cleanup, err := architectureproof.NewResponsesFixture()
	if err != nil {
		var zero *architectureproof.ResponsesFixture
		return zero, nil, fmt.Errorf("construct bean responsesFixture (*github.com/spice-framework/spice-agent-coding/internal/architectureproof.ResponsesFixture, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|19:NewResponsesFixture): %w", err)
	}
	return value, cleanup, nil
}
