//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/architectureproof/workspace.go:23

package spicegen

import (
	fmt "fmt"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructCodingConfig_4b9af99c performs the direct construction selected for bean "codingConfig".
// Spice source identity: spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|15:NewCodingConfig.
func ConstructCodingConfig_4b9af99c() (coding.Config, spicelifecycle.Cleanup, error) {
	value, cleanup, err := architectureproof.NewCodingConfig()
	if err != nil {
		var zero coding.Config
		return zero, nil, fmt.Errorf("construct bean codingConfig (github.com/spice-framework/spice-agent-tools-coding.Config, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|15:NewCodingConfig): %w", err)
	}
	return value, cleanup, nil
}
