//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/connection.go:22
// Source: internal/terminal/connection.go:50
// Source: internal/terminal/connection.go:63
// Source: internal/terminal/connection.go:74
// Source: internal/terminal/connection.go:81

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	client "github.com/spice-framework/spice-agent/client"
	managed "github.com/spice-framework/spice-agent/client/managed"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalClientBuild_da24cc0e performs the direct construction selected for bean "terminalClientBuild".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|14:NewClientBuild.
func ConstructTerminalClientBuild_da24cc0e() (client.Build, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewClientBuild()
	if err != nil {
		var zero client.Build
		return zero, nil, fmt.Errorf("construct bean terminalClientBuild (github.com/spice-framework/spice-agent/client.Build, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|14:NewClientBuild): %w", err)
	}
	return value, nil, nil
}

// ConstructTerminalClientLimits_52619d6f performs the direct construction selected for bean "terminalClientLimits".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|15:NewClientLimits.
func ConstructTerminalClientLimits_52619d6f() (client.Limits, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewClientLimits()
	if err != nil {
		var zero client.Limits
		return zero, nil, fmt.Errorf("construct bean terminalClientLimits (github.com/spice-framework/spice-agent/client.Limits, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|15:NewClientLimits): %w", err)
	}
	return value, nil, nil
}

// ConstructTerminalClientProtocol_8b3d67c7 performs the direct construction selected for bean "terminalClientProtocol".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|17:NewClientProtocol.
func ConstructTerminalClientProtocol_8b3d67c7() (client.ProtocolRange, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewClientProtocol()
	if err != nil {
		var zero client.ProtocolRange
		return zero, nil, fmt.Errorf("construct bean terminalClientProtocol (github.com/spice-framework/spice-agent/client.ProtocolRange, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|17:NewClientProtocol): %w", err)
	}
	return value, nil, nil
}

// ConstructTerminalClientConnector_123f20e3 performs the direct construction selected for bean "terminalClientConnector".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|18:NewClientConnector.
func ConstructTerminalClientConnector_123f20e3(dependency0 terminal.Properties, dependency1 *managed.Connector, dependency2 *endpoint.Store) (client.Connector, spicelifecycle.Cleanup, error) {
	value, cleanup, err := terminal.NewClientConnector(dependency0, dependency1, dependency2)
	if err != nil {
		var zero client.Connector
		return zero, nil, fmt.Errorf("construct bean terminalClientConnector (github.com/spice-framework/spice-agent/client.Connector, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|18:NewClientConnector): %w", err)
	}
	return value, cleanup, nil
}

// ConstructTerminalInitializeRequest_5f766851 performs the direct construction selected for bean "terminalInitializeRequest".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|20:NewInitializeRequest.
func ConstructTerminalInitializeRequest_5f766851(dependency0 client.ProtocolRange, dependency1 client.Build, dependency2 client.Limits) (client.InitializeRequest, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewInitializeRequest(dependency0, dependency1, dependency2)
	if err != nil {
		var zero client.InitializeRequest
		return zero, nil, fmt.Errorf("construct bean terminalInitializeRequest (github.com/spice-framework/spice-agent/client.InitializeRequest, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|20:NewInitializeRequest): %w", err)
	}
	return value, nil, nil
}
