//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/endpoint.go:27
// Source: internal/terminal/endpoint.go:34
// Source: internal/terminal/endpoint.go:45
// Source: internal/terminal/endpoint.go:56
// Source: internal/terminal/endpoint.go:64
// Source: internal/terminal/endpoint.go:75

package spicegen

import (
	fmt "fmt"

	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	localclient "github.com/spice-framework/spice-agent/client/localclient"
	managed "github.com/spice-framework/spice-agent/client/managed"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalStartupLock_08684a8d performs the direct construction selected for bean "terminalStartupLock".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|14:NewStartupLock.
func ConstructTerminalStartupLock_08684a8d(dependency0 *endpoint.Store) (*localclient.StartupLock, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewStartupLock(dependency0)
	if err != nil {
		var zero *localclient.StartupLock
		return zero, nil, fmt.Errorf("construct bean terminalStartupLock (*github.com/spice-framework/spice-agent/client/localclient.StartupLock, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|14:NewStartupLock): %w", err)
	}
	return value, nil, nil
}

// ConstructTerminalDaemonStarter_3c195b7f performs the direct construction selected for bean "terminalDaemonStarter".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewDaemonStarter.
func ConstructTerminalDaemonStarter_3c195b7f() (*daemonprocess.Starter, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewDaemonStarter()
	if err != nil {
		var zero *daemonprocess.Starter
		return zero, nil, fmt.Errorf("construct bean terminalDaemonStarter (*github.com/spice-framework/spice-agent-coding/internal/daemonprocess.Starter, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewDaemonStarter): %w", err)
	}
	return value, nil, nil
}

// ConstructTerminalEndpointScope_22dee5fa performs the direct construction selected for bean "terminalEndpointScope".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewEndpointScope.
func ConstructTerminalEndpointScope_22dee5fa() (endpoint.UserScope, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewEndpointScope()
	if err != nil {
		var zero endpoint.UserScope
		return zero, nil, fmt.Errorf("construct bean terminalEndpointScope (github.com/spice-framework/spice-agent/daemon/endpoint.UserScope, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewEndpointScope): %w", err)
	}
	return value, nil, nil
}

// ConstructTerminalEndpointStore_bc57eb5e performs the direct construction selected for bean "terminalEndpointStore".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewEndpointStore.
func ConstructTerminalEndpointStore_bc57eb5e(dependency0 endpoint.UserScope) (*endpoint.Store, spicelifecycle.Cleanup, error) {
	value, cleanup, err := terminal.NewEndpointStore(dependency0)
	if err != nil {
		var zero *endpoint.Store
		return zero, nil, fmt.Errorf("construct bean terminalEndpointStore (*github.com/spice-framework/spice-agent/daemon/endpoint.Store, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewEndpointStore): %w", err)
	}
	return value, cleanup, nil
}

// ConstructTerminalManagedConnector_707e2057 performs the direct construction selected for bean "terminalManagedConnector".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|19:NewManagedConnector.
func ConstructTerminalManagedConnector_707e2057(dependency0 *localclient.Discovery, dependency1 *daemonprocess.Starter, dependency2 *localclient.StartupLock) (*managed.Connector, spicelifecycle.Cleanup, error) {
	value, cleanup, err := terminal.NewManagedConnector(dependency0, dependency1, dependency2)
	if err != nil {
		var zero *managed.Connector
		return zero, nil, fmt.Errorf("construct bean terminalManagedConnector (*github.com/spice-framework/spice-agent/client/managed.Connector, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|19:NewManagedConnector): %w", err)
	}
	return value, cleanup, nil
}

// ConstructTerminalManagedDiscovery_0eae5b45 performs the direct construction selected for bean "terminalManagedDiscovery".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|19:NewManagedDiscovery.
func ConstructTerminalManagedDiscovery_0eae5b45(dependency0 *endpoint.Store) (*localclient.Discovery, spicelifecycle.Cleanup, error) {
	value, cleanup, err := terminal.NewManagedDiscovery(dependency0)
	if err != nil {
		var zero *localclient.Discovery
		return zero, nil, fmt.Errorf("construct bean terminalManagedDiscovery (*github.com/spice-framework/spice-agent/client/localclient.Discovery, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|19:NewManagedDiscovery): %w", err)
	}
	return value, cleanup, nil
}
