//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/properties.go:17

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	spiceconfig "github.com/spice-framework/spice/config"
)

// BindProperties_940b9db9 binds the validated configuration declared by spice:symbol:v1|type|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|10:Properties.
func BindProperties_940b9db9(configurationSnapshot spiceconfig.Snapshot) (terminal.Properties, error) {
	value := terminal.Properties{}
	if _, configured := configurationSnapshot.Lookup("agent.workspace"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.workspace")
		if valueErr != nil {
			return terminal.Properties{}, fmt.Errorf("decode configuration property agent.workspace for github.com/spice-framework/spice-agent-coding/internal/terminal.Properties.Workspace: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.Workspace = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.terminal.mode"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.terminal.mode")
		if valueErr != nil {
			return terminal.Properties{}, fmt.Errorf("decode configuration property agent.terminal.mode for github.com/spice-framework/spice-agent-coding/internal/terminal.Properties.TerminalMode: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.TerminalMode = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.terminal.endpoint"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("agent.terminal.endpoint")
		if valueErr != nil {
			return terminal.Properties{}, fmt.Errorf("decode configuration property agent.terminal.endpoint for github.com/spice-framework/spice-agent-coding/internal/terminal.Properties.TerminalEndpoint: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.TerminalEndpoint = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("agent.terminal.accessible"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("agent.terminal.accessible")
		if valueErr != nil {
			return terminal.Properties{}, fmt.Errorf("decode configuration property agent.terminal.accessible for github.com/spice-framework/spice-agent-coding/internal/terminal.Properties.TerminalAccessible: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.TerminalAccessible = convertedValue
	}
	return value, nil
}
