//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_initial_status_bean.go:11

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	agenttui "github.com/spice-framework/spice-agent-tui"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalInitialStatus_3572e532 performs the direct construction selected for bean "terminalInitialStatus".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewInitialStatus.
func ConstructTerminalInitialStatus_3572e532() (agenttui.StatusState, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewInitialStatus()
	if err != nil {
		var zero agenttui.StatusState
		return zero, nil, fmt.Errorf("construct bean terminalInitialStatus (github.com/spice-framework/spice-agent-tui.StatusState, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewInitialStatus): %w", err)
	}
	return value, nil, nil
}
