//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_endpoint_store_bean.go:15

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalEndpointStore_bc57eb5e performs the direct construction selected for bean "terminalEndpointStore".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewEndpointStore.
func ConstructTerminalEndpointStore_bc57eb5e(dependency0 endpoint.UserScope) (*endpoint.Store, spicelifecycle.Cleanup, error) {
	value, cleanup, err := terminal.NewEndpointStore(dependency0)
	if err != nil {
		var zero *endpoint.Store
		return zero, nil, fmt.Errorf("construct bean terminalEndpointStore (*github.com/spice-framework/spice-agent/daemon/endpoint.Store, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewEndpointStore): %w", err)
	}
	return value, cleanup, nil
}
