//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_client_build_bean.go:14

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	client "github.com/spice-framework/spice-agent/client"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalClientBuild_da24cc0e performs the direct construction selected for bean "terminalClientBuild".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|14:NewClientBuild.
func ConstructTerminalClientBuild_da24cc0e() (client.Build, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewClientBuild()
	if err != nil {
		var zero client.Build
		return zero, nil, fmt.Errorf("construct bean terminalClientBuild (github.com/spice-framework/spice-agent/client.Build, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|14:NewClientBuild): %w", err)
	}
	return value, nil, nil
}
