//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_session_bean.go:15

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	tuisession "github.com/spice-framework/spice-agent-coding/internal/tuisession"
	agenttui "github.com/spice-framework/spice-agent-tui"
	client "github.com/spice-framework/spice-agent/client"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalSession_bcae29da performs the direct construction selected for bean "terminalSession".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|10:NewSession.
func ConstructTerminalSession_bcae29da(dependency0 tuisession.Config, dependency1 client.Connector, dependency2 tuisession.IdentifierSource) (agenttui.Session, spicelifecycle.Cleanup, error) {
	value, cleanup, err := terminal.NewSession(dependency0, dependency1, dependency2)
	if err != nil {
		var zero agenttui.Session
		return zero, nil, fmt.Errorf("construct bean terminalSession (github.com/spice-framework/spice-agent-tui.Session, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|10:NewSession): %w", err)
	}
	return value, cleanup, nil
}
