//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_config_bean.go:12

package spicegen

import (
	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	agenttui "github.com/spice-framework/spice-agent-tui"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalConfig_ec99ff28 performs the direct construction selected for bean "terminalConfig".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|17:NewTerminalConfig.
func ConstructTerminalConfig_ec99ff28(dependency0 terminal.Properties) (agenttui.TerminalConfig, spicelifecycle.Cleanup, error) {
	value := terminal.NewTerminalConfig(dependency0)
	return value, nil, nil
}
