//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_managed_connector_bean.go:18

package spicegen

import (
	fmt "fmt"

	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	localclient "github.com/spice-framework/spice-agent/client/localclient"
	managed "github.com/spice-framework/spice-agent/client/managed"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalManagedConnector_707e2057 performs the direct construction selected for bean "terminalManagedConnector".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|19:NewManagedConnector.
func ConstructTerminalManagedConnector_707e2057(dependency0 *localclient.Discovery, dependency1 *daemonprocess.Starter, dependency2 *localclient.StartupLock) (*managed.Connector, spicelifecycle.Cleanup, error) {
	value, cleanup, err := terminal.NewManagedConnector(dependency0, dependency1, dependency2)
	if err != nil {
		var zero *managed.Connector
		return zero, nil, fmt.Errorf("construct bean terminalManagedConnector (*github.com/spice-framework/spice-agent/client/managed.Connector, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|19:NewManagedConnector): %w", err)
	}
	return value, cleanup, nil
}
