//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_definition_bean.go:11

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	client "github.com/spice-framework/spice-agent/client"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalDefinition_7925977f performs the direct construction selected for bean "terminalDefinition".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|13:NewDefinition.
func ConstructTerminalDefinition_7925977f() (client.DefinitionRef, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewDefinition()
	if err != nil {
		var zero client.DefinitionRef
		return zero, nil, fmt.Errorf("construct bean terminalDefinition (github.com/spice-framework/spice-agent/client.DefinitionRef, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|13:NewDefinition): %w", err)
	}
	return value, nil, nil
}
