//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_endpoint_scope_bean.go:11

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalEndpointScope_22dee5fa performs the direct construction selected for bean "terminalEndpointScope".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewEndpointScope.
func ConstructTerminalEndpointScope_22dee5fa() (endpoint.UserScope, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewEndpointScope()
	if err != nil {
		var zero endpoint.UserScope
		return zero, nil, fmt.Errorf("construct bean terminalEndpointScope (github.com/spice-framework/spice-agent/daemon/endpoint.UserScope, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewEndpointScope): %w", err)
	}
	return value, nil, nil
}
