//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_client_protocol_bean.go:12

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	client "github.com/spice-framework/spice-agent/client"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalClientProtocol_8b3d67c7 performs the direct construction selected for bean "terminalClientProtocol".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|17:NewClientProtocol.
func ConstructTerminalClientProtocol_8b3d67c7() (client.ProtocolRange, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewClientProtocol()
	if err != nil {
		var zero client.ProtocolRange
		return zero, nil, fmt.Errorf("construct bean terminalClientProtocol (github.com/spice-framework/spice-agent/client.ProtocolRange, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|17:NewClientProtocol): %w", err)
	}
	return value, nil, nil
}
