//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_managed_discovery_bean.go:15

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	localclient "github.com/spice-framework/spice-agent/client/localclient"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalManagedDiscovery_0eae5b45 performs the direct construction selected for bean "terminalManagedDiscovery".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|19:NewManagedDiscovery.
func ConstructTerminalManagedDiscovery_0eae5b45(dependency0 *endpoint.Store) (*localclient.Discovery, spicelifecycle.Cleanup, error) {
	value, cleanup, err := terminal.NewManagedDiscovery(dependency0)
	if err != nil {
		var zero *localclient.Discovery
		return zero, nil, fmt.Errorf("construct bean terminalManagedDiscovery (*github.com/spice-framework/spice-agent/client/localclient.Discovery, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|19:NewManagedDiscovery): %w", err)
	}
	return value, cleanup, nil
}
