//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_workspace_bean.go:15

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	workspace "github.com/spice-framework/spice-agent-coding/internal/workspace"
	agenttui "github.com/spice-framework/spice-agent-tui"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalWorkspace_8ebebbbd performs the direct construction selected for bean "terminalWorkspace".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|12:NewWorkspace.
func ConstructTerminalWorkspace_8ebebbbd(dependency0 workspace.Properties) (agenttui.WorkspaceState, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewWorkspace(dependency0)
	if err != nil {
		var zero agenttui.WorkspaceState
		return zero, nil, fmt.Errorf("construct bean terminalWorkspace (github.com/spice-framework/spice-agent-tui.WorkspaceState, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|12:NewWorkspace): %w", err)
	}
	return value, nil, nil
}
