//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_daemon_starter_bean.go:14

package spicegen

import (
	fmt "fmt"

	daemonprocess "github.com/spice-framework/spice-agent-coding/internal/daemonprocess"
	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalDaemonStarter_3c195b7f performs the direct construction selected for bean "terminalDaemonStarter".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewDaemonStarter.
func ConstructTerminalDaemonStarter_3c195b7f() (*daemonprocess.Starter, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewDaemonStarter()
	if err != nil {
		var zero *daemonprocess.Starter
		return zero, nil, fmt.Errorf("construct bean terminalDaemonStarter (*github.com/spice-framework/spice-agent-coding/internal/daemonprocess.Starter, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewDaemonStarter): %w", err)
	}
	return value, nil, nil
}
