//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_session_config_bean.go:14

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	tuisession "github.com/spice-framework/spice-agent-coding/internal/tuisession"
	agenttui "github.com/spice-framework/spice-agent-tui"
	client "github.com/spice-framework/spice-agent/client"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalSessionConfig_87aa536d performs the direct construction selected for bean "terminalSessionConfig".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewSessionConfig.
func ConstructTerminalSessionConfig_87aa536d(dependency0 client.InitializeRequest, dependency1 client.DefinitionRef, dependency2 agenttui.WorkspaceState, dependency3 agenttui.StatusState) (tuisession.Config, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewSessionConfig(dependency0, dependency1, dependency2, dependency3)
	if err != nil {
		var zero tuisession.Config
		return zero, nil, fmt.Errorf("construct bean terminalSessionConfig (github.com/spice-framework/spice-agent-coding/internal/tuisession.Config, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|16:NewSessionConfig): %w", err)
	}
	return value, nil, nil
}
