//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_initialize_request_bean.go:11

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	client "github.com/spice-framework/spice-agent/client"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalInitializeRequest_5f766851 performs the direct construction selected for bean "terminalInitializeRequest".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|20:NewInitializeRequest.
func ConstructTerminalInitializeRequest_5f766851(dependency0 client.ProtocolRange, dependency1 client.Build, dependency2 client.Limits) (client.InitializeRequest, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewInitializeRequest(dependency0, dependency1, dependency2)
	if err != nil {
		var zero client.InitializeRequest
		return zero, nil, fmt.Errorf("construct bean terminalInitializeRequest (github.com/spice-framework/spice-agent/client.InitializeRequest, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|20:NewInitializeRequest): %w", err)
	}
	return value, nil, nil
}
