//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_client_connector_bean.go:20

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	client "github.com/spice-framework/spice-agent/client"
	managed "github.com/spice-framework/spice-agent/client/managed"
	endpoint "github.com/spice-framework/spice-agent/daemon/endpoint"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalClientConnector_123f20e3 performs the direct construction selected for bean "terminalClientConnector".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|18:NewClientConnector.
func ConstructTerminalClientConnector_123f20e3(dependency0 terminal.Properties, dependency1 *managed.Connector, dependency2 *endpoint.Store) (client.Connector, spicelifecycle.Cleanup, error) {
	value, cleanup, err := terminal.NewClientConnector(dependency0, dependency1, dependency2)
	if err != nil {
		var zero client.Connector
		return zero, nil, fmt.Errorf("construct bean terminalClientConnector (github.com/spice-framework/spice-agent/client.Connector, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|18:NewClientConnector): %w", err)
	}
	return value, cleanup, nil
}
