//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_identifier_source_bean.go:12

package spicegen

import (
	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	tuisession "github.com/spice-framework/spice-agent-coding/internal/tuisession"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalIdentifierSource_3f0df0e0 performs the direct construction selected for bean "terminalIdentifierSource".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|19:NewIdentifierSource.
func ConstructTerminalIdentifierSource_3f0df0e0() (tuisession.IdentifierSource, spicelifecycle.Cleanup, error) {
	value := terminal.NewIdentifierSource()
	return value, nil, nil
}
