//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/terminal/terminal_client_limits_bean.go:11

package spicegen

import (
	fmt "fmt"

	terminal "github.com/spice-framework/spice-agent-coding/internal/terminal"
	client "github.com/spice-framework/spice-agent/client"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTerminalClientLimits_52619d6f performs the direct construction selected for bean "terminalClientLimits".
// Spice source identity: spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|15:NewClientLimits.
func ConstructTerminalClientLimits_52619d6f() (client.Limits, spicelifecycle.Cleanup, error) {
	value, err := terminal.NewClientLimits()
	if err != nil {
		var zero client.Limits
		return zero, nil, fmt.Errorf("construct bean terminalClientLimits (github.com/spice-framework/spice-agent/client.Limits, source spice:symbol:v1|function|63:github.com/spice-framework/spice-agent-coding/internal/terminal|0:|15:NewClientLimits): %w", err)
	}
	return value, nil, nil
}
