//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	spiceArchitectureproof "github.com/spice-framework/spice-agent-coding/internal/spicegen/architectureproof/sources/internal_/architectureproof"
	spiceAutoconfigure "github.com/spice-framework/spice-agent-coding/internal/spicegen/architectureproof/sources/vendor_/github.com/spice-framework/spice-agent-tools-coding/autoconfigure"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	agent "github.com/spice-framework/spice-agent/agent"
	interaction "github.com/spice-framework/spice-agent/interaction"
	model "github.com/spice-framework/spice-agent/model"
	process "github.com/spice-framework/spice-agent/process"
	stage "github.com/spice-framework/spice-agent/stage"
	tool "github.com/spice-framework/spice-agent/tool"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

type applicationDependencies struct {
	architectureProofIDSource          agent.IDSource
	codingConfig                       coding.Config
	read                               tool.Tool
	replace                            tool.Tool
	processLauncher                    process.Launcher
	responsesFixture                   *architectureproof.ResponsesFixture
	architectureProofOpenai            model.Provider
	architectureProofInteractionBroker interaction.Broker
	processResolver                    process.ExecutableResolver
	shell                              tool.Tool
	architectureProofToolDispatcher    stage.ToolDispatcher
	architectureProofToolPlanSource    stage.ToolPlanSource
	architectureProofExecutionPlan     architectureproof.ExecutionPlanMetadata
	architectureProofEngine            *agent.Engine
	proof                              *architectureproof.Proof
}

func constructApplicationDependencies(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
) (*applicationDependencies, error) {
	_ = ctx
	_ = application
	_ = options
	_ = configurationSnapshot
	architectureProofIDSource, architectureProofIDSourceCleanup, err := func() (agent.IDSource, spicelifecycle.Cleanup, error) {
		if options.Overrides.ArchitectureProofIDSource.Enabled() {
			return options.Overrides.ArchitectureProofIDSource.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructArchitectureProofIDSource_a4ffe4a0()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean architectureProofIDSource (github.com/spice-framework/spice-agent/agent.IDSource, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|11:NewIDSource): %w", err))
	}
	if architectureProofIDSourceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|11:NewIDSource", architectureProofIDSourceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean architectureProofIDSource (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|11:NewIDSource): %w", err))
		}
	}
	_ = architectureProofIDSource
	codingConfig, codingConfigCleanup, err := func() (coding.Config, spicelifecycle.Cleanup, error) {
		if options.Overrides.CodingConfig.Enabled() {
			return options.Overrides.CodingConfig.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructCodingConfig_4b9af99c()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean codingConfig (github.com/spice-framework/spice-agent-tools-coding.Config, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|15:NewCodingConfig): %w", err))
	}
	if codingConfigCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|15:NewCodingConfig", codingConfigCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean codingConfig (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|15:NewCodingConfig): %w", err))
		}
	}
	_ = codingConfig
	read, readCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Read.Enabled() {
			return options.Overrides.Read.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructRead_1b770715(codingConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean read (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead): %w", err))
	}
	if readCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead", readCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean read (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead): %w", err))
		}
	}
	_ = read
	replace, replaceCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Replace.Enabled() {
			return options.Overrides.Replace.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructReplace_96382d5b(codingConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean replace (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace): %w", err))
	}
	if replaceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace", replaceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean replace (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace): %w", err))
		}
	}
	_ = replace
	processLauncher, processLauncherCleanup, err := func() (process.Launcher, spicelifecycle.Cleanup, error) {
		if options.Overrides.ProcessLauncher.Enabled() {
			return options.Overrides.ProcessLauncher.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructProcessLauncher_33098fb2()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean processLauncher (github.com/spice-framework/spice-agent/process.Launcher, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|18:NewProcessLauncher): %w", err))
	}
	if processLauncherCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|18:NewProcessLauncher", processLauncherCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean processLauncher (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|18:NewProcessLauncher): %w", err))
		}
	}
	_ = processLauncher
	responsesFixture, responsesFixtureCleanup, err := func() (*architectureproof.ResponsesFixture, spicelifecycle.Cleanup, error) {
		if options.Overrides.ResponsesFixture.Enabled() {
			return options.Overrides.ResponsesFixture.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructResponsesFixture_e85077ec()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean responsesFixture (*github.com/spice-framework/spice-agent-coding/internal/architectureproof.ResponsesFixture, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|19:NewResponsesFixture): %w", err))
	}
	if responsesFixtureCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|19:NewResponsesFixture", responsesFixtureCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean responsesFixture (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|19:NewResponsesFixture): %w", err))
		}
	}
	_ = responsesFixture
	architectureProofOpenai, architectureProofOpenaiCleanup, err := func() (model.Provider, spicelifecycle.Cleanup, error) {
		if options.Overrides.Provider6.Enabled() {
			return options.Overrides.Provider6.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructArchitectureProofOpenai_7e4ddfc0(responsesFixture)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean architecture-proof-openai (github.com/spice-framework/spice-agent/model.Provider, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|16:NewModelProvider): %w", err))
	}
	if architectureProofOpenaiCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|16:NewModelProvider", architectureProofOpenaiCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean architecture-proof-openai (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|16:NewModelProvider): %w", err))
		}
	}
	_ = architectureProofOpenai
	architectureProofInteractionBroker, architectureProofInteractionBrokerCleanup, err := func() (interaction.Broker, spicelifecycle.Cleanup, error) {
		if options.Overrides.ArchitectureProofInteractionBroker.Enabled() {
			return options.Overrides.ArchitectureProofInteractionBroker.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructArchitectureProofInteractionBroker_e456026b()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean architectureProofInteractionBroker (github.com/spice-framework/spice-agent/interaction.Broker, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|20:NewInteractionBroker): %w", err))
	}
	if architectureProofInteractionBrokerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|20:NewInteractionBroker", architectureProofInteractionBrokerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean architectureProofInteractionBroker (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|20:NewInteractionBroker): %w", err))
		}
	}
	_ = architectureProofInteractionBroker
	processResolver, processResolverCleanup, err := func() (process.ExecutableResolver, spicelifecycle.Cleanup, error) {
		if options.Overrides.ProcessResolver.Enabled() {
			return options.Overrides.ProcessResolver.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructProcessResolver_5cc0b06d()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean processResolver (github.com/spice-framework/spice-agent/process.ExecutableResolver, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|21:NewExecutableResolver): %w", err))
	}
	if processResolverCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|21:NewExecutableResolver", processResolverCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean processResolver (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|21:NewExecutableResolver): %w", err))
		}
	}
	_ = processResolver
	shell, shellCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Shell.Enabled() {
			return options.Overrides.Shell.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructShell_a48b269f(codingConfig, processResolver, processLauncher)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean shell (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell): %w", err))
	}
	if shellCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell", shellCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean shell (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell): %w", err))
		}
	}
	_ = shell
	architectureProofToolDispatcher, architectureProofToolDispatcherCleanup, err := func() (stage.ToolDispatcher, spicelifecycle.Cleanup, error) {
		if options.Overrides.ArchitectureProofToolDispatcher.Enabled() {
			return options.Overrides.ArchitectureProofToolDispatcher.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructArchitectureProofToolDispatcher_d94350c9(map[string]tool.Tool{"read": read, "replace": replace, "shell": shell})
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean architectureProofToolDispatcher (github.com/spice-framework/spice-agent/stage.ToolDispatcher, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolDispatcher): %w", err))
	}
	if architectureProofToolDispatcherCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolDispatcher", architectureProofToolDispatcherCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean architectureProofToolDispatcher (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolDispatcher): %w", err))
		}
	}
	_ = architectureProofToolDispatcher
	architectureProofToolPlanSource, architectureProofToolPlanSourceCleanup, err := func() (stage.ToolPlanSource, spicelifecycle.Cleanup, error) {
		if options.Overrides.ArchitectureProofToolPlanSource.Enabled() {
			return options.Overrides.ArchitectureProofToolPlanSource.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructArchitectureProofToolPlanSource_5bb296a1(architectureProofToolDispatcher)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean architectureProofToolPlanSource (github.com/spice-framework/spice-agent/stage.ToolPlanSource, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolPlanSource): %w", err))
	}
	if architectureProofToolPlanSourceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolPlanSource", architectureProofToolPlanSourceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean architectureProofToolPlanSource (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|17:NewToolPlanSource): %w", err))
		}
	}
	_ = architectureProofToolPlanSource
	architectureProofExecutionPlan, architectureProofExecutionPlanCleanup, err := func() (architectureproof.ExecutionPlanMetadata, spicelifecycle.Cleanup, error) {
		if options.Overrides.ArchitectureProofExecutionPlan.Enabled() {
			return options.Overrides.ArchitectureProofExecutionPlan.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructArchitectureProofExecutionPlan_98e864a9()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean architectureProofExecutionPlan (github.com/spice-framework/spice-agent-coding/internal/architectureproof.ExecutionPlanMetadata, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|24:NewExecutionPlanMetadata): %w", err))
	}
	if architectureProofExecutionPlanCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|24:NewExecutionPlanMetadata", architectureProofExecutionPlanCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean architectureProofExecutionPlan (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|24:NewExecutionPlanMetadata): %w", err))
		}
	}
	_ = architectureProofExecutionPlan
	architectureProofEngine, architectureProofEngineCleanup, err := func() (*agent.Engine, spicelifecycle.Cleanup, error) {
		if options.Overrides.ArchitectureProofEngine.Enabled() {
			return options.Overrides.ArchitectureProofEngine.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructArchitectureProofEngine_d50c6257(architectureProofOpenai, architectureProofToolPlanSource, architectureProofInteractionBroker, architectureProofExecutionPlan, architectureProofIDSource)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean architectureProofEngine (*github.com/spice-framework/spice-agent/agent.Engine, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|9:NewEngine): %w", err))
	}
	if architectureProofEngineCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|9:NewEngine", architectureProofEngineCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean architectureProofEngine (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|9:NewEngine): %w", err))
		}
	}
	_ = architectureProofEngine
	proof, proofCleanup, err := func() (*architectureproof.Proof, spicelifecycle.Cleanup, error) {
		if options.Overrides.Proof.Enabled() {
			return options.Overrides.Proof.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructProof_579c091e(architectureProofEngine, architectureProofToolDispatcher, responsesFixture)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean proof (*github.com/spice-framework/spice-agent-coding/internal/architectureproof.Proof, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|8:NewProof): %w", err))
	}
	if proofCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|8:NewProof", proofCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean proof (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|8:NewProof): %w", err))
		}
	}
	_ = proof
	return &applicationDependencies{
		architectureProofIDSource:          architectureProofIDSource,
		codingConfig:                       codingConfig,
		read:                               read,
		replace:                            replace,
		processLauncher:                    processLauncher,
		responsesFixture:                   responsesFixture,
		architectureProofOpenai:            architectureProofOpenai,
		architectureProofInteractionBroker: architectureProofInteractionBroker,
		processResolver:                    processResolver,
		shell:                              shell,
		architectureProofToolDispatcher:    architectureProofToolDispatcher,
		architectureProofToolPlanSource:    architectureProofToolPlanSource,
		architectureProofExecutionPlan:     architectureProofExecutionPlan,
		architectureProofEngine:            architectureProofEngine,
		proof:                              proof,
	}, nil
}
