//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	fmt "fmt"
	strings "strings"
	time "time"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	spiceArchitectureproof "github.com/spice-framework/spice-agent-coding/internal/spicegen/architectureproof/sources/internal_/architectureproof"
	workspace "github.com/spice-framework/spice-agent-coding/internal/workspace"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	agent "github.com/spice-framework/spice-agent/agent"
	interaction "github.com/spice-framework/spice-agent/interaction"
	model "github.com/spice-framework/spice-agent/model"
	process "github.com/spice-framework/spice-agent/process"
	stage "github.com/spice-framework/spice-agent/stage"
	tool "github.com/spice-framework/spice-agent/tool"
	spicebean "github.com/spice-framework/spice/bean"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

const TargetID = spiceArchitectureproof.ApplicationTargetArchitectureProof_a9d0849b

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// ArchitectureProofIDSource is bean "architectureProofIDSource".
	ArchitectureProofIDSource agent.IDSource
	// CodingConfig is bean "codingConfig".
	CodingConfig coding.Config
	// Read is bean "read".
	Read tool.Tool
	// Replace is bean "replace".
	Replace tool.Tool
	// ProcessLauncher is bean "processLauncher".
	ProcessLauncher process.Launcher
	// ResponsesFixture is bean "responsesFixture".
	ResponsesFixture *architectureproof.ResponsesFixture
	// Provider6 is bean "architecture-proof-openai".
	Provider6 model.Provider
	// ArchitectureProofInteractionBroker is bean "architectureProofInteractionBroker".
	ArchitectureProofInteractionBroker interaction.Broker
	// ProcessResolver is bean "processResolver".
	ProcessResolver process.ExecutableResolver
	// Shell is bean "shell".
	Shell tool.Tool
	// ArchitectureProofToolDispatcher is bean "architectureProofToolDispatcher".
	ArchitectureProofToolDispatcher stage.ToolDispatcher
	// ArchitectureProofToolPlanSource is bean "architectureProofToolPlanSource".
	ArchitectureProofToolPlanSource stage.ToolPlanSource
	// ArchitectureProofExecutionPlan is bean "architectureProofExecutionPlan".
	ArchitectureProofExecutionPlan architectureproof.ExecutionPlanMetadata
	// ArchitectureProofEngine is bean "architectureProofEngine".
	ArchitectureProofEngine *agent.Engine
	// Proof is bean "proof".
	Proof *architectureproof.Proof
	// Properties is bean "Properties".
	Properties workspace.Properties
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// ArchitectureProofIDSource replaces bean "architectureProofIDSource".
	ArchitectureProofIDSource spicebean.Override[agent.IDSource]
	// CodingConfig replaces bean "codingConfig".
	CodingConfig spicebean.Override[coding.Config]
	// Read replaces bean "read".
	Read spicebean.Override[tool.Tool]
	// Replace replaces bean "replace".
	Replace spicebean.Override[tool.Tool]
	// ProcessLauncher replaces bean "processLauncher".
	ProcessLauncher spicebean.Override[process.Launcher]
	// ResponsesFixture replaces bean "responsesFixture".
	ResponsesFixture spicebean.Override[*architectureproof.ResponsesFixture]
	// Provider6 replaces bean "architecture-proof-openai".
	Provider6 spicebean.Override[model.Provider]
	// ArchitectureProofInteractionBroker replaces bean "architectureProofInteractionBroker".
	ArchitectureProofInteractionBroker spicebean.Override[interaction.Broker]
	// ProcessResolver replaces bean "processResolver".
	ProcessResolver spicebean.Override[process.ExecutableResolver]
	// Shell replaces bean "shell".
	Shell spicebean.Override[tool.Tool]
	// ArchitectureProofToolDispatcher replaces bean "architectureProofToolDispatcher".
	ArchitectureProofToolDispatcher spicebean.Override[stage.ToolDispatcher]
	// ArchitectureProofToolPlanSource replaces bean "architectureProofToolPlanSource".
	ArchitectureProofToolPlanSource spicebean.Override[stage.ToolPlanSource]
	// ArchitectureProofExecutionPlan replaces bean "architectureProofExecutionPlan".
	ArchitectureProofExecutionPlan spicebean.Override[architectureproof.ExecutionPlanMetadata]
	// ArchitectureProofEngine replaces bean "architectureProofEngine".
	ArchitectureProofEngine spicebean.Override[*agent.Engine]
	// Proof replaces bean "proof".
	Proof spicebean.Override[*architectureproof.Proof]
}

// BeanOverrideLayer is one named immutable override composition layer.
// Layers are applied in order; a later layer deliberately replaces an earlier value.
type BeanOverrideLayer struct {
	Name      string
	Overrides BeanOverrides
}

// ComposeBeanOverrides validates and deterministically composes named layers.
// It never mutates a running application or performs runtime bean lookup.
func ComposeBeanOverrides(layers ...BeanOverrideLayer) (BeanOverrides, error) {
	result := BeanOverrides{}
	seen := make(map[string]int, len(layers))
	for index, layer := range layers {
		if layer.Name == "" || strings.TrimSpace(layer.Name) != layer.Name {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %d requires a non-empty name without surrounding whitespace", index)
		}
		if previous, duplicate := seen[layer.Name]; duplicate {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %q repeats layer %d", layer.Name, previous)
		}
		seen[layer.Name] = index
		if layer.Overrides.ArchitectureProofIDSource.Enabled() {
			result.ArchitectureProofIDSource = layer.Overrides.ArchitectureProofIDSource
		}
		if layer.Overrides.CodingConfig.Enabled() {
			result.CodingConfig = layer.Overrides.CodingConfig
		}
		if layer.Overrides.Read.Enabled() {
			result.Read = layer.Overrides.Read
		}
		if layer.Overrides.Replace.Enabled() {
			result.Replace = layer.Overrides.Replace
		}
		if layer.Overrides.ProcessLauncher.Enabled() {
			result.ProcessLauncher = layer.Overrides.ProcessLauncher
		}
		if layer.Overrides.ResponsesFixture.Enabled() {
			result.ResponsesFixture = layer.Overrides.ResponsesFixture
		}
		if layer.Overrides.Provider6.Enabled() {
			result.Provider6 = layer.Overrides.Provider6
		}
		if layer.Overrides.ArchitectureProofInteractionBroker.Enabled() {
			result.ArchitectureProofInteractionBroker = layer.Overrides.ArchitectureProofInteractionBroker
		}
		if layer.Overrides.ProcessResolver.Enabled() {
			result.ProcessResolver = layer.Overrides.ProcessResolver
		}
		if layer.Overrides.Shell.Enabled() {
			result.Shell = layer.Overrides.Shell
		}
		if layer.Overrides.ArchitectureProofToolDispatcher.Enabled() {
			result.ArchitectureProofToolDispatcher = layer.Overrides.ArchitectureProofToolDispatcher
		}
		if layer.Overrides.ArchitectureProofToolPlanSource.Enabled() {
			result.ArchitectureProofToolPlanSource = layer.Overrides.ArchitectureProofToolPlanSource
		}
		if layer.Overrides.ArchitectureProofExecutionPlan.Enabled() {
			result.ArchitectureProofExecutionPlan = layer.Overrides.ArchitectureProofExecutionPlan
		}
		if layer.Overrides.ArchitectureProofEngine.Enabled() {
			result.ArchitectureProofEngine = layer.Overrides.ArchitectureProofEngine
		}
		if layer.Overrides.Proof.Enabled() {
			result.Proof = layer.Overrides.Proof
		}
	}
	return result, nil
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	Observers                 []spicelifecycle.Observer
}
