//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	fmt "fmt"
	strings "strings"
	time "time"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	spiceArchitectureproof "github.com/spice-framework/spice-agent-coding/internal/spicegen/architectureproof/sources/internal_/architectureproof"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	model "github.com/spice-framework/spice-agent/model"
	tool "github.com/spice-framework/spice-agent/tool"
	spicebean "github.com/spice-framework/spice/bean"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

const TargetID = spiceArchitectureproof.ApplicationTargetArchitectureProof_a9d0849b

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// CodingConfig is bean "codingConfig".
	CodingConfig coding.Config
	// Read is bean "read".
	Read tool.Tool
	// Shell is bean "shell".
	Shell tool.Tool
	// Replace is bean "replace".
	Replace tool.Tool
	// ResponsesFixture is bean "responsesFixture".
	ResponsesFixture *architectureproof.ResponsesFixture
	// Provider5 is bean "architecture-proof-openai".
	Provider5 model.Provider
	// Proof is bean "proof".
	Proof *architectureproof.Proof
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// CodingConfig replaces bean "codingConfig".
	CodingConfig spicebean.Override[coding.Config]
	// Read replaces bean "read".
	Read spicebean.Override[tool.Tool]
	// Shell replaces bean "shell".
	Shell spicebean.Override[tool.Tool]
	// Replace replaces bean "replace".
	Replace spicebean.Override[tool.Tool]
	// ResponsesFixture replaces bean "responsesFixture".
	ResponsesFixture spicebean.Override[*architectureproof.ResponsesFixture]
	// Provider5 replaces bean "architecture-proof-openai".
	Provider5 spicebean.Override[model.Provider]
	// Proof replaces bean "proof".
	Proof spicebean.Override[*architectureproof.Proof]
}

// BeanOverrideLayer is one named immutable override composition layer.
// Layers are applied in order; a later layer deliberately replaces an earlier value.
type BeanOverrideLayer struct {
	Name      string
	Overrides BeanOverrides
}

// ComposeBeanOverrides validates and deterministically composes named layers.
// It never mutates a running application or performs runtime bean lookup.
func ComposeBeanOverrides(layers ...BeanOverrideLayer) (BeanOverrides, error) {
	result := BeanOverrides{}
	seen := make(map[string]int, len(layers))
	for index, layer := range layers {
		if layer.Name == "" || strings.TrimSpace(layer.Name) != layer.Name {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %d requires a non-empty name without surrounding whitespace", index)
		}
		if previous, duplicate := seen[layer.Name]; duplicate {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %q repeats layer %d", layer.Name, previous)
		}
		seen[layer.Name] = index
		if layer.Overrides.CodingConfig.Enabled() {
			result.CodingConfig = layer.Overrides.CodingConfig
		}
		if layer.Overrides.Read.Enabled() {
			result.Read = layer.Overrides.Read
		}
		if layer.Overrides.Shell.Enabled() {
			result.Shell = layer.Overrides.Shell
		}
		if layer.Overrides.Replace.Enabled() {
			result.Replace = layer.Overrides.Replace
		}
		if layer.Overrides.ResponsesFixture.Enabled() {
			result.ResponsesFixture = layer.Overrides.ResponsesFixture
		}
		if layer.Overrides.Provider5.Enabled() {
			result.Provider5 = layer.Overrides.Provider5
		}
		if layer.Overrides.Proof.Enabled() {
			result.Proof = layer.Overrides.Proof
		}
	}
	return result, nil
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	Observers                 []spicelifecycle.Observer
}
