//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {
	return NewApplicationWithOptions(ctx, ApplicationOptions{Observers: observers})
}

func NewApplicationWithOptions(ctx context.Context, options ApplicationOptions) (*Application, error) {
	if ctx == nil {
		return nil, fmt.Errorf("construct application architectureproof: context is nil")
	}
	application := &Application{coordinator: spicelifecycle.NewCoordinator()}
	configurationSchema, err := ConfigurationSchema()
	if err != nil {
		return nil, fmt.Errorf("construct configuration schema for application architectureproof: %w", err)
	}
	configurationSnapshot, err := spiceconfig.Resolve(
		ctx,
		configurationSchema,
		spiceconfig.Options{
			Profiles:     options.Profiles,
			AllowUnknown: options.AllowUnknownConfiguration,
		},
		options.Sources...,
	)
	if err != nil {
		return nil, fmt.Errorf("resolve configuration for application architectureproof: %w", err)
	}
	application.shutdownTimeout, err = configurationSnapshot.Duration("spice.shutdown-timeout")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application architectureproof: %w", err))
	}
	if application.shutdownTimeout <= 0 {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application architectureproof: duration must be positive"))
	}
	observers := append([]spicelifecycle.Observer(nil), options.Observers...)
	for index, observer := range observers {
		if err := application.coordinator.RegisterObserver(observer); err != nil {
			return nil, fmt.Errorf("register lifecycle observer %d: %w", index, err)
		}
	}
	dependencies, err := constructApplicationDependencies(ctx, application, options, configurationSnapshot)
	if err != nil {
		return nil, err
	}
	_ = dependencies
	application.components = Components{
		ArchitectureProofIDSource:          dependencies.architectureProofIDSource,
		CodingConfig:                       dependencies.codingConfig,
		Read:                               dependencies.read,
		Replace:                            dependencies.replace,
		ProcessLauncher:                    dependencies.processLauncher,
		ResponsesFixture:                   dependencies.responsesFixture,
		Provider6:                          dependencies.architectureProofOpenai,
		ArchitectureProofInteractionBroker: dependencies.architectureProofInteractionBroker,
		ProcessResolver:                    dependencies.processResolver,
		Shell:                              dependencies.shell,
		ArchitectureProofToolDispatcher:    dependencies.architectureProofToolDispatcher,
		ArchitectureProofToolPlanSource:    dependencies.architectureProofToolPlanSource,
		ArchitectureProofExecutionPlan:     dependencies.architectureProofExecutionPlan,
		ArchitectureProofEngine:            dependencies.architectureProofEngine,
		Proof:                              dependencies.proof,
		Properties:                         dependencies.properties,
	}
	return application, nil
}
