//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	architectureproof "github.com/spice-framework/spice-agent-coding/internal/architectureproof"
	spiceArchitectureproof "github.com/spice-framework/spice-agent-coding/internal/spicegen/architectureproof/sources/internal_/architectureproof"
	spiceAutoconfigure "github.com/spice-framework/spice-agent-coding/internal/spicegen/architectureproof/sources/vendor_/github.com/spice-framework/spice-agent-tools-coding/autoconfigure"
	coding "github.com/spice-framework/spice-agent-tools-coding"
	model "github.com/spice-framework/spice-agent/model"
	tool "github.com/spice-framework/spice-agent/tool"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

type applicationDependencies struct {
	codingConfig            coding.Config
	read                    tool.Tool
	shell                   tool.Tool
	replace                 tool.Tool
	responsesFixture        *architectureproof.ResponsesFixture
	architectureProofOpenai model.Provider
	proof                   *architectureproof.Proof
}

func constructApplicationDependencies(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
) (*applicationDependencies, error) {
	_ = ctx
	_ = application
	_ = options
	_ = configurationSnapshot
	codingConfig, codingConfigCleanup, err := func() (coding.Config, spicelifecycle.Cleanup, error) {
		if options.Overrides.CodingConfig.Enabled() {
			return options.Overrides.CodingConfig.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructCodingConfig_4b9af99c()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean codingConfig (github.com/spice-framework/spice-agent-tools-coding.Config, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|15:NewCodingConfig): %w", err))
	}
	if codingConfigCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|15:NewCodingConfig", codingConfigCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean codingConfig (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|15:NewCodingConfig): %w", err))
		}
	}
	_ = codingConfig
	read, readCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Read.Enabled() {
			return options.Overrides.Read.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructRead_1b770715(codingConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean read (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead): %w", err))
	}
	if readCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead", readCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean read (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead): %w", err))
		}
	}
	_ = read
	shell, shellCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Shell.Enabled() {
			return options.Overrides.Shell.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructShell_a48b269f(codingConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean shell (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell): %w", err))
	}
	if shellCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell", shellCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean shell (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell): %w", err))
		}
	}
	_ = shell
	replace, replaceCleanup, err := func() (tool.Tool, spicelifecycle.Cleanup, error) {
		if options.Overrides.Replace.Enabled() {
			return options.Overrides.Replace.Acquire(ctx)
		}
		return spiceAutoconfigure.ConstructReplace_96382d5b(codingConfig)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean replace (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace): %w", err))
	}
	if replaceCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace", replaceCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean replace (source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace): %w", err))
		}
	}
	_ = replace
	responsesFixture, responsesFixtureCleanup, err := func() (*architectureproof.ResponsesFixture, spicelifecycle.Cleanup, error) {
		if options.Overrides.ResponsesFixture.Enabled() {
			return options.Overrides.ResponsesFixture.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructResponsesFixture_e85077ec()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean responsesFixture (*github.com/spice-framework/spice-agent-coding/internal/architectureproof.ResponsesFixture, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|19:NewResponsesFixture): %w", err))
	}
	if responsesFixtureCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|19:NewResponsesFixture", responsesFixtureCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean responsesFixture (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|19:NewResponsesFixture): %w", err))
		}
	}
	_ = responsesFixture
	architectureProofOpenai, architectureProofOpenaiCleanup, err := func() (model.Provider, spicelifecycle.Cleanup, error) {
		if options.Overrides.Provider5.Enabled() {
			return options.Overrides.Provider5.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructArchitectureProofOpenai_7e4ddfc0(responsesFixture)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean architecture-proof-openai (github.com/spice-framework/spice-agent/model.Provider, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|16:NewModelProvider): %w", err))
	}
	if architectureProofOpenaiCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|16:NewModelProvider", architectureProofOpenaiCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean architecture-proof-openai (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|16:NewModelProvider): %w", err))
		}
	}
	_ = architectureProofOpenai
	proof, proofCleanup, err := func() (*architectureproof.Proof, spicelifecycle.Cleanup, error) {
		if options.Overrides.Proof.Enabled() {
			return options.Overrides.Proof.Acquire(ctx)
		}
		return spiceArchitectureproof.ConstructProof_579c091e(architectureProofOpenai, map[string]tool.Tool{"read": read, "replace": replace, "shell": shell}, responsesFixture)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean proof (*github.com/spice-framework/spice-agent-coding/internal/architectureproof.Proof, source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|8:NewProof): %w", err))
	}
	if proofCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|8:NewProof", proofCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean proof (source spice:symbol:v1|function|72:github.com/spice-framework/spice-agent-coding/internal/architectureproof|0:|8:NewProof): %w", err))
		}
	}
	_ = proof
	return &applicationDependencies{
		codingConfig:            codingConfig,
		read:                    read,
		shell:                   shell,
		replace:                 replace,
		responsesFixture:        responsesFixture,
		architectureProofOpenai: architectureProofOpenai,
		proof:                   proof,
	}, nil
}
