//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/application.go:14

package spicegen

// ApplicationTargetDaemon_7041e896 identifies the generated target selected by spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|6:Daemon.
const ApplicationTargetDaemon_7041e896 = "daemon"
