//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/daemon/plan.go:22
// Source: internal/daemon/plan.go:34
// Source: internal/daemon/plan.go:41
// Source: internal/daemon/plan.go:49
// Source: internal/daemon/plan.go:57

package spicegen

import (
	fmt "fmt"

	daemon2 "github.com/spice-framework/spice-agent-coding/internal/daemon"
	agent "github.com/spice-framework/spice-agent/agent"
	daemon "github.com/spice-framework/spice-agent/daemon"
	interaction "github.com/spice-framework/spice-agent/interaction"
	model "github.com/spice-framework/spice-agent/model"
	stage "github.com/spice-framework/spice-agent/stage"
	tool "github.com/spice-framework/spice-agent/tool"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructPendingHub_4cbcfd89 performs the direct construction selected for bean "pendingHub".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub.
func ConstructPendingHub_4cbcfd89() (*daemon.PendingHub, spicelifecycle.Cleanup, error) {
	value, err := daemon2.NewPendingHub()
	if err != nil {
		var zero *daemon.PendingHub
		return zero, nil, fmt.Errorf("construct bean pendingHub (*github.com/spice-framework/spice-agent/daemon.PendingHub, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|13:NewPendingHub): %w", err)
	}
	return value, nil, nil
}

// ConstructDaemonToolDispatcher_62bc19b3 performs the direct construction selected for bean "daemonToolDispatcher".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|17:NewToolDispatcher.
func ConstructDaemonToolDispatcher_62bc19b3(dependency0 map[string]tool.Tool) (stage.ToolDispatcher, spicelifecycle.Cleanup, error) {
	value, err := daemon2.NewToolDispatcher(dependency0)
	if err != nil {
		var zero stage.ToolDispatcher
		return zero, nil, fmt.Errorf("construct bean daemonToolDispatcher (github.com/spice-framework/spice-agent/stage.ToolDispatcher, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|17:NewToolDispatcher): %w", err)
	}
	return value, nil, nil
}

// ConstructDaemonToolPlanSource_4dd1bcce performs the direct construction selected for bean "daemonToolPlanSource".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|17:NewToolPlanSource.
func ConstructDaemonToolPlanSource_4dd1bcce(dependency0 stage.ToolDispatcher) (stage.ToolPlanSource, spicelifecycle.Cleanup, error) {
	value, err := daemon2.NewToolPlanSource(dependency0)
	if err != nil {
		var zero stage.ToolPlanSource
		return zero, nil, fmt.Errorf("construct bean daemonToolPlanSource (github.com/spice-framework/spice-agent/stage.ToolPlanSource, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|17:NewToolPlanSource): %w", err)
	}
	return value, nil, nil
}

// ConstructDaemonInteractionBroker_bf812f17 performs the direct construction selected for bean "daemonInteractionBroker".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|20:NewInteractionBroker.
func ConstructDaemonInteractionBroker_bf812f17(dependency0 *daemon.PendingHub) (interaction.Broker, spicelifecycle.Cleanup, error) {
	value := daemon2.NewInteractionBroker(dependency0)
	return value, nil, nil
}

// ConstructDaemonEngine_10b0c974 performs the direct construction selected for bean "daemonEngine".
// Spice source identity: spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine.
func ConstructDaemonEngine_10b0c974(dependency0 model.Provider, dependency1 stage.ToolPlanSource, dependency2 interaction.Broker) (*agent.Engine, spicelifecycle.Cleanup, error) {
	value, err := daemon2.NewEngine(dependency0, dependency1, dependency2)
	if err != nil {
		var zero *agent.Engine
		return zero, nil, fmt.Errorf("construct bean daemonEngine (*github.com/spice-framework/spice-agent/agent.Engine, source spice:symbol:v1|function|61:github.com/spice-framework/spice-agent-coding/internal/daemon|0:|9:NewEngine): %w", err)
	}
	return value, nil, nil
}
