//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: vendor/github.com/spice-framework/spice-agent/logging/autoconfigure/autoconfigure.go:18
// Source: vendor/github.com/spice-framework/spice-agent/logging/autoconfigure/autoconfigure.go:23

package spicegen

import (
	fmt "fmt"

	event "github.com/spice-framework/spice-agent/event"
	logging "github.com/spice-framework/spice-agent/logging"
	autoconfigure "github.com/spice-framework/spice-agent/logging/autoconfigure"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
	logging2 "github.com/spice-framework/spice/logging"
)

// ConstructAgentLoggingMailbox_42d3a702 performs the direct construction selected for bean "agentLoggingMailbox".
// Spice source identity: spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|14:DefaultMailbox.
func ConstructAgentLoggingMailbox_42d3a702(dependency0 logging.Config) (*event.BestEffortObserver, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultMailbox(dependency0)
	if err != nil {
		var zero *event.BestEffortObserver
		return zero, nil, fmt.Errorf("construct bean agentLoggingMailbox (*github.com/spice-framework/spice-agent/event.BestEffortObserver, source spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|14:DefaultMailbox): %w", err)
	}
	return value, nil, nil
}

// ConstructAgentLoggingProcessor_a4291fa3 performs the direct construction selected for bean "agentLoggingProcessor".
// Spice source identity: spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|16:DefaultProcessor.
func ConstructAgentLoggingProcessor_a4291fa3(dependency0 logging.Config, dependency1 *event.BestEffortObserver, dependency2 *logging2.Logger) (*logging.Processor, spicelifecycle.Cleanup, error) {
	value, cleanup, err := autoconfigure.DefaultProcessor(dependency0, dependency1, dependency2)
	if err != nil {
		var zero *logging.Processor
		return zero, nil, fmt.Errorf("construct bean agentLoggingProcessor (*github.com/spice-framework/spice-agent/logging.Processor, source spice:symbol:v1|function|60:github.com/spice-framework/spice-agent/logging/autoconfigure|0:|16:DefaultProcessor): %w", err)
	}
	return value, cleanup, nil
}
