//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: vendor/github.com/spice-framework/spice-agent-tools-coding/autoconfigure/autoconfigure.go:12
// Source: vendor/github.com/spice-framework/spice-agent-tools-coding/autoconfigure/autoconfigure.go:17
// Source: vendor/github.com/spice-framework/spice-agent-tools-coding/autoconfigure/autoconfigure.go:22

package spicegen

import (
	fmt "fmt"

	coding "github.com/spice-framework/spice-agent-tools-coding"
	autoconfigure "github.com/spice-framework/spice-agent-tools-coding/autoconfigure"
	tool "github.com/spice-framework/spice-agent/tool"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructRead_1b770715 performs the direct construction selected for bean "read".
// Spice source identity: spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead.
func ConstructRead_1b770715(dependency0 coding.Config) (tool.Tool, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultRead(dependency0)
	if err != nil {
		var zero tool.Tool
		return zero, nil, fmt.Errorf("construct bean read (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|11:DefaultRead): %w", err)
	}
	return value, nil, nil
}

// ConstructShell_a48b269f performs the direct construction selected for bean "shell".
// Spice source identity: spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell.
func ConstructShell_a48b269f(dependency0 coding.Config) (tool.Tool, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultShell(dependency0)
	if err != nil {
		var zero tool.Tool
		return zero, nil, fmt.Errorf("construct bean shell (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|12:DefaultShell): %w", err)
	}
	return value, nil, nil
}

// ConstructReplace_96382d5b performs the direct construction selected for bean "replace".
// Spice source identity: spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace.
func ConstructReplace_96382d5b(dependency0 coding.Config) (tool.Tool, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultReplace(dependency0)
	if err != nil {
		var zero tool.Tool
		return zero, nil, fmt.Errorf("construct bean replace (github.com/spice-framework/spice-agent/tool.Tool, source spice:symbol:v1|function|65:github.com/spice-framework/spice-agent-tools-coding/autoconfigure|0:|14:DefaultReplace): %w", err)
	}
	return value, nil, nil
}
