//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: cmd/spice-agentd/application.go:19

package spicegen

// ApplicationTargetSpiceAgentd_d556aede identifies the generated target selected by spice:symbol:v1|function|62:github.com/spice-framework/spice-agent-coding/cmd/spice-agentd|0:|4:main.
const ApplicationTargetSpiceAgentd_d556aede = "spice_agentd"
