//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: vendor/github.com/spice-framework/spice-agent/plugin/host/autoconfigure/autoconfigure.go:23
// Source: vendor/github.com/spice-framework/spice-agent/plugin/host/autoconfigure/autoconfigure.go:29
// Source: vendor/github.com/spice-framework/spice-agent/plugin/host/autoconfigure/autoconfigure.go:36
// Source: vendor/github.com/spice-framework/spice-agent/plugin/host/autoconfigure/autoconfigure.go:58

package spicegen

import (
	fmt "fmt"

	pluginhost "github.com/spice-framework/spice-agent/plugin/host"
	autoconfigure "github.com/spice-framework/spice-agent/plugin/host/autoconfigure"
	pluginv1 "github.com/spice-framework/spice-agent/plugin/v1"
	process "github.com/spice-framework/spice-agent/process"
	stage "github.com/spice-framework/spice-agent/stage"
	tool "github.com/spice-framework/spice-agent/tool"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructRuntimePluginHost_335c4779 performs the direct construction selected for bean "runtimePluginHost".
// Spice source identity: spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|11:DefaultHost.
func ConstructRuntimePluginHost_335c4779(dependency0 *pluginv1.BuildIdentity, dependency1 stage.ToolDispatcher, dependency2 []stage.ToolDispatchDecorator, dependency3 process.Launcher, dependency4 pluginhost.LocalEndpointFactory) (*pluginhost.Host, spicelifecycle.Cleanup, error) {
	value, cleanup, err := autoconfigure.DefaultHost(dependency0, dependency1, dependency2, dependency3, dependency4)
	if err != nil {
		var zero *pluginhost.Host
		return zero, nil, fmt.Errorf("construct bean runtimePluginHost (*github.com/spice-framework/spice-agent/plugin/host.Host, source spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|11:DefaultHost): %w", err)
	}
	return value, cleanup, nil
}

// ConstructRuntimePluginToolPlanSource_db29b3aa performs the direct construction selected for bean "runtimePluginToolPlanSource".
// Spice source identity: spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|21:DefaultToolPlanSource.
func ConstructRuntimePluginToolPlanSource_db29b3aa(dependency0 *pluginhost.Host) (stage.ToolPlanSource, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultToolPlanSource(dependency0)
	if err != nil {
		var zero stage.ToolPlanSource
		return zero, nil, fmt.Errorf("construct bean runtimePluginToolPlanSource (github.com/spice-framework/spice-agent/stage.ToolPlanSource, source spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|21:DefaultToolPlanSource): %w", err)
	}
	return value, nil, nil
}

// ConstructRuntimePluginCompiledDispatcher_288d6ba6 performs the direct construction selected for bean "runtimePluginCompiledDispatcher".
// Spice source identity: spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|25:DefaultCompiledDispatcher.
func ConstructRuntimePluginCompiledDispatcher_288d6ba6(dependency0 map[string]tool.Tool) (stage.ToolDispatcher, spicelifecycle.Cleanup, error) {
	value, err := autoconfigure.DefaultCompiledDispatcher(dependency0)
	if err != nil {
		var zero stage.ToolDispatcher
		return zero, nil, fmt.Errorf("construct bean runtimePluginCompiledDispatcher (github.com/spice-framework/spice-agent/stage.ToolDispatcher, source spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|25:DefaultCompiledDispatcher): %w", err)
	}
	return value, nil, nil
}

// ConstructRuntimePluginEndpointFactory_d1bddc00 performs the direct construction selected for bean "runtimePluginEndpointFactory".
// Spice source identity: spice:symbol:v1|function|64:github.com/spice-framework/spice-agent/plugin/host/autoconfigure|0:|33:DefaultCurrentUserEndpointFactory.
func ConstructRuntimePluginEndpointFactory_d1bddc00() (pluginhost.LocalEndpointFactory, spicelifecycle.Cleanup, error) {
	value := autoconfigure.DefaultCurrentUserEndpointFactory()
	return value, nil, nil
}
